CREATE TABLE BB_LIVE_SUBJECTS
(
    REPORTING_PERIOD DATE,
    FI_SUBJECT_CODE VARCHAR2(16)
);

ALTER TABLE BB_LIVE_SUBJECTS
ADD CONSTRAINT PK_BB_LIVE_SUBJECTS PRIMARY KEY (REPORTING_PERIOD, FI_SUBJECT_CODE);

