CREATE TABLE BB_LIVE_CONTRACTS
(
    REPORTING_PERIOD DATE,
    CONTRACT_CODE VARCHAR(16),
    FI_CONTRACT_CODE VARCHAR2(16),
    CONTRACT_TYPE VARCHAR2(1)
);

ALTER TABLE BB_LIVE_CONTRACTS
ADD CONSTRAINT PK_BB_LIVE_CONTRACTS PRIMARY KEY (REPORTING_PERIOD, FI_CONTRACT_CODE);

