CREATE TABLE BRANCHES 
(
    BRANCH_CODE VARCHAR2(4) NOT NULL ENABLE, 
    BRANCH_NAME VARCHAR2(100) NOT NULL ENABLE, 
    CIB_BRANCH_CODE VARCHAR2(4) NOT NULL ENABLE, 
    MAKE_BY VARCHAR2(30) NOT NULL ENABLE, 
    MAKE_DATE DATE NOT NULL ENABLE, 
    ISLAMIC_WINDOW_BRANCH_CODE VARCHAR2(3),
    CONSTRAINT BRANCHES_PK PRIMARY KEY (BRANCH_CODE)
)
