CREATE TABLE INSTITUTIONS 
(
    RECORD_TYPE VARCHAR2(1) NOT NULL ENABLE, 
    FI_CODE VARCHAR2(3) NOT NULL ENABLE, 
    BRANCH_CODE VARCHAR2(4), 
    FI_SUBJECT_CODE VARCHAR2(16) NOT NULL ENABLE, 
    TITLE VARCHAR2(20), 
    TRADE_NAME VARCHAR2(130) NOT NULL ENABLE, 
    SECTOR_TYPE NUMBER(1,0), 
    SECTOR_CODE NUMBER(6,0), 
    LEGAL_FORM NUMBER(2,0) NOT NULL ENABLE, 
    REGISTRATION_NUMBER_RJSC VARCHAR2(15), 
    REGISTRATION_DATE_RJSC DATE, 
    TIN VARCHAR2(12), 
    BUSINESS_ADDRESS_STREET VARCHAR2(100), 
    BUSINESS_ADDRESS_POSTAL_CODE NUMBER(4,0), 
    BUSINESS_ADDRESS_DISTRICT VARCHAR2(20), 
    BUSINESS_ADDRESS_COUNTRY VARCHAR2(2), 
    FACTORY_ADDRESS_STREET VARCHAR2(100), 
    FACTORY_ADDRESS_POSTAL_CODE NUMBER(4,0), 
    FACTORY_ADDRESS_DISTRICT VARCHAR2(20), 
    FACTORY_ADDRESS_COUNTRY VARCHAR2(2), 
    CRG_SCORING NUMBER(3,0), 
    CREDIT_RATING NUMBER(3,0), 
    PHONE_NUMBER VARCHAR2(40), 
    MAKE_BY VARCHAR2(30), 
    MAKE_DATE DATE, 
    RECORD_STATUS VARCHAR2(1), 
    CIF_NO VARCHAR2(9), 
    CONSTRAINT INSTITUTIONS_UK1 UNIQUE (CIF_NO),
    CONSTRAINT INSTITUTIONS_PK PRIMARY KEY (FI_SUBJECT_CODE)
);

CREATE INDEX INSTITUTIONS_REC_STAT ON INSTITUTIONS (RECORD_STATUS);
CREATE UNIQUE INDEX INSTITUTIONS_UK1 ON INSTITUTIONS (CIF_NO);
CREATE UNIQUE INDEX INSTITUTIONS_PK ON INSTITUTIONS (FI_SUBJECT_CODE);
