CREATE TABLE NON_INSTALMENT_CONTRACTS 
(	
	RECORD_TYPE VARCHAR2(1) NOT NULL ENABLE, 
	FI_CODE VARCHAR2(3) NOT NULL ENABLE, 
	BRANCH_CODE VARCHAR2(4), 
	FI_SUBJECT_CODE VARCHAR2(16) NOT NULL ENABLE, 
	FI_CONTRACT_CODE VARCHAR2(16) NOT NULL ENABLE, 
	CONTRACT_TYPE VARCHAR2(2) NOT NULL ENABLE, 
	CONTRACT_PHASE VARCHAR2(2) NOT NULL ENABLE, 
	CONTRACT_STATUS VARCHAR2(1) NOT NULL ENABLE, 
	CURRENCY_CODE VARCHAR2(3) NOT NULL ENABLE, 
	STARTING_DATE DATE, 
	REQUEST_DATE DATE, 
	PLANNED_END_DATE DATE, 
	ACTUAL_END_DATE DATE, 
	DEFAULTER_STATUS VARCHAR2(1) NOT NULL ENABLE, 
	DATE_OF_LAST_PAYMENT DATE, 
	SUBSIDIZED_CREDIT VARCHAR2(1), 
	PRE_FINANCE_LOAN VARCHAR2(1), 
	REORGANIZED_CREDIT VARCHAR2(1), 
	THIRD_PARTY_GUARANTEE_TYPE VARCHAR2(3), 
	SECURITY_TYPE VARCHAR2(3), 
	AMOUNT_GUARANTEED_THIRD_PARTY NUMBER(12,0), 
	AMOUNT_GUARANTEED_SECURITY NUMBER(12,0), 
	QUALITATIVE_JUDGEMENT VARCHAR2(1), 
	SANCTION_LIMIT NUMBER(12,0) NOT NULL ENABLE, 
	TOTAL_OUTSTANDING_AMOUNT NUMBER(12,0) NOT NULL ENABLE, 
	NO_OF_DAYS_PAYMENT_DELAY NUMBER(3,0), 
	DUE_FOR_RECOVERY NUMBER(12,0), 
	RECOVERY_DURING_REPORTING NUMBER(12,0), 
	CUMULATIVE_RECOVERY NUMBER(12,0), 
	DATE_OF_LAW_SUIT DATE, 
	DATE_OF_CLASSIFICATION DATE, 
	NO_OF_TIMES_RESCHEDULING VARCHAR2(6), 
	DATE_LAST_RESCHEDULING DATE, 
	ECONOMIC_PURPOSE_CODE VARCHAR2(4), 
	SME VARCHAR2(1), 
	ENTERPRISE_TYPE VARCHAR2(2), 
	MAKE_BY VARCHAR2(30), 
	MAKE_DATE DATE, 
	RECORD_STATUS VARCHAR2(1), 
	CONSTRAINT NON_INSTALMENT_CONTRACTS_PK PRIMARY KEY (FI_CONTRACT_CODE)
);

COMMENT ON COLUMN NON_INSTALMENT_CONTRACTS.NO_OF_TIMES_RESCHEDULING IS 'this actually is number(6)';

CREATE INDEX NON_INSTALMENT_CONTRACTS_RSTAT ON UCIBTEST.NON_INSTALMENT_CONTRACTS (RECORD_STATUS);

ALTER TABLE NON_INSTALMENT_CONTRACTS
ADD UBS_ACCOUNT_NO VARCHAR2(16) NULL;

ALTER TABLE NON_INSTALMENT_CONTRACTS
ADD CONSTRAINT NON_INS_CNT_UNIQ_UBS_ACC_NO UNIQUE(UBS_ACCOUNT_NO);