CREATE SEQUENCE "SEQ_INSTITUTION" MAXVALUE 99999999 START WITH 99570;
CREATE SEQUENCE "SEQ_PERSON" MAXVALUE 99999999 START WITH 254878;

CREATE TABLE "LOV_GENDER" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(20 BYTE) NOT NULL
);
ALTER TABLE "LOV_GENDER" ADD CONSTRAINT "LOV_GENDER_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_LINK_TYPES" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(20 BYTE) NOT NULL
);
ALTER TABLE "LOV_LINK_TYPES" ADD CONSTRAINT "LOV_LINK_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_CONTRACT_PHASES" (
  "CODE" VARCHAR2(2 BYTE) NOT NULL,
  "NAME" VARCHAR2(30 BYTE) NOT NULL
);
ALTER TABLE "LOV_CONTRACT_PHASES" ADD CONSTRAINT "LOV_CONTRACT_PHASES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_SUBSIDIZED_CREDIT" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(30 BYTE) NOT NULL
);
ALTER TABLE "LOV_SUBSIDIZED_CREDIT" ADD CONSTRAINT "LOV_SUBSIDIZED_CREDIT_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_PRE_FINANCE_OF_LOAN" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE) NOT NULL
);
ALTER TABLE "LOV_PRE_FINANCE_OF_LOAN" ADD CONSTRAINT "LOV_PRE_FINANCE_OF_LOAN_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_REORGANIZED_CREDIT" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(50 BYTE)
);
ALTER TABLE "LOV_REORGANIZED_CREDIT" ADD CONSTRAINT "LOV_REORGANIZED_CREDIT_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_PERIODICITY_OF_PAYMENT" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NOT NULL
);
ALTER TABLE "LOV_PERIODICITY_OF_PAYMENT" ADD CONSTRAINT "LOV_PERIODICITY_OF_PAYMENT_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_INSTALMENT_TYPES" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(20 BYTE) NOT NULL
);
ALTER TABLE "LOV_INSTALMENT_TYPES" ADD CONSTRAINT "LOV_INSTALMENT_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_LEASED_GOOD_TYPES" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NOT NULL
);
ALTER TABLE "LOV_LEASED_GOOD_TYPES" ADD CONSTRAINT "LOV_LEASED_GOOD_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_PAYMENT_METHODS" (
  "CODE" VARCHAR2(3 BYTE) NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NOT NULL
);
ALTER TABLE "LOV_PAYMENT_METHODS" ADD CONSTRAINT "LOV_PAYMENT_METHODS_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_3RD_PARTY_GUARANTEE_TYPES" (
  "CODE" VARCHAR2(3 BYTE) NOT NULL,
  "NAME" VARCHAR2(70 BYTE) NOT NULL
);
ALTER TABLE "LOV_3RD_PARTY_GUARANTEE_TYPES" ADD CONSTRAINT "LOV_3RD_PARTY_GUARANTEE_TY_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_SECURITY_TYPES" (
  "CODE" VARCHAR2(2 BYTE) NOT NULL,
  "NAME" VARCHAR2(150 BYTE) NOT NULL
);
ALTER TABLE "LOV_SECURITY_TYPES" ADD CONSTRAINT "LOV_SECURITY_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_ID_TYPES" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(30 BYTE) NOT NULL
);
ALTER TABLE "LOV_ID_TYPES" ADD CONSTRAINT "LOV_ID_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_OWNER_TYPES" (
  "CODE" VARCHAR2(2 BYTE) NOT NULL,
  "NAME" VARCHAR2(100 BYTE) NOT NULL
);
ALTER TABLE "LOV_OWNER_TYPES" ADD CONSTRAINT "LOB_OWNER_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_SECTOR_TYPES" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(20 BYTE) NOT NULL
);
ALTER TABLE "LOV_SECTOR_TYPES" ADD CONSTRAINT "LOB_SECTOR_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_INSTITUTION_LEGAL_FORMS" (
  "CODE" VARCHAR2(2 BYTE) NOT NULL,
  "NAME" VARCHAR2(30 BYTE) NOT NULL
);
ALTER TABLE "LOV_INSTITUTION_LEGAL_FORMS" ADD CONSTRAINT "LOB_INSTITUTION_LEGAL_FORM_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_CONTRACT_STATUS" (
  "CODE" VARCHAR2(1 BYTE) NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NOT NULL
);
ALTER TABLE "LOV_CONTRACT_STATUS" ADD CONSTRAINT "LOV_CONTRACT_STATUS_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_CONTRACT_TYPES" (
  "CODE" VARCHAR2(2 BYTE) NOT NULL,
  "NAME" VARCHAR2(100 BYTE) NOT NULL,
  "CATEGORY" VARCHAR2(20 BYTE) NOT NULL
);
ALTER TABLE "LOV_CONTRACT_TYPES" ADD CONSTRAINT "LOV_CONTRACT_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_SECTOR_CODES" (
  "CODE" VARCHAR2(6 BYTE) NOT NULL,
  "NAME" VARCHAR2(250 BYTE) NOT NULL
);
ALTER TABLE "LOV_SECTOR_CODES" ADD CONSTRAINT "LOV_SECTOR_CODES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_COUNTRIES" (
  "CODE" VARCHAR2(3 BYTE) NOT NULL,
  "NAME" VARCHAR2(100 BYTE) NOT NULL
);
ALTER TABLE "LOV_COUNTRIES" ADD CONSTRAINT "LOV_COUNTRIES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_CURRENCIES" (
  "CODE" VARCHAR2(4 BYTE) NOT NULL,
  "NAME" VARCHAR2(200 BYTE) NOT NULL
);
ALTER TABLE "LOV_CURRENCIES" ADD CONSTRAINT "LOV_CURRENCIES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_ECONOMIC_PURPOSE_CODES" (
  "CODE" VARCHAR2(6 BYTE) NOT NULL,
  "NAME" VARCHAR2(150 BYTE) NOT NULL
);
ALTER TABLE "LOV_ECONOMIC_PURPOSE_CODES" ADD CONSTRAINT "LOV_ECONOMIC_PURPOSES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_DISTRICTS" (
  "DISTRICT_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "COUNTRY_CODE" VARCHAR2(3 BYTE) NOT NULL
);

CREATE TABLE "LOV_NO_OF_DAYS" (
  "CODE" VARCHAR2(3 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE) NOT NULL
);
ALTER TABLE "LOV_NO_OF_DAYS" ADD CONSTRAINT "LOV_NO_OF_DAYS_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_ENTERPRISE_TYPES" (
  "CODE" VARCHAR2(2 BYTE) NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NOT NULL
);
ALTER TABLE "LOV_ENTERPRISE_TYPES" ADD CONSTRAINT "LOV_ENTERPRISE_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "PERSONAL_DATA" (
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "TITLE" VARCHAR2(20 BYTE),
  "NAME" VARCHAR2(70 BYTE) NOT NULL,
  "FATHERS_TITLE" VARCHAR2(20 BYTE),
  "FATHERS_NAME" VARCHAR2(70 BYTE),
  "MOTHERS_TITLE" VARCHAR2(20 BYTE),
  "MOTHERS_NAME" VARCHAR2(70 BYTE),
  "SPOUSES_TITLE" VARCHAR2(20 BYTE),
  "SPOUSES_NAME" VARCHAR2(70 BYTE),
  "SECTOR_TYPE" NUMBER(1,0),
  "SECTOR_CODE" NUMBER(6,0),
  "GENDER" VARCHAR2(1 BYTE),
  "DATE_OF_BIRTH" DATE NOT NULL,
  "PLACE_OF_BIRTH" VARCHAR2(20 BYTE),
  "COUNTRY_OF_BIRTH" VARCHAR2(2 BYTE) NOT NULL,
  "NATIONAL_ID_NUMBER" VARCHAR2(17 BYTE),
  "NATIONAL_ID_AVAILABLE" NUMBER(1,0),
  "TIN" VARCHAR2(12 BYTE),
  "PERMANENT_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "PERMANENT_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "PERMANENT_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "PERMANENT_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "PRESENT_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "PRESENT_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "PRESENT_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "PRESENT_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "BUSINESS_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "BUSINESS_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "BUSINESS_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "BUSINESS_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "ID_TYPE" VARCHAR2(1 BYTE),
  "ID_NUMBER" VARCHAR2(20 BYTE),
  "ID_ISSUE_DATE" DATE,
  "ID_ISSUE_COUNTRY" VARCHAR2(2 BYTE),
  "PHONE_NUMBER" VARCHAR2(40 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "CIF_NO" VARCHAR2(9 BYTE),
  "SMART_ID_NUMBER" VARCHAR2(10 BYTE)
);
ALTER TABLE "PERSONAL_DATA" ADD CONSTRAINT "PERSONAL_DATA_UK1" UNIQUE ("CIF_NO");
ALTER TABLE "PERSONAL_DATA" ADD CONSTRAINT "PERSONAL_DATA_PK" PRIMARY KEY ("FI_SUBJECT_CODE");
CREATE INDEX "PERSONAL_DATA_REC_STAT" ON "PERSONAL_DATA" ("RECORD_STATUS");

CREATE TABLE "INSTITUTIONS" (
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "TITLE" VARCHAR2(20 BYTE),
  "TRADE_NAME" VARCHAR2(130 BYTE) NOT NULL,
  "SECTOR_TYPE" NUMBER(1,0),
  "SECTOR_CODE" NUMBER(6,0),
  "LEGAL_FORM" NUMBER(2,0) NOT NULL,
  "REGISTRATION_NUMBER_RJSC" VARCHAR2(15 BYTE),
  "REGISTRATION_DATE_RJSC" DATE,
  "TIN" VARCHAR2(12 BYTE),
  "BUSINESS_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "BUSINESS_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "BUSINESS_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "BUSINESS_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "FACTORY_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "FACTORY_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "FACTORY_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "FACTORY_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "CRG_SCORING" NUMBER(3,0),
  "CREDIT_RATING" NUMBER(3,0),
  "PHONE_NUMBER" VARCHAR2(40 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "CIF_NO" VARCHAR2(9 BYTE)
);
ALTER TABLE "INSTITUTIONS" ADD CONSTRAINT "INSTITUTIONS_UK1" UNIQUE ("CIF_NO");
ALTER TABLE "INSTITUTIONS" ADD CONSTRAINT "INSTITUTIONS_PK" PRIMARY KEY ("FI_SUBJECT_CODE");
CREATE INDEX "INSTITUTIONS_REC_STAT" ON "INSTITUTIONS" ("RECORD_STATUS");

CREATE TABLE "INSTITUTION_OWNER_LINKS" (
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "INSTITUTION_FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ROLE" VARCHAR2(2 BYTE) NOT NULL,
  "OWNER_FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE)
);
ALTER TABLE "INSTITUTION_OWNER_LINKS" ADD CONSTRAINT "INSTITUTION_OWNER_LINKS_PK" PRIMARY KEY ("INSTITUTION_FI_SUBJECT_CODE", "OWNER_FI_SUBJECT_CODE");
CREATE INDEX "OWNER_LINKS_REC_STAT" ON "INSTITUTION_OWNER_LINKS" ("RECORD_STATUS");
CREATE INDEX "OWNER_LINKS_ROLE" ON "INSTITUTION_OWNER_LINKS" ("ROLE");

CREATE TABLE "INSTALMENT_CONTRACTS" (
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "CONTRACT_TYPE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_PHASE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "STARTING_DATE" DATE,
  "REQUEST_DATE" DATE,
  "PLANNED_END_DATE" DATE,
  "ACTUAL_END_DATE" DATE,
  "DEFAULTER_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "LAST_PAYMENT_DATE" DATE,
  "SUBSIDIZED_CREDIT" VARCHAR2(1 BYTE),
  "PRE_FINANCE_LOAN" VARCHAR2(1 BYTE),
  "REORGANIZED_CREDIT" VARCHAR2(1 BYTE),
  "THIRD_PARTY_GUARANTEE_TYPE" VARCHAR2(3 BYTE),
  "SECURITY_TYPE" VARCHAR2(3 BYTE),
  "AMOUNT_GURANTEED_THIRD_PARTY" NUMBER(12,0),
  "AMOUNT_GUARANTEED_SECURITY" NUMBER(12,0),
  "QUALIFICATION_JUDGEMENT" VARCHAR2(1 BYTE),
  "SANCTION_LIMIT" NUMBER(12,0) NOT NULL,
  "TOTAL_DISBURSED_AMOUNT" NUMBER(12,0) NOT NULL,
  "TOTAL_OUTSTANDING_AMOUNT" NUMBER(12,0) NOT NULL,
  "TOTAL_NUMBER_INSTALMENTS" NUMBER(3,0) NOT NULL,
  "PERIODICITY_PAYMENT" VARCHAR2(1 BYTE) NOT NULL,
  "METHOD_PAYMENT" VARCHAR2(3 BYTE),
  "INSTALMENT_AMOUNT" NUMBER(12,0),
  "EXPIRATION_DATE_NEXT_INST" DATE,
  "AMOUNT_NEXT_EXPIRING_INST" NUMBER(12,0),
  "NO_OF_REMAINING_INSTALMENT" NUMBER(3,0),
  "REMAINING_AMOUNT" NUMBER(12,0),
  "NO_OF_OVERDUE_INSTALMENT" NUMBER(3,0),
  "OVERDUE_AMOUNT" NUMBER(12,0),
  "NO_OF_DAYS_PAYMENT_DELAY" NUMBER(3,0),
  "TYPE_OF_LEASED_GOOD" VARCHAR2(1 BYTE),
  "VALUE_OF_LEASED_GOOD" NUMBER(12,0),
  "REGISTRATION_NUMBER" VARCHAR2(40 BYTE),
  "DATE_OF_MANUFACTURING" DATE,
  "DUE_FOR_RECOVERY" NUMBER(12,0),
  "RECOVERY_DURING_REPORTING" NUMBER(12,0),
  "CUMULATIVE_RECOVERY" NUMBER(12,0),
  "DATE_OF_LAW_SUIT" DATE,
  "DATE_OF_CLASSIFICATION" DATE,
  "NO_TIMES_RESCHEDULING" VARCHAR2(6 BYTE),
  "DATE_LAST_RESCHEDULING" DATE,
  "ECONOMIC_PURPOSE_CODE" VARCHAR2(4 BYTE),
  "SME" VARCHAR2(1 BYTE),
  "ENTERPRISE_TYPE" VARCHAR2(2 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "UBS_ACCOUNT_NO" VARCHAR2(16 BYTE)
);
ALTER TABLE "INSTALMENT_CONTRACTS" ADD CONSTRAINT "INS_CNT_UNIQ_UBS_ACCOUNT_NO" UNIQUE ("UBS_ACCOUNT_NO");
ALTER TABLE "INSTALMENT_CONTRACTS" ADD CONSTRAINT "INSTALMENT_CONTRACTS_PK" PRIMARY KEY ("FI_CONTRACT_CODE");

COMMENT ON COLUMN "INSTALMENT_CONTRACTS"."NO_TIMES_RESCHEDULING" IS 'this actually is Number(6)';
CREATE INDEX "INSTALMENT_CONTRACTS_REC_STAT" ON "INSTALMENT_CONTRACTS" ("RECORD_STATUS");

CREATE TABLE "CARD_CONTRACTS" (
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "CONTRACT_TYPE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_PHASE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "STARTING_DATE" DATE,
  "REQUEST_DATE" DATE,
  "PLANNED_END_DATE" DATE,
  "ACTUAL_END_DATE" DATE,
  "DEFAULTER_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "DATE_LAST_PAYMENT" DATE,
  "SUBSIDIZED_CREDIT" VARCHAR2(1 BYTE),
  "PRE_FINANCE_OF_LOAN" VARCHAR2(1 BYTE),
  "REORGANIZED_CREDIT" VARCHAR2(1 BYTE),
  "THIRD_PARTY_GUARANTEE_TYPE" VARCHAR2(3 BYTE),
  "SECURITY_TYPE" VARCHAR2(3 BYTE),
  "AMOUNT_GUARANTEED_THIRD_PARTY" NUMBER(12,0),
  "AMOUNT_GUARANTEED_SECURITY" NUMBER(12,0),
  "QUALITATIVE_JUDGEMENT" VARCHAR2(1 BYTE),
  "PERIODICITY_PAYMENT" VARCHAR2(1 BYTE),
  "METHOD_OF_PAYMENT" VARCHAR2(3 BYTE),
  "INSTALMENT_AMOUNT" NUMBER(12,0),
  "CREDIT_LIMIT" NUMBER(12,0) NOT NULL,
  "TOTAL_OUTSTANDING_AMOUNT" NUMBER(12,0) NOT NULL,
  "EXPIRATION_DATE_NEXT_INST" DATE,
  "REMAINING_AMOUNT" NUMBER(12,0),
  "NUMBER_OF_OVERDUE" NUMBER(3,0),
  "OVERDUE_AMOUNT" NUMBER(12,0),
  "DATE_OF_LAST_CHARGE" DATE,
  "TYPE_OF_INSTALMENT" VARCHAR2(1 BYTE) NOT NULL,
  "NO_OF_DAYS_PAYMENT_DELAY" NUMBER(3,0),
  "DUE_FOR_RECOVERY" NUMBER(12,0),
  "RECOVERY_DURING_REPORTING" NUMBER(12,0),
  "CUMULATIVE_RECOVERY" NUMBER(12,0),
  "DATE_OF_LAW_SUIT" DATE,
  "ECONOMIC_PURPOSE_CODE" VARCHAR2(4 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "DATE_OF_CLASSIFICATION" DATE
);
ALTER TABLE "CARD_CONTRACTS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("FI_CONTRACT_CODE");
CREATE INDEX "CARD_CONTRACTS_REC_STAT" ON "CARD_CONTRACTS" ("RECORD_STATUS");

CREATE TABLE "NON_INSTALMENT_CONTRACTS" (
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "CONTRACT_TYPE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_PHASE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "STARTING_DATE" DATE,
  "REQUEST_DATE" DATE,
  "PLANNED_END_DATE" DATE,
  "ACTUAL_END_DATE" DATE,
  "DEFAULTER_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "DATE_OF_LAST_PAYMENT" DATE,
  "SUBSIDIZED_CREDIT" VARCHAR2(1 BYTE),
  "PRE_FINANCE_LOAN" VARCHAR2(1 BYTE),
  "REORGANIZED_CREDIT" VARCHAR2(1 BYTE),
  "THIRD_PARTY_GUARANTEE_TYPE" VARCHAR2(3 BYTE),
  "SECURITY_TYPE" VARCHAR2(3 BYTE),
  "AMOUNT_GUARANTEED_THIRD_PARTY" NUMBER(12,0),
  "AMOUNT_GUARANTEED_SECURITY" NUMBER(12,0),
  "QUALITATIVE_JUDGEMENT" VARCHAR2(1 BYTE),
  "SANCTION_LIMIT" NUMBER(12,0) NOT NULL,
  "TOTAL_OUTSTANDING_AMOUNT" NUMBER(12,0) NOT NULL,
  "NO_OF_DAYS_PAYMENT_DELAY" NUMBER(3,0),
  "DUE_FOR_RECOVERY" NUMBER(12,0),
  "RECOVERY_DURING_REPORTING" NUMBER(12,0),
  "CUMULATIVE_RECOVERY" NUMBER(12,0),
  "DATE_OF_LAW_SUIT" DATE,
  "DATE_OF_CLASSIFICATION" DATE,
  "NO_OF_TIMES_RESCHEDULING" VARCHAR2(6 BYTE),
  "DATE_LAST_RESCHEDULING" DATE,
  "ECONOMIC_PURPOSE_CODE" VARCHAR2(4 BYTE),
  "SME" VARCHAR2(1 BYTE),
  "ENTERPRISE_TYPE" VARCHAR2(2 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "UBS_ACCOUNT_NO" VARCHAR2(16 BYTE)
);
ALTER TABLE "NON_INSTALMENT_CONTRACTS" ADD CONSTRAINT "NON_INS_CNT_UNIQ_UBS_ACC_NO" UNIQUE ("UBS_ACCOUNT_NO");
ALTER TABLE "NON_INSTALMENT_CONTRACTS" ADD CONSTRAINT "NON_INSTALMENT_CONTRACTS_PK" PRIMARY KEY ("FI_CONTRACT_CODE");

COMMENT ON COLUMN "NON_INSTALMENT_CONTRACTS"."NO_OF_TIMES_RESCHEDULING" IS 'this actually is number(6)';
CREATE INDEX "NON_INSTALMENT_CONTRACTS_RSTAT" ON "NON_INSTALMENT_CONTRACTS" ("RECORD_STATUS");

CREATE TABLE "CONTRACT_LINKS" (
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "TYPE_OF_LINK" VARCHAR2(1 BYTE) NOT NULL,
  "FI_PRIMARY_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_SECONDARY_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE)
);
ALTER TABLE "CONTRACT_LINKS" ADD CONSTRAINT "CONTRACT_LINKS_PK" PRIMARY KEY ("FI_PRIMARY_CODE", "FI_SECONDARY_CODE", "FI_CONTRACT_CODE");
CREATE INDEX "CONTRACT_LINKS_REC_STAT" ON "CONTRACT_LINKS" ("RECORD_STATUS");
CREATE INDEX "CONTRACT_LINKS_TYPEOFLINK" ON "CONTRACT_LINKS" ("TYPE_OF_LINK");

CREATE TABLE "APP_USERS" (
  "EMPID" NUMBER(10,0) NOT NULL,
  "ADID" VARCHAR2(30 BYTE) NOT NULL,
  "FULLNAME" VARCHAR2(100 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE) NOT NULL,
  "STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "AD" VARCHAR2(20 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "APP_USERS" ADD CONSTRAINT "APP_USERS_PK" PRIMARY KEY ("EMPID", "ADID");

CREATE TABLE "APP_ROLES" (
  "ROLE_CODE" VARCHAR2(10 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL,
  "STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "APP_ROLES" ADD CONSTRAINT "APP_ROLES_PK" PRIMARY KEY ("ROLE_CODE");

CREATE TABLE "APP_USER_ROLES" (
  "EMPID" NUMBER(10,0) NOT NULL,
  "ROLE_CODE" VARCHAR2(10 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "APP_USER_ROLES" ADD CONSTRAINT "APP_USER_ROLES_PK" PRIMARY KEY ("EMPID", "ROLE_CODE");

CREATE TABLE "APP_ROLE_GROUPS" (
  "GROUP_CODE" VARCHAR2(10 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL,
  "STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "APP_ROLE_GROUPS" ADD CONSTRAINT "APP_ROLE_GROUPS_PK" PRIMARY KEY ("GROUP_CODE");

CREATE TABLE "APP_ROLE_GROUP_ROLES" (
  "GROUP_CODE" VARCHAR2(10 BYTE) NOT NULL,
  "ROLE_CODE" VARCHAR2(10 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "APP_ROLE_GROUP_ROLES" ADD CONSTRAINT "APP_ROLE_GROUP_ROLES_PK" PRIMARY KEY ("GROUP_CODE", "ROLE_CODE");

CREATE TABLE "APP_ROLE_GROUP_USERS" (
  "GROUP_CODE" VARCHAR2(10 BYTE) NOT NULL,
  "EMPID" NUMBER(10,0) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "APP_ROLE_GROUP_USERS" ADD CONSTRAINT "APP_ROLE_GROUP_USERS_PK" PRIMARY KEY ("GROUP_CODE", "EMPID");

CREATE TABLE "REPORTING_PARAMETERS" (
  "KEY" VARCHAR2(20 BYTE) NOT NULL,
  "VALUE" VARCHAR2(20 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "REPORTING_PARAMETERS" ADD CONSTRAINT "REPORTING_PARAMETERS_PK" PRIMARY KEY ("KEY");

CREATE TABLE "BRANCHES" (
  "BRANCH_CODE" VARCHAR2(4 BYTE) NOT NULL,
  "BRANCH_NAME" VARCHAR2(100 BYTE) NOT NULL,
  "CIB_BRANCH_CODE" VARCHAR2(4 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE) NOT NULL,
  "MAKE_DATE" DATE NOT NULL,
  "ISLAMIC_WINDOW_BRANCH_CODE" VARCHAR2(3 BYTE)
);
ALTER TABLE "BRANCHES" ADD CONSTRAINT "BRANCHES_PK" PRIMARY KEY ("BRANCH_CODE");

CREATE TABLE "REF_RECORD_STATUS" (
  "RECORD_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL,
  "REMARKS" VARCHAR2(100 BYTE)
);
ALTER TABLE "REF_RECORD_STATUS" ADD CONSTRAINT "REF_RECORD_STATUS_PK" PRIMARY KEY ("RECORD_STATUS");

CREATE TABLE "INSTALMENT_CONTRACTS_HIST" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "ENTRY_DATE" DATE,
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "CONTRACT_TYPE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_PHASE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "STARTING_DATE" DATE,
  "REQUEST_DATE" DATE,
  "PLANNED_END_DATE" DATE,
  "ACTUAL_END_DATE" DATE,
  "DEFAULTER_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "LAST_PAYMENT_DATE" DATE,
  "SUBSIDIZED_CREDIT" VARCHAR2(1 BYTE),
  "PRE_FINANCE_LOAN" VARCHAR2(1 BYTE),
  "REORGANIZED_CREDIT" VARCHAR2(1 BYTE),
  "THIRD_PARTY_GUARANTEE_TYPE" VARCHAR2(3 BYTE),
  "SECURITY_TYPE" VARCHAR2(3 BYTE),
  "AMOUNT_GURANTEED_THIRD_PARTY" NUMBER(12,0),
  "AMOUNT_GUARANTEED_SECURITY" NUMBER(12,0),
  "QUALIFICATION_JUDGEMENT" VARCHAR2(1 BYTE),
  "SANCTION_LIMIT" NUMBER(12,0) NOT NULL,
  "TOTAL_DISBURSED_AMOUNT" NUMBER(12,0) NOT NULL,
  "TOTAL_OUTSTANDING_AMOUNT" NUMBER(12,0) NOT NULL,
  "TOTAL_NUMBER_INSTALMENTS" NUMBER(3,0) NOT NULL,
  "PERIODICITY_PAYMENT" VARCHAR2(1 BYTE) NOT NULL,
  "METHOD_PAYMENT" VARCHAR2(3 BYTE),
  "INSTALMENT_AMOUNT" NUMBER(12,0),
  "EXPIRATION_DATE_NEXT_INST" DATE,
  "AMOUNT_NEXT_EXPIRING_INST" NUMBER(12,0),
  "NO_OF_REMAINING_INSTALMENT" NUMBER(3,0),
  "REMAINING_AMOUNT" NUMBER(12,0),
  "NO_OF_OVERDUE_INSTALMENT" NUMBER(3,0),
  "OVERDUE_AMOUNT" NUMBER(12,0),
  "NO_OF_DAYS_PAYMENT_DELAY" NUMBER(3,0),
  "TYPE_OF_LEASED_GOOD" VARCHAR2(1 BYTE),
  "VALUE_OF_LEASED_GOOD" NUMBER(12,0),
  "REGISTRATION_NUMBER" VARCHAR2(40 BYTE),
  "DATE_OF_MANUFACTURING" DATE,
  "DUE_FOR_RECOVERY" NUMBER(12,0),
  "RECOVERY_DURING_REPORTING" NUMBER(12,0),
  "CUMULATIVE_RECOVERY" NUMBER(12,0),
  "DATE_OF_LAW_SUIT" DATE,
  "DATE_OF_CLASSIFICATION" DATE,
  "NO_TIMES_RESCHEDULING" VARCHAR2(6 BYTE),
  "DATE_LAST_RESCHEDULING" DATE,
  "ECONOMIC_PURPOSE_CODE" VARCHAR2(4 BYTE),
  "SME" VARCHAR2(1 BYTE),
  "ENTERPRISE_TYPE" VARCHAR2(2 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "UBS_ACCOUNT_NO" VARCHAR2(16 BYTE)
);
ALTER TABLE "INSTALMENT_CONTRACTS_HIST" ADD CONSTRAINT "INSTALMENT_CONTRACT_HIST_PK" PRIMARY KEY ("VERSION_NO", "FI_CONTRACT_CODE");

CREATE TABLE "CARD_CONTRACTS_HIST" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "ENTRY_DATE" DATE,
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "CONTRACT_TYPE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_PHASE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "STARTING_DATE" DATE,
  "REQUEST_DATE" DATE,
  "PLANNED_END_DATE" DATE,
  "ACTUAL_END_DATE" DATE,
  "DEFAULTER_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "DATE_LAST_PAYMENT" DATE,
  "SUBSIDIZED_CREDIT" VARCHAR2(1 BYTE),
  "PRE_FINANCE_OF_LOAN" VARCHAR2(1 BYTE),
  "REORGANIZED_CREDIT" VARCHAR2(1 BYTE),
  "THIRD_PARTY_GUARANTEE_TYPE" VARCHAR2(3 BYTE),
  "SECURITY_TYPE" VARCHAR2(3 BYTE),
  "AMOUNT_GUARANTEED_THIRD_PARTY" NUMBER(12,0),
  "AMOUNT_GUARANTEED_SECURITY" NUMBER(12,0),
  "QUALITATIVE_JUDGEMENT" VARCHAR2(1 BYTE),
  "PERIODICITY_PAYMENT" VARCHAR2(1 BYTE),
  "METHOD_OF_PAYMENT" VARCHAR2(3 BYTE),
  "INSTALMENT_AMOUNT" NUMBER(12,0),
  "CREDIT_LIMIT" NUMBER(12,0) NOT NULL,
  "TOTAL_OUTSTANDING_AMOUNT" NUMBER(12,0) NOT NULL,
  "EXPIRATION_DATE_NEXT_INST" DATE,
  "REMAINING_AMOUNT" NUMBER(12,0),
  "NUMBER_OF_OVERDUE" NUMBER(3,0),
  "OVERDUE_AMOUNT" NUMBER(12,0),
  "DATE_OF_LAST_CHARGE" DATE,
  "TYPE_OF_INSTALMENT" VARCHAR2(1 BYTE) NOT NULL,
  "NO_OF_DAYS_PAYMENT_DELAY" NUMBER(3,0),
  "DUE_FOR_RECOVERY" NUMBER(12,0),
  "RECOVERY_DURING_REPORTING" NUMBER(12,0),
  "CUMULATIVE_RECOVERY" NUMBER(12,0),
  "DATE_OF_LAW_SUIT" DATE,
  "ECONOMIC_PURPOSE_CODE" VARCHAR2(4 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "DATE_OF_CLASSIFICATION" DATE
);
ALTER TABLE "CARD_CONTRACTS_HIST" ADD CONSTRAINT "CARD_CONTRACTS_HIST_PK" PRIMARY KEY ("FI_CONTRACT_CODE", "VERSION_NO");

CREATE TABLE "INSTITUTIONS_HIST" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "ENTRY_DATE" DATE,
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "TITLE" VARCHAR2(20 BYTE),
  "TRADE_NAME" VARCHAR2(130 BYTE) NOT NULL,
  "SECTOR_TYPE" NUMBER(1,0),
  "SECTOR_CODE" NUMBER(6,0),
  "LEGAL_FORM" NUMBER(2,0) NOT NULL,
  "REGISTRATION_NUMBER_RJSC" VARCHAR2(15 BYTE),
  "REGISTRATION_DATE_RJSC" DATE,
  "TIN" VARCHAR2(12 BYTE),
  "BUSINESS_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "BUSINESS_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "BUSINESS_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "BUSINESS_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "FACTORY_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "FACTORY_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "FACTORY_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "FACTORY_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "CRG_SCORING" NUMBER(3,0),
  "CREDIT_RATING" NUMBER(3,0),
  "PHONE_NUMBER" VARCHAR2(40 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "CIF_NO" VARCHAR2(9 BYTE)
);
ALTER TABLE "INSTITUTIONS_HIST" ADD CONSTRAINT "INSTITUTIONS_HIST_PK" PRIMARY KEY ("VERSION_NO", "FI_SUBJECT_CODE");

CREATE TABLE "NON_INSTALMENT_CONTRACTS_HIST" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "ENTRY_DATE" DATE,
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "CONTRACT_TYPE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_PHASE" VARCHAR2(2 BYTE) NOT NULL,
  "CONTRACT_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "CURRENCY_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "STARTING_DATE" DATE,
  "REQUEST_DATE" DATE,
  "PLANNED_END_DATE" DATE,
  "ACTUAL_END_DATE" DATE,
  "DEFAULTER_STATUS" VARCHAR2(1 BYTE) NOT NULL,
  "DATE_OF_LAST_PAYMENT" DATE,
  "SUBSIDIZED_CREDIT" VARCHAR2(1 BYTE),
  "PRE_FINANCE_LOAN" VARCHAR2(1 BYTE),
  "REORGANIZED_CREDIT" VARCHAR2(1 BYTE),
  "THIRD_PARTY_GUARANTEE_TYPE" VARCHAR2(3 BYTE),
  "SECURITY_TYPE" VARCHAR2(3 BYTE),
  "AMOUNT_GUARANTEED_THIRD_PARTY" NUMBER(12,0),
  "AMOUNT_GUARANTEED_SECURITY" NUMBER(12,0),
  "QUALITATIVE_JUDGEMENT" VARCHAR2(1 BYTE),
  "SANCTION_LIMIT" NUMBER(12,0) NOT NULL,
  "TOTAL_OUTSTANDING_AMOUNT" NUMBER(12,0) NOT NULL,
  "NO_OF_DAYS_PAYMENT_DELAY" NUMBER(3,0),
  "DUE_FOR_RECOVERY" NUMBER(12,0),
  "RECOVERY_DURING_REPORTING" NUMBER(12,0),
  "CUMULATIVE_RECOVERY" NUMBER(12,0),
  "DATE_OF_LAW_SUIT" DATE,
  "DATE_OF_CLASSIFICATION" DATE,
  "NO_OF_TIMES_RESCHEDULING" VARCHAR2(6 BYTE),
  "DATE_LAST_RESCHEDULING" DATE,
  "ECONOMIC_PURPOSE_CODE" VARCHAR2(4 BYTE),
  "SME" VARCHAR2(1 BYTE),
  "ENTERPRISE_TYPE" VARCHAR2(2 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "UBS_ACCOUNT_NO" VARCHAR2(16 BYTE)
);
ALTER TABLE "NON_INSTALMENT_CONTRACTS_HIST" ADD CONSTRAINT "NON_INSTALMENT_CONTRACT_HI_PK" PRIMARY KEY ("VERSION_NO", "FI_CONTRACT_CODE");

CREATE TABLE "PERSONAL_DATA_HIST" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "ENTRY_DATE" DATE,
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "TITLE" VARCHAR2(20 BYTE),
  "NAME" VARCHAR2(70 BYTE) NOT NULL,
  "FATHERS_TITLE" VARCHAR2(20 BYTE),
  "FATHERS_NAME" VARCHAR2(70 BYTE),
  "MOTHERS_TITLE" VARCHAR2(20 BYTE),
  "MOTHERS_NAME" VARCHAR2(70 BYTE),
  "SPOUSES_TITLE" VARCHAR2(20 BYTE),
  "SPOUSES_NAME" VARCHAR2(70 BYTE),
  "SECTOR_TYPE" NUMBER(1,0),
  "SECTOR_CODE" NUMBER(6,0),
  "GENDER" VARCHAR2(1 BYTE),
  "DATE_OF_BIRTH" DATE NOT NULL,
  "PLACE_OF_BIRTH" VARCHAR2(20 BYTE),
  "COUNTRY_OF_BIRTH" VARCHAR2(2 BYTE) NOT NULL,
  "NATIONAL_ID_NUMBER" VARCHAR2(17 BYTE),
  "NATIONAL_ID_AVAILABLE" NUMBER(1,0),
  "TIN" VARCHAR2(12 BYTE),
  "PERMANENT_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "PERMANENT_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "PERMANENT_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "PERMANENT_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "PRESENT_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "PRESENT_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "PRESENT_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "PRESENT_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "BUSINESS_ADDRESS_STREET" VARCHAR2(100 BYTE),
  "BUSINESS_ADDRESS_POSTAL_CODE" NUMBER(4,0),
  "BUSINESS_ADDRESS_DISTRICT" VARCHAR2(20 BYTE),
  "BUSINESS_ADDRESS_COUNTRY" VARCHAR2(2 BYTE),
  "ID_TYPE" VARCHAR2(1 BYTE),
  "ID_NUMBER" VARCHAR2(20 BYTE),
  "ID_ISSUE_DATE" DATE,
  "ID_ISSUE_COUNTRY" VARCHAR2(2 BYTE),
  "PHONE_NUMBER" VARCHAR2(40 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE),
  "CIF_NO" VARCHAR2(9 BYTE),
  "SMART_ID_NUMBER" VARCHAR2(10 BYTE)
);
ALTER TABLE "PERSONAL_DATA_HIST" ADD CONSTRAINT "PERSONAL_DATA_HIST_PK" PRIMARY KEY ("VERSION_NO", "FI_SUBJECT_CODE");

CREATE TABLE "INSTITUTION_OWNER_LINKS_HIST" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "ENTRY_DATE" DATE,
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "INSTITUTION_FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ROLE" VARCHAR2(2 BYTE) NOT NULL,
  "OWNER_FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE)
);
ALTER TABLE "INSTITUTION_OWNER_LINKS_HIST" ADD CONSTRAINT "INSTITUTION_OWNER_LINKS_HI_PK" PRIMARY KEY ("VERSION_NO", "INSTITUTION_FI_SUBJECT_CODE", "OWNER_FI_SUBJECT_CODE");

CREATE TABLE "CONTRACT_LINKS_HIST" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "ENTRY_DATE" DATE,
  "RECORD_TYPE" VARCHAR2(1 BYTE) NOT NULL,
  "FI_CODE" VARCHAR2(3 BYTE) NOT NULL,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "TYPE_OF_LINK" VARCHAR2(1 BYTE) NOT NULL,
  "FI_PRIMARY_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_SECONDARY_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE,
  "RECORD_STATUS" VARCHAR2(1 BYTE)
);
ALTER TABLE "CONTRACT_LINKS_HIST" ADD CONSTRAINT "CONTRACT_LINKS_HIST_PK" PRIMARY KEY ("VERSION_NO", "FI_CONTRACT_CODE", "FI_SECONDARY_CODE");

CREATE TABLE "PERSONAL_DATA_REPORT" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "PERSONAL_DATA_REPORT" ADD CONSTRAINT "PERSONAL_DATA_REPORT_PK" PRIMARY KEY ("VERSION_NO", "REPORTING_PERIOD", "FI_SUBJECT_CODE");

CREATE TABLE "PERSONAL_DATA_ERROR" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ERROR_CODE" VARCHAR2(20 BYTE),
  "ERROR_DESCRIPTION" VARCHAR2(150 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
CREATE INDEX "PERSONAL_DATA_ERROR_INDEX1" ON "PERSONAL_DATA_ERROR" ("VERSION_NO", "REPORTING_PERIOD", "FI_SUBJECT_CODE");

CREATE TABLE "INSTITUTION_REPORT" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "INSTITUTION_REPORT" ADD CONSTRAINT "INSTITUTION_REPORT_PK" PRIMARY KEY ("VERSION_NO", "REPORTING_PERIOD", "FI_SUBJECT_CODE");

CREATE TABLE "INSTITUTION_ERROR" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ERROR_CODE" VARCHAR2(20 BYTE),
  "ERROR_DESCRIPTION" VARCHAR2(150 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
CREATE INDEX "INSTITUTION_ERROR_INDEX1" ON "INSTITUTION_ERROR" ("VERSION_NO", "REPORTING_PERIOD", "FI_SUBJECT_CODE");

CREATE TABLE "OWNER_LINK_REPORT" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "INSTITUTION_FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "OWNER_FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "OWNER_LINK_REPORT" ADD CONSTRAINT "OWNER_LINKS_REPORT_PK" PRIMARY KEY ("VERSION_NO", "REPORTING_PERIOD", "INSTITUTION_FI_SUBJECT_CODE", "OWNER_FI_SUBJECT_CODE");

CREATE TABLE "OWNER_LINK_ERROR" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "INSTITUTION_FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "OWNER_FI_SUBJECT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ERROR_CODE" VARCHAR2(20 BYTE),
  "ERROR_DESCRIPTION" VARCHAR2(150 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
CREATE INDEX "OWNER_LINK_ERROR_INDEX1" ON "OWNER_LINK_ERROR" ("VERSION_NO", "REPORTING_PERIOD", "INSTITUTION_FI_SUBJECT_CODE", "OWNER_FI_SUBJECT_CODE");

CREATE TABLE "INSTALMENT_CONTRACT_REPORT" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "INSTALMENT_CONTRACT_REPORT" ADD CONSTRAINT "INSTALMENT_CONTRACT_REPORT_PK" PRIMARY KEY ("VERSION_NO", "REPORTING_PERIOD", "FI_CONTRACT_CODE");

CREATE TABLE "INSTALMENT_CONTRACT_ERROR" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ERROR_CODE" VARCHAR2(20 BYTE),
  "ERROR_DESCRIPTION" VARCHAR2(150 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
CREATE INDEX "INST_CONTRACT_ERROR_INDEX1" ON "INSTALMENT_CONTRACT_ERROR" ("VERSION_NO", "REPORTING_PERIOD", "FI_CONTRACT_CODE");

CREATE TABLE "NON_INSTALMENT_CONTRACT_REPORT" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "NON_INSTALMENT_CONTRACT_REPORT" ADD CONSTRAINT "NON_INSTALMENT_CONTRACT_RE_PK" PRIMARY KEY ("VERSION_NO", "REPORTING_PERIOD", "FI_CONTRACT_CODE");

CREATE TABLE "NON_INSTALMENT_CONTRACT_ERROR" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ERROR_CODE" VARCHAR2(20 BYTE),
  "ERROR_DESCRIPTION" VARCHAR2(150 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
CREATE INDEX "NON_INST_CONTRACT_ERROR_IDX1" ON "NON_INSTALMENT_CONTRACT_ERROR" ("VERSION_NO", "REPORTING_PERIOD", "FI_CONTRACT_CODE");

CREATE TABLE "CARD_CONTRACT_REPORT" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "CARD_CONTRACT_REPORT" ADD CONSTRAINT "CARD_CONTRACT_REPORT_PK" PRIMARY KEY ("VERSION_NO", "REPORTING_PERIOD", "FI_CONTRACT_CODE");

CREATE TABLE "CARD_CONTRACT_ERROR" (
  "VERSION_NO" NUMBER(10,0) NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ERROR_CODE" VARCHAR2(20 BYTE),
  "ERROR_DESCRIPTION" VARCHAR2(150 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
CREATE INDEX "CARD_CONTRACT_ERROR_INDEX1" ON "CARD_CONTRACT_ERROR" ("VERSION_NO", "REPORTING_PERIOD", "FI_CONTRACT_CODE");

CREATE TABLE "CONTRACT_LINK_REPORT" (
  "VERSION_NO" NUMBER NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_PRIMARY_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_SECONDARY_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
ALTER TABLE "CONTRACT_LINK_REPORT" ADD CONSTRAINT "CONTRACT_LINK_REPORT_PK" PRIMARY KEY ("VERSION_NO", "REPORTING_PERIOD", "FI_PRIMARY_CODE", "FI_SECONDARY_CODE", "FI_CONTRACT_CODE");

CREATE TABLE "CONTRACT_LINK_ERROR" (
  "VERSION_NO" NUMBER NOT NULL,
  "REPORTING_PERIOD" DATE NOT NULL,
  "FI_PRIMARY_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_SECONDARY_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "FI_CONTRACT_CODE" VARCHAR2(16 BYTE) NOT NULL,
  "ERROR_CODE" VARCHAR2(20 BYTE),
  "ERROR_DESCRIPTION" VARCHAR2(150 BYTE),
  "MAKE_BY" VARCHAR2(30 BYTE),
  "MAKE_DATE" DATE
);
CREATE INDEX "CONTRACT_LINK_ERROR_INDEX1" ON "CONTRACT_LINK_ERROR" ("VERSION_NO", "REPORTING_PERIOD", "FI_PRIMARY_CODE", "FI_SECONDARY_CODE", "FI_CONTRACT_CODE");

CREATE TABLE "LOV_DEED_TYPES" (
  "CODE" VARCHAR2(2 BYTE) NOT NULL,
  "NAME" VARCHAR2(30 BYTE) NOT NULL
);
ALTER TABLE "LOV_DEED_TYPES" ADD CONSTRAINT "LOV_DEED_TYPES_PK" PRIMARY KEY ("CODE");

CREATE TABLE "LOV_MOUZAS" (
  "DISTRICT" VARCHAR2(20 BYTE) NOT NULL,
  "MOUZA" VARCHAR2(40 BYTE) NOT NULL
);
ALTER TABLE "LOV_MOUZAS" ADD CONSTRAINT "LOV_MOUZAS_PK" PRIMARY KEY ("DISTRICT", "MOUZA");

CREATE TABLE "LOV_SUB_REGISTRY_OFFICES" (
  "DISTRICT" VARCHAR2(30 BYTE) NOT NULL,
  "SRO" VARCHAR2(30 BYTE) NOT NULL
);
ALTER TABLE "LOV_SUB_REGISTRY_OFFICES" ADD CONSTRAINT "LOV_SUB_REGISTRY_OFFICES_PK" PRIMARY KEY ("DISTRICT", "SRO");

CREATE TABLE "LOV_THANAS" (
  "DISTRICT" VARCHAR2(20 BYTE) NOT NULL,
  "THANA" VARCHAR2(20 BYTE) NOT NULL
);
ALTER TABLE "LOV_THANAS" ADD CONSTRAINT "LOV_THANAS_PK" PRIMARY KEY ("DISTRICT", "THANA");

CREATE TABLE "TMP_CODES" (
  "FI_CODE" VARCHAR2(16 BYTE),
  "UDF1" VARCHAR2(20 BYTE)
);

CREATE TABLE "LOAN_LIST" (
  "BRANCH_CODE" VARCHAR2(10 BYTE),
  "SL" NUMBER,
  "CUSTOMER_ID" VARCHAR2(35 BYTE),
  "MODULE" VARCHAR2(4 BYTE),
  "PRODUCT_CODE" VARCHAR2(6 BYTE),
  "PRODDES" VARCHAR2(315 BYTE),
  "CONT_REF_NO" VARCHAR2(35 BYTE),
  "VALUE_DATE" VARCHAR2(15 BYTE),
  "CCY" VARCHAR2(3 BYTE),
  "LIMIT_AMOUNT" NUMBER,
  "ACCOUNT_LIMIT" NUMBER,
  "OUTSTANDING" NUMBER,
  "FOUTSTANDING" NUMBER,
  "NFOUTSTANDING" NUMBER,
  "OUTSTANDING_LOCAL_CURRENCY" NUMBER,
  "OVERDUE" NUMBER,
  "MATURITY_DATE" VARCHAR2(15 BYTE),
  "STATUS1" VARCHAR2(4 BYTE),
  "LINKED_REFERENCE_NO" VARCHAR2(90 BYTE),
  "LIABILITY_NO" VARCHAR2(9 BYTE),
  "LINE_EXPIRY_DATE" VARCHAR2(15 BYTE),
  "MARGINAMOUNT" NUMBER,
  "INTEREST_RATE" NUMBER,
  "OVERDUE_INTEREST_RATE" NUMBER,
  "ENV_RISK" VARCHAR2(50 BYTE),
  "SECT_CODE" VARCHAR2(50 BYTE),
  "SME_CODE" VARCHAR2(50 BYTE),
  "GENERATION_DATE" DATE,
  "ALT_ACC_NO" VARCHAR2(40 BYTE),
  "TOTAL_AMOUNT_PAID" NUMBER,
  "LOAD_ID" NUMBER,
  "CONTRACT_REF_NO" VARCHAR2(200 BYTE),
  "INSTALLMENT_SIZE_FOR_CL" NUMBER,
  "VALIDITY_OF_WORK_ORDER" DATE,
  "TOTAL_VALUE_OF_WORK_ORDER" NUMBER,
  "WORK_AWARDING_AUTHORITY" VARCHAR2(200 BYTE),
  "WORK_ORDER_NUMBER" VARCHAR2(200 BYTE),
  "BILL_CODE" VARCHAR2(20 BYTE),
  "RESCHEDULING_STATUS" VARCHAR2(101 BYTE),
  "PURPOSE_OF_TERM_FINANCE" VARCHAR2(200 BYTE),
  "PREVIOUS_ACCOUNT_NO" VARCHAR2(20 BYTE),
  "NUMBER_OF_RESCHEDULED" VARCHAR2(100 BYTE),
  "FORCED_LOAN_AGAINST" VARCHAR2(200 BYTE),
  "FINANCE_TO" VARCHAR2(300 BYTE),
  "ELIGIBLE_SECURIY_VALUE" NUMBER,
  "NATURE_OF_SECURITY" VARCHAR2(100 BYTE),
  "SYNDICATION_LOAN" VARCHAR2(10 BYTE),
  "LAW_SUIT_DATE" DATE,
  "LAW_SUIT_NUMBER" VARCHAR2(100 BYTE),
  "SECURITY_CODE" NUMBER,
  "ECO_PURPOSE_CODE" NUMBER,
  "USER_DEFINE_EMI" NUMBER,
  "EMI_AMOUNT" NUMBER,
  "INSTALLMENT_FREQUENCE" VARCHAR2(10 BYTE),
  "INTEREST_SUSPENCE" NUMBER,
  "AMOUNT_PAID_LAST_MNTH" NUMBER,
  "CUSTOMER_NAME" VARCHAR2(100 CHAR),
  "NO_OF_INTALLMENT_DUE" NUMBER,
  "NO_OF_INTALLMENT_PAID" NUMBER,
  "INTEREST_OUTSTANDING" NUMBER,
  "LAST_RESCHEDULE_DATE" DATE,
  "FIRST_REPAY_DUE_DATE" DATE,
  "SATTLEMENT_LOAN_AC" VARCHAR2(100 BYTE),
  "SATTLEMENT_AC_BAL" NUMBER,
  "LATEST_APPROVAL_DATE" VARCHAR2(100 BYTE),
  "OVERDUE_DAYS" NUMBER,
  "SCHEDULE_NEXT_DATE" DATE,
  "LATEST_EVENT_DATE" DATE,
  "LAST_PAYMENT_DATE" DATE,
  "SECURITY_VALUE" NUMBER,
  "LAST_CLASSIFICATION_DATE" DATE,
  "FACILITY_TYPE_SPECIAL" VARCHAR2(100 BYTE),
  "GROUP_NAME" VARCHAR2(105 BYTE),
  "SPECIAL_FINANCING" VARCHAR2(50 BYTE),
  "UPOSHAKHA_CODE" VARCHAR2(3 BYTE),
  "BB_LOAN_ID" VARCHAR2(20 BYTE),
  "NON_AD_BRANCH" VARCHAR2(3 BYTE),
  "LATEST_RENEWAL_DATE" DATE,
  "AVG_INSTALLMENT_AMT" NUMBER,
  "AMT_PAID_SINCE_LAST_RENEWAL" NUMBER,
  "EQUIV_ARREAR" NUMBER,
  "NO_OF_INSTALLMENT" NUMBER,
  "NO_OF_OVERDUE_UPTO_EXPIRY" NUMBER,
  "NO_OF_INTALLMENT_DUE_CL" NUMBER,
  "NO_OF_INTALLMENT_PAID_CL" NUMBER
);

CREATE TABLE "LOV_PRODUCT_TYPES" (
  "PRODUCTCODE" VARCHAR2(10 BYTE),
  "CONTRACTCODE" VARCHAR2(2 BYTE),
  "DESCRIPTION" VARCHAR2(200 BYTE)
);
ALTER TABLE "LOV_PRODUCT_TYPES" ADD CONSTRAINT "FK_CON_TYPE" FOREIGN KEY ("CONTRACTCODE")
  REFERENCES "LOV_CONTRACT_TYPES" ("CODE");

CREATE GLOBAL TEMPORARY TABLE "TMP_AC_CODES" (
  "FI_CODE" VARCHAR2(16 BYTE)
) ON COMMIT PRESERVE ROWS;

CREATE TABLE "CL_DATA" (
  "REFERENCE_DATE" DATE,
  "BRANCH_CODE" VARCHAR2(4 BYTE),
  "BRANCH_NAME" VARCHAR2(50 BYTE),
  "CL_FILE" VARCHAR2(50 BYTE),
  "ACCOUNT_NO" VARCHAR2(16 BYTE),
  "BN02" VARCHAR2(100 BYTE),
  "CATEGORY" VARCHAR2(60 BYTE),
  "NATURE" VARCHAR2(50 BYTE),
  "OPENING_DATE" DATE,
  "EXPIRY_DATE" DATE,
  "OVERDUE_MONTH" NUMBER(12,0),
  "PERIOD_SINCE" NUMBER(*,0),
  "EQUIVALENT_AREAR" NUMBER(12,0),
  "STATUS" VARCHAR2(5 BYTE),
  "QUALITATIVE_JUDGEMENT" VARCHAR2(5 BYTE),
  "OBJECTIVE_CRITERIA" VARCHAR2(5 BYTE),
  "NO_OF_TIMES_RESCHEDULING" NUMBER(*,0),
  "SANCTION_NUMBER" NUMBER(*,0),
  "SANCTION_AMOUNT" NUMBER(18,2),
  "AMOUNT_DUE" NUMBER(18,2),
  "INTEREST_SUSPENSE" NUMBER(18,2),
  "ELIGIBLE_SECURITY" NUMBER(18,2),
  "BASIS" VARCHAR2(3 BYTE),
  "CUMULATIVE_INTEREST_SMA" NUMBER(18,2),
  "CUMULATIVE_INTEREST_CLASSIFIED" NUMBER(18,2),
  "BASE_FOR_PROVISION" NUMBER(18,2),
  "AMOUNT_PROVISION" NUMBER(18,2),
  "INSTALLMENT_SIZE" NUMBER(18,2),
  "AMOUNT_PAID_SINCE_SANCTIONED" NUMBER(18,2),
  "INSTALLMENT_FREQUENCY" NUMBER(*,0),
  "FIRST_REPAYMENT_DUE_DATE" DATE,
  "CREDIT_TYPE" VARCHAR2(1 BYTE),
  "INTEREST_RATE" NUMBER(4,2),
  "SBS_ECONOMIC_SECTOR_CODE" VARCHAR2(15 BYTE),
  "SBS_ECONOMIC_SECTOR_NAME" VARCHAR2(100 BYTE),
  "SBS_SECURITY_CODE" VARCHAR2(15 BYTE),
  "SBS_SECURITY_DESCRIPTION" VARCHAR2(100 BYTE),
  "SBS_ECONOMIC_PURPOSE_CODE" VARCHAR2(15 BYTE),
  "SBS_ECONOMIC_PURPOSE_DESCRIPTION" VARCHAR2(100 BYTE),
  "SBS_SME_CODE" VARCHAR2(15 BYTE),
  "SBS_SME_DESCRIPTION" VARCHAR2(100 BYTE),
  "SBS_PRODUCT_CODE" VARCHAR2(15 BYTE),
  "SBS_PRODUCT_DESCRIPTION" VARCHAR2(100 BYTE),
  "SBS_BILL_CODE" VARCHAR2(15 BYTE),
  "DEFAULTED_OUTSTANDING" NUMBER(18,2)
);

CREATE TABLE "BB_LIVE_SUBJECTS" (
  "REPORTING_PERIOD" DATE,
  "FI_SUBJECT_CODE" VARCHAR2(16 BYTE)
);
ALTER TABLE "BB_LIVE_SUBJECTS" ADD CONSTRAINT "PK_BB_LIVE_SUBJECTS" PRIMARY KEY ("REPORTING_PERIOD", "FI_SUBJECT_CODE");

CREATE OR REPLACE VIEW "VW_SUBJECTS" ("FI_SUBJECT_CODE", "SUBJECT_NAME", "SUBJECT_TYPE", "RECORD_STATUS", "CIF_NO") AS
  SELECT
  FI_SUBJECT_CODE,
  NAME SUBJECT_NAME,
  SUBSTR(FI_SUBJECT_CODE,1,1) SUBJECT_TYPE,
  RECORD_STATUS,
  CIF_NO
FROM
  PERSONAL_DATA
UNION
SELECT
  FI_SUBJECT_CODE,
  TRADE_NAME,
  SUBSTR(FI_SUBJECT_CODE,1,1),
  RECORD_STATUS,
  CIF_NO
FROM
  INSTITUTIONS
 ;

CREATE OR REPLACE VIEW "VW_CONTRACTS" ("CONTRACT_CATEGORY", "FI_CONTRACT_CODE", "FI_SUBJECT_CODE", "CONTRACT_PHASE", "DEFAULTER_STATUS", "RECORD_STATUS", "UBS_ACCOUNT_NO", "BRANCH_CODE", "CONTRACT_STATUS") AS
  SELECT 'Instalment' contract_category, fi_contract_code, FI_SUBJECT_CODE,CONTRACT_phase,DEFAULTER_STATUS, record_status, UBS_ACCOUNT_NO, BRANCH_CODE, CONTRACT_STATUS from instalment_contracts
union
select 'NonInstalment', fi_contract_code, FI_SUBJECT_CODE,CONTRACT_phase,DEFAULTER_STATUS, record_status, UBS_ACCOUNT_NO, BRANCH_CODE, CONTRACT_STATUS from non_instalment_contracts
union
select 'Card',fi_contract_code, FI_SUBJECT_CODE,CONTRACT_phase,DEFAULTER_STATUS, record_status, NULL, BRANCH_CODE, CONTRACT_STATUS from card_contracts
 ;

CREATE OR REPLACE VIEW "VW_SUBJECT_REPORT" ("VERSION_NO", "REPORTING_PERIOD", "FI_SUBJECT_CODE", "MAKE_BY", "MAKE_DATE") AS
  SELECT "VERSION_NO","REPORTING_PERIOD","FI_SUBJECT_CODE","MAKE_BY","MAKE_DATE" FROM PERSONAL_DATA_REPORT
UNION
SELECT "VERSION_NO","REPORTING_PERIOD","FI_SUBJECT_CODE","MAKE_BY","MAKE_DATE" FROM INSTITUTION_REPORT
 ;

CREATE OR REPLACE VIEW "VW_CONTRACT_REPORT" ("VERSION_NO", "REPORTING_PERIOD", "FI_CONTRACT_CODE", "MAKE_BY", "MAKE_DATE") AS
  SELECT "VERSION_NO","REPORTING_PERIOD","FI_CONTRACT_CODE","MAKE_BY","MAKE_DATE" FROM instalment_contract_report
union all
SELECT "VERSION_NO","REPORTING_PERIOD","FI_CONTRACT_CODE","MAKE_BY","MAKE_DATE" FROM non_instalment_contract_report
union all
SELECT "VERSION_NO","REPORTING_PERIOD","FI_CONTRACT_CODE","MAKE_BY","MAKE_DATE" FROM card_contract_report
 ;
