CREATE OR REPLACE VIEW VW_SUBJECT_REPORT 
(
    VERSION_NO,
    REPORTING_PERIOD,
    FI_SUBJECT_CODE,
    MAKE_BY,
    MAKE_DATE
) AS
SELECT
    VERSION_NO,
    REPORTING_PERIOD,
    FI_SUBJECT_CODE,
    MAKE_BY,
    MAKE_DATE
FROM
    PERSONAL_DATA_REPORT
UNION
SELECT
    VERSION_NO,
    REPORTING_PERIOD,
    FI_SUBJECT_CODE,
    MAKE_BY,
    MAKE_DATE
FROM
    INSTITUTION_REPORT;
