CREATE OR REPLACE VIEW VW_SECURITY_REPORT 
(
    VERSION_NO,
    REPORTING_PERIOD,
    FI_SECURITY_CODE,
    MAKE_BY,
    MAKE_DATE
) AS
SELECT
    VERSION_NO,
    REPORTING_PERIOD,
    FI_SECURITY_CODE,
    MAKE_BY,
    MAKE_DATE
FROM
    LAND_BUILDING_REPORT
UNION ALL
SELECT
    VERSION_NO,
    REPORTING_PERIOD,
    FI_SECURITY_CODE,
    MAKE_BY,
    MAKE_DATE
FROM
    FLAT_REPORT
UNION ALL
SELECT
    VERSION_NO,
    REPORTING_PERIOD,
    FI_SECURITY_CODE,
    MAKE_BY,
    MAKE_DATE
FROM
    MACHINERY_REPORT;
