CREATE OR REPLACE VIEW VW_SUBJECTS 
(
    FI_SUBJECT_CODE,
    SUBJECT_NAME,
    SUBJECT_TYPE,
    CIF_NO
) AS
SELECT
    FI_SUBJECT_CODE,
    NAME SUBJECT_NAME,
    SUBSTR(FI_SUBJECT_CODE, 1, 1) SUBJECT_TYPE,
    CIF_NO
FROM
    PERSONAL_DATA
UNION
SELECT
    FI_SUBJECT_CODE,
    TRADE_NAME,
    SUBSTR(FI_SUBJECT_CODE, 1, 1),
    CIF_NO
FROM
    INSTITUTIONS;
