CREATE OR REPLACE PACKAGE PKG_SECURITY AS 

    PROCEDURE SP_SECURITY_PAYLOAD_GET(
      IN_FI_SECURITY_CODE IN VARCHAR2,
      PERSON_CURSOR OUT SYS_REFCURSOR,
      INSTITUTION_CURSOR OUT SYS_REFCURSOR,
      LAND_BUILDING_CURSOR OUT SYS_REFCURSOR,
      FLAT_CURSOR OUT SYS_REFCURSOR,
      MACHINERY_CURSOR OUT SYS_REFCURSOR,
      MORTGAGE_CURSOR OUT SYS_REFCURSOR,
      HYPOTHECATION_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_LAND_BUILDING_GET(
      IN_BRANCH_CODE IN VARCHAR2,
      IN_FI_SECURITY_CODE IN VARCHAR2,
      IN_SUBJECT_NAME IN VARCHAR2,        
      IN_ROW_START IN INT,
      IN_ROW_END IN INT,
      REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_LAND_BUILDING_INSERT(
        IN_RECORD_TYPE IN VARCHAR2,
        IN_FI_CODE IN VARCHAR2,
        IN_BRANCH_CODE IN VARCHAR2,
        IN_SECURITY_VALUE_CODE IN VARCHAR2,
        IN_SECURITY_CATEGORY IN VARCHAR2,
        IN_FI_SECURITY_CODE IN VARCHAR2,
        IN_TYPE_DEED IN VARCHAR2,
        IN_TITLE_DEED_POA_NO IN VARCHAR2,
        IN_DATE_REGISTRATION IN NUMBER,
        IN_NAME_SUB_REGISTRY_OFFICE IN VARCHAR2,
        IN_DISTRICT IN VARCHAR2,
        IN_THANA IN VARCHAR2,
        IN_MOUZA IN VARCHAR2,
        IN_AREA_LAND IN NUMBER,
        IN_PLOT_NO IN VARCHAR2,
        IN_HOLDING_NO IN VARCHAR2,
        IN_ADDRESS IN VARCHAR2,
        IN_JOTE_NO IN VARCHAR2,
        IN_DAG_NO_CS IN VARCHAR2,
        IN_DAG_NO_SA IN VARCHAR2,
        IN_DAG_NO_RS IN VARCHAR2,
        IN_DAG_NO_BS IN VARCHAR2,
        IN_DAG_NO_CITY_JORIP IN VARCHAR2,
        IN_KHATIAN_NO_CS IN VARCHAR2,
        IN_KHATIAN_NO_SA IN VARCHAR2,
        IN_KHATIAN_NO_RS IN VARCHAR2,
        IN_KHATIAN_NO_BS IN VARCHAR2,
        IN_KHATIAN_NO_CITY_JORIP IN VARCHAR2,
        IN_MUTATION_KHATIAN_NO IN VARCHAR2,
        IN_LEASEHOLD_PROPERTY IN VARCHAR2,
        IN_BUILDING_EXISTS_IN_LAND IN VARCHAR2,
        IN_SIZE_AREA_BUILDING IN NUMBER,
        IN_NUMBER_FLOOR IN NUMBER,
        IN_MAKE_BY IN VARCHAR2,
        IN_MAKE_DATE IN DATE,
        IN_CHECK_BY IN VARCHAR2,
        IN_CHECK_DATE IN DATE,
        IN_RECORD_STATUS IN VARCHAR2,
        REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_FLAT_GET(
      IN_BRANCH_CODE IN VARCHAR2,
      IN_FI_SECURITY_CODE IN VARCHAR2,
      IN_SUBJECT_NAME IN VARCHAR2,        
      IN_ROW_START IN INT,
      IN_ROW_END IN INT,
      REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_FLAT_INSERT(
        IN_RECORD_TYPE IN VARCHAR2,
        IN_FI_CODE IN VARCHAR2,
        IN_BRANCH_CODE IN VARCHAR2,
        IN_SECURITY_VALUE_CODE IN VARCHAR2,
        IN_SECURITY_CATEGORY IN VARCHAR2,
        IN_FI_SECURITY_CODE IN VARCHAR2,
        IN_TYPE_DEED IN VARCHAR2,
        IN_TITLE_DEED_POA_NO IN VARCHAR2,
        IN_DATE_REGISTRATION IN NUMBER,
        IN_NAME_SUB_REGISTRY_OFFICE IN VARCHAR2,
        IN_DISTRICT IN VARCHAR2,
        IN_THANA IN VARCHAR2,
        IN_MOUZA IN VARCHAR2,
        IN_TRIPARTITE_AGREEMENT IN VARCHAR2,
        IN_AREA_FLAT IN NUMBER,
        IN_UNDEMARCATED_LAND_AREA IN NUMBER,
        IN_APARTMENT_FLAT_NO IN VARCHAR2,
        IN_FLOOR_NO IN NUMBER,
        IN_LOCATION_FLAT IN VARCHAR2,
        IN_CITY_CORPRATION_HOLDING_NO IN VARCHAR2,
        IN_NAME_BUILDING IN VARCHAR2,
        IN_NAME_PROJECT IN VARCHAR2,
        IN_NAME_DEVELOPER IN VARCHAR2,
        IN_REHAB_MEMBER_NO_DEVELOPER IN VARCHAR2,
        IN_ADDRESS IN VARCHAR2,
        IN_JOTE_NO IN VARCHAR2,
        IN_DAG_NO_CS IN VARCHAR2,
        IN_DAG_NO_SA IN VARCHAR2,
        IN_DAG_NO_RS IN VARCHAR2,
        IN_DAG_NO_BS IN VARCHAR2,
        IN_DAG_NO_CITY_JORIP IN VARCHAR2,
        IN_KHATIAN_NO_CS IN VARCHAR2,
        IN_KHATIAN_NO_SA IN VARCHAR2,
        IN_KHATIAN_NO_RS IN VARCHAR2,
        IN_KHATIAN_NO_BS IN VARCHAR2,
        IN_KHATIAN_NO_CITY_JORIP IN VARCHAR2,
        IN_MUTATION_KHATIAN_NO IN VARCHAR2,
        IN_LEASEHOLD_PROPERTY IN VARCHAR2,
        IN_MAKE_BY IN VARCHAR2,
        IN_MAKE_DATE IN DATE,
        IN_CHECK_BY IN VARCHAR2,
        IN_CHECK_DATE IN DATE,
        IN_RECORD_STATUS IN VARCHAR2,
        REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_MACHINERY_GET(
      IN_BRANCH_CODE IN VARCHAR2,
      IN_FI_SECURITY_CODE IN VARCHAR2,
      IN_SUBJECT_NAME IN VARCHAR2,        
      IN_ROW_START IN INT,
      IN_ROW_END IN INT,
      REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_MACHINERY_INSERT(
        IN_RECORD_TYPE IN VARCHAR2,
        IN_FI_CODE IN VARCHAR2,
        IN_BRANCH_CODE IN VARCHAR2,
        IN_SECURITY_VALUE_CODE IN VARCHAR2,
        IN_SECURITY_CATEGORY IN VARCHAR2,
        IN_FI_SECURITY_CODE IN VARCHAR2,
        IN_NAME_MACHINERY IN VARCHAR2,
        IN_NAME_FACTORY IN VARCHAR2,
        IN_ADDRESS_FACTORY IN VARCHAR2,
        IN_MFG_CO_BRAND_NAME IN VARCHAR2,
        IN_MFG_COUNTRY IN VARCHAR2,
        IN_MFG_YEAR IN NUMBER,
        IN_MODEL_NO IN VARCHAR2,
        IN_NO_UNIT IN NUMBER,
        IN_LC_NO IN VARCHAR2,
        IN_LC_DATE IN NUMBER,
        IN_VALUE_LC IN NUMBER,
        IN_LADING_AIR_WAY_BILL_NO IN VARCHAR2,
        IN_PRESENT_VALUE IN NUMBER,
        IN_BOOK_INVOICE_VALUE IN NUMBER,
        IN_MAKE_BY IN VARCHAR2,
        IN_MAKE_DATE IN DATE,
        IN_CHECK_BY IN VARCHAR2,
        IN_CHECK_DATE IN DATE,
        IN_RECORD_STATUS IN VARCHAR2,
        REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_MORTGAGE_INSERT(
        IN_RECORD_TYPE IN VARCHAR2,
        IN_FI_CODE IN VARCHAR2,
        IN_BRANCH_CODE IN VARCHAR2,
        IN_FI_MORTGAGE_CODE IN VARCHAR2,
        IN_MORTGAGE_TYPE IN VARCHAR2,
        IN_MORTGAGE_DEED_NO IN VARCHAR2,
        IN_MORTGAGE_DATE IN NUMBER,
        IN_MORTGAGE_VALUE IN NUMBER,
        IN_MARKET_VALUE IN NUMBER,
        IN_RJSC_FILLING_NO IN VARCHAR2,
        IN_RJSC_FILLING_DATE IN NUMBER,
        IN_RANKING_CHARGE IN VARCHAR2,
        IN_PARI_PASSU_CHARGE IN VARCHAR2,
        IN_RIGPA_NO IN VARCHAR2,
        IN_RIGPA_DATE IN NUMBER,
        IN_MORTGAGE_PHASE IN VARCHAR2,
        IN_SECURITY_CATEGORY IN VARCHAR2,
        IN_MORTGAGED_LAND_AREA IN NUMBER,
        IN_MAKE_BY IN VARCHAR2,
        IN_MAKE_DATE IN DATE,
        IN_CHECK_BY IN VARCHAR2,
        IN_CHECK_DATE IN DATE,
        IN_RECORD_STATUS IN VARCHAR2,
        REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_MORTGAGE_GET_FILTERED(
        IN_BRANCH_CODE IN VARCHAR2,
        IN_FI_MORTGAGE_CODE IN VARCHAR2,
        IN_MORTGAGE_DEED_NO IN VARCHAR2,
        IN_MORTGAGE_DATE IN NUMBER,
        IN_MORTGAGE_VALUE IN NUMBER,
        REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_HYPOTHECATION_INSERT(
        IN_RECORD_TYPE IN VARCHAR2,
        IN_FI_CODE IN VARCHAR2,
        IN_BRANCH_CODE IN VARCHAR2,
        IN_FI_HYPOTHECATION_CODE IN VARCHAR2,
        IN_DATE_HYPOTHECATION IN NUMBER,
        IN_RJSC_FILLING_NO IN VARCHAR2,
        IN_RJSC_FILLING_DATE IN NUMBER,
        IN_RANKING_CHARGE IN VARCHAR2,
        IN_PARI_PASSU_CHARGE IN VARCHAR2,
        IN_HYPOTHECATION_PHASE IN VARCHAR2,
        IN_MAKE_BY IN VARCHAR2,
        IN_MAKE_DATE IN DATE,
        IN_CHECK_BY IN VARCHAR2,
        IN_CHECK_DATE IN DATE,
        IN_RECORD_STATUS IN VARCHAR2,
        REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_HYPOTHECATION_GET_FILTERED(
        IN_BRANCH_CODE IN VARCHAR2,
        IN_FI_HYPOTHECATION_CODE IN VARCHAR2,
        IN_DATE_HYPOTHECATION IN NUMBER,
        IN_RJSC_FILLING_NO IN VARCHAR2,
        IN_RJSC_FILLING_DATE IN NUMBER,
        REF_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_SECURITY_LINK_INSERT(
        IN_RECORD_TYPE VARCHAR2,
        IN_FI_CODE VARCHAR2,
        IN_BRANCH_CODE VARCHAR2,
        IN_LINK_TYPE VARCHAR2,
        IN_FI_SECURITY_CODE VARCHAR2,
        IN_FI_MORT_HYPO_CODE VARCHAR2,
        IN_MAKE_BY VARCHAR2,
        IN_MAKE_DATE DATE,
        IN_CHECK_BY VARCHAR2,
        IN_CHECK_DATE DATE,
        IN_RECORD_STATUS VARCHAR2
    );

    PROCEDURE SP_SUBJECT_LINK_INSERT(
        IN_RECORD_TYPE VARCHAR2,
        IN_FI_CODE VARCHAR2,
        IN_BRANCH_CODE VARCHAR2,
        IN_LINK_TYPE VARCHAR2,
        IN_FI_SUBJECT_CODE VARCHAR2,
        IN_FI_SEC_MORT_HYPO_CODE VARCHAR2,
        IN_ROLE VARCHAR2,
        IN_MAKE_BY VARCHAR2,
        IN_MAKE_DATE DATE,
        IN_CHECK_BY VARCHAR2,
        IN_CHECK_DATE DATE,
        IN_RECORD_STATUS VARCHAR2
    );

END PKG_SECURITY;
 
