CREATE OR REPLACE PACKAGE BODY PKG_ADMIN AS

--  User Info

  PROCEDURE SP_GET_USERS_BY_FILTERS(
      EMP_ID_IN     IN NUMBER,
      EMP_NAME_IN IN VARCHAR2,
      BRANCH_CODE_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT EMPID,
    ADID,
    FULLNAME,
    BRANCH_CODE,
    STATUS FROM APP_USERS WHERE (STATUS = 'A' OR STATUS = 'U') 
    AND BRANCH_CODE like NVL('%'||BRANCH_CODE_IN||'%', BRANCH_CODE)
    AND EMPID like NVL('%'||EMP_ID_IN||'%', EMPID)
    AND FULLNAME like NVL('%'||EMP_NAME_IN||'%', FULLNAME);
  END SP_GET_USERS_BY_FILTERS;
  
  
  PROCEDURE SP_USERINFO_INSERT(
      
      EMP_ID_IN            NUMBER,
      AD_ID_IN             VARCHAR2,
      FULLNAME_IN          VARCHAR2,
      BRANCH_CODE_IN       VARCHAR2,
      STATUS_IN            VARCHAR2,
      AD_IN                VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE)
      AS
      TMP_EXIST_ID NUMBER;
  BEGIN
  select COUNT(EMPID) into TMP_EXIST_ID FROM APP_USERS WHERE EMPID IN(EMP_ID_IN); 
  IF TMP_EXIST_ID <> 0
  THEN
    UPDATE APP_USERS
      SET
        ADID = AD_ID_IN ,
        FULLNAME = FULLNAME_IN ,
        BRANCH_CODE = BRANCH_CODE_IN ,
--        STATUS = 'U',
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        EMPID = EMP_ID_IN;
  ELSE 
    INSERT INTO APP_USERS
        VALUES
        ( EMP_ID_IN,
          AD_ID_IN,
          FULLNAME_IN,
          BRANCH_CODE_IN,
          STATUS_IN,
          AD_IN,
          MAKE_BY_IN,
          MAKE_DATE_IN);
  END IF;
    
  END SP_USERINFO_INSERT;
  
  
  PROCEDURE SP_USERINFO_DELETE(
      EMP_ID_IN            NUMBER,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE) AS
  BEGIN
    UPDATE APP_USERS
      SET
        STATUS = STATUS_IN ,
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        EMPID = EMP_ID_IN;
  END SP_USERINFO_DELETE;
  
--  Role Info
  
  PROCEDURE SP_GET_ROLES_BY_FILTERS(
      ROLE_CODE_IN IN VARCHAR2,
      DESCRIPTION_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT ROLE_CODE, DESCRIPTION
    FROM APP_ROLES WHERE (STATUS = 'A' OR STATUS = 'U') 
    AND ROLE_CODE like NVL('%'||ROLE_CODE_IN||'%', ROLE_CODE)
    AND DESCRIPTION like NVL('%'||DESCRIPTION_IN||'%', DESCRIPTION);
  END SP_GET_ROLES_BY_FILTERS;
  
  PROCEDURE SP_ROLE_INSERT(

      ROLE_CODE_IN         VARCHAR2,
      DESCRIPTION_IN       VARCHAR2,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE)
      AS
      TMP_EXIST_ID NUMBER;
  BEGIN
  select COUNT(ROLE_CODE) into TMP_EXIST_ID FROM APP_ROLES WHERE ROLE_CODE IN(ROLE_CODE_IN); 
  IF TMP_EXIST_ID <> 0
  THEN
    UPDATE APP_ROLES
      SET
        ROLE_CODE = ROLE_CODE_IN ,
        DESCRIPTION = DESCRIPTION_IN ,
        STATUS = 'U',
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        ROLE_CODE = ROLE_CODE_IN;
  ELSE 
    INSERT INTO APP_ROLES
        VALUES
        ( ROLE_CODE_IN,
          DESCRIPTION_IN,
          STATUS_IN,
          MAKE_BY_IN,
          MAKE_DATE_IN);
  END IF;
    
  END SP_ROLE_INSERT;
  
  PROCEDURE SP_ROLE_DELETE(
      ROLE_CODE_IN         VARCHAR2,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE) AS
  BEGIN
    UPDATE APP_ROLES
      SET
        STATUS = STATUS_IN ,
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        ROLE_CODE = ROLE_CODE_IN;
  END SP_ROLE_DELETE;
  
  
--  Group Info
  
  PROCEDURE SP_GET_GROUP_BY_FILTERS(
      GROUP_CODE_IN IN VARCHAR2,
      DESCRIPTION_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN REF_CURSOR FOR 
    SELECT GROUP_CODE, DESCRIPTION
    FROM APP_ROLE_GROUPS WHERE (STATUS = 'A' OR STATUS = 'U') 
    AND GROUP_CODE like NVL('%'||GROUP_CODE_IN||'%', GROUP_CODE)
    AND DESCRIPTION like NVL('%'||DESCRIPTION_IN||'%', DESCRIPTION);
  END SP_GET_GROUP_BY_FILTERS;
  
  PROCEDURE SP_GROUP_INSERT(

      GROUP_CODE_IN         VARCHAR2,
      DESCRIPTION_IN       VARCHAR2,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE)
      AS
      TMP_EXIST_ID NUMBER;
  BEGIN
  select COUNT(GROUP_CODE) into TMP_EXIST_ID FROM APP_ROLE_GROUPS WHERE GROUP_CODE IN(GROUP_CODE_IN); 
  IF TMP_EXIST_ID <> 0
  THEN
    UPDATE APP_ROLE_GROUPS
      SET
        GROUP_CODE = GROUP_CODE_IN ,
        DESCRIPTION = DESCRIPTION_IN ,
        STATUS = 'U',
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        GROUP_CODE = GROUP_CODE_IN;
  ELSE 
    INSERT INTO APP_ROLE_GROUPS
        VALUES
        ( GROUP_CODE_IN,
          DESCRIPTION_IN,
          STATUS_IN,
          MAKE_BY_IN,
          MAKE_DATE_IN);
  END IF;
    
  END SP_GROUP_INSERT;
  
  PROCEDURE SP_GROUP_DELETE(
      GROUP_CODE_IN         VARCHAR2,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE) AS
  BEGIN
    UPDATE APP_ROLE_GROUPS
      SET
        STATUS = STATUS_IN ,
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        GROUP_CODE = GROUP_CODE_IN;
  END SP_GROUP_DELETE;
   
  
--  User Role Info
  
  PROCEDURE SP_GET_USERROLE_BY_FILTERS(
      EMP_ID_IN      IN NUMBER,
      ROLE_CODE_IN   IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN REF_CURSOR FOR 
    SELECT EMPID, ROLE_CODE
    FROM APP_USER_ROLES WHERE 
    EMPID like NVL('%'||EMP_ID_IN||'%', EMPID)
    AND ROLE_CODE like NVL('%'||ROLE_CODE_IN||'%', ROLE_CODE);
  END SP_GET_USERROLE_BY_FILTERS;
  
  PROCEDURE SP_EMPID(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT EMPID FROM APP_USERS
    WHERE (STATUS = 'A' OR STATUS = 'U');
  END SP_EMPID;
  
  PROCEDURE SP_ROLECODE(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT ROLE_CODE FROM APP_ROLES
    WHERE (STATUS = 'A' OR STATUS = 'U');
  END SP_ROLECODE;
  
  PROCEDURE SP_USERROLE_INSERT(
      EMP_ID_IN            NUMBER,
      ROLE_CODE_IN         VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE)
      AS
      TMP_EXIST_ID NUMBER;
  BEGIN
  select COUNT(*) into TMP_EXIST_ID FROM APP_USER_ROLES WHERE EMPID IN (EMP_ID_IN)
  AND ROLE_CODE IN (ROLE_CODE_IN); 
  IF TMP_EXIST_ID <> 0
  THEN
    UPDATE APP_USER_ROLES
      SET
        EMPID = EMP_ID_IN,
        ROLE_CODE = ROLE_CODE_IN ,
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        EMPID = EMP_ID_IN
        OR ROLE_CODE = ROLE_CODE_IN;
  ELSE 
    INSERT INTO APP_USER_ROLES
        VALUES
        ( EMP_ID_IN,
          ROLE_CODE_IN,
          MAKE_BY_IN,
          MAKE_DATE_IN);
  END IF;  
  END SP_USERROLE_INSERT;
  
  PROCEDURE SP_USERROLE_DELETE(
      EMP_ID_IN            NUMBER,
      ROLE_CODE_IN         VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE) AS
  BEGIN
    DELETE FROM APP_USER_ROLES
      WHERE
        EMPID = EMP_ID_IN
        AND ROLE_CODE = ROLE_CODE_IN;
  END SP_USERROLE_DELETE;
  
  
--  User Group Info
  
  PROCEDURE SP_GET_USERGROUP_BY_FILTERS(
      EMP_ID_IN       IN NUMBER,
      GROUP_CODE_IN   IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN REF_CURSOR FOR 
    SELECT EMPID, GROUP_CODE
    FROM APP_ROLE_GROUP_USERS WHERE 
    EMPID like NVL('%'||EMP_ID_IN||'%', EMPID)
    AND GROUP_CODE like NVL('%'||GROUP_CODE_IN||'%', GROUP_CODE);
  END SP_GET_USERGROUP_BY_FILTERS;
  
  PROCEDURE SP_EMPID_USERGROUP(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT EMPID FROM APP_USERS
    WHERE (STATUS = 'A' OR STATUS = 'U');
  END SP_EMPID_USERGROUP;
  
  PROCEDURE SP_GROUPCODE_USERGROUP(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT GROUP_CODE FROM APP_ROLE_GROUPS
    WHERE (STATUS = 'A' OR STATUS = 'U');
  END SP_GROUPCODE_USERGROUP;
  
  PROCEDURE SP_USERGROUP_INSERT(
      EMP_ID_IN            NUMBER,
      GROUP_CODE_IN        VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE)
      AS
      TMP_EXIST_ID NUMBER;
  BEGIN
  select COUNT(*) into TMP_EXIST_ID FROM APP_ROLE_GROUP_USERS WHERE EMPID IN(EMP_ID_IN) 
  AND GROUP_CODE IN(GROUP_CODE_IN); 
  IF TMP_EXIST_ID <> 0
  THEN
    UPDATE APP_ROLE_GROUP_USERS
      SET
        EMPID = EMP_ID_IN,
        GROUP_CODE = GROUP_CODE_IN ,
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        EMPID = EMP_ID_IN
        OR GROUP_CODE = GROUP_CODE_IN;
  ELSE 
    INSERT INTO APP_ROLE_GROUP_USERS
        VALUES
        ( GROUP_CODE_IN,
          EMP_ID_IN,
          MAKE_BY_IN,
          MAKE_DATE_IN);
  END IF;  
  END SP_USERGROUP_INSERT;
  
  PROCEDURE SP_USERGROUP_DELETE(
      EMP_ID_IN            NUMBER,
      GROUP_CODE_IN        VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE) AS
  BEGIN
    DELETE FROM APP_ROLE_GROUP_USERS
      WHERE
        EMPID = EMP_ID_IN
        AND GROUP_CODE = GROUP_CODE_IN;
  END SP_USERGROUP_DELETE;
  
  
--  Group Role Info
  
  PROCEDURE SP_GET_GROUPROLE_BY_FILTERS(
      GROUP_CODE_IN   IN VARCHAR2,
      ROLE_CODE_IN    IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN REF_CURSOR FOR 
    SELECT GROUP_CODE, ROLE_CODE
    FROM APP_ROLE_GROUP_ROLES WHERE 
    GROUP_CODE like NVL('%'||GROUP_CODE_IN||'%', GROUP_CODE)
    AND ROLE_CODE like NVL('%'||ROLE_CODE_IN||'%', ROLE_CODE);
  END SP_GET_GROUPROLE_BY_FILTERS;
  
  PROCEDURE SP_GROUPCODE_GROUPROLE(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT GROUP_CODE FROM APP_ROLE_GROUPS
    WHERE (STATUS = 'A' OR STATUS = 'U');
  END SP_GROUPCODE_GROUPROLE;
  
  PROCEDURE SP_ROLECODE_GROUPROLE(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT ROLE_CODE FROM APP_ROLES
    WHERE (STATUS = 'A' OR STATUS = 'U');
  END SP_ROLECODE_GROUPROLE;
  
  PROCEDURE SP_GROUPROLE_INSERT(
      GROUP_CODE_IN       VARCHAR2,
      ROLE_CODE_IN        VARCHAR2,
      MAKE_BY_IN          VARCHAR2,
      MAKE_DATE_IN        DATE)
      AS
      TMP_EXIST_ID NUMBER;
  BEGIN
  select COUNT(*) into TMP_EXIST_ID FROM APP_ROLE_GROUP_ROLES 
  WHERE GROUP_CODE IN(GROUP_CODE_IN) AND ROLE_CODE IN(ROLE_CODE_IN); 
  IF TMP_EXIST_ID <> 0
  THEN
    UPDATE APP_ROLE_GROUP_ROLES
      SET
        GROUP_CODE = GROUP_CODE_IN,
        ROLE_CODE = ROLE_CODE_IN ,
        MAKE_BY = MAKE_BY_IN ,
        MAKE_DATE = MAKE_DATE_IN
      WHERE
        GROUP_CODE = GROUP_CODE_IN
        OR ROLE_CODE = ROLE_CODE_IN;
  ELSE 
    INSERT INTO APP_ROLE_GROUP_ROLES
        VALUES
        ( GROUP_CODE_IN,
          ROLE_CODE_IN,
          MAKE_BY_IN,
          MAKE_DATE_IN);
  END IF;  
  END SP_GROUPROLE_INSERT;
  
  PROCEDURE SP_GROUPROLE_DELETE(
      GROUP_CODE_IN       VARCHAR2,
      ROLE_CODE_IN        VARCHAR2,
      MAKE_BY_IN          VARCHAR2,
      MAKE_DATE_IN        DATE) AS
  BEGIN
    DELETE FROM APP_ROLE_GROUP_ROLES     
      WHERE
        GROUP_CODE = GROUP_CODE_IN
        AND ROLE_CODE = ROLE_CODE_IN;
  END SP_GROUPROLE_DELETE;
  
END PKG_ADMIN;
