CREATE OR REPLACE PACKAGE PKG_ERROR
AS
  PROCEDURE SP_GET_PERSONAL_DATA_ERROR(
      P_BRANCH_CODE     IN VARCHAR2,
      P_FI_SUBJECT_CODE IN VARCHAR2,
      P_FI_SUBJECT_NAME IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_INSTITUTION_ERROR(
      P_BRANCH_CODE     IN VARCHAR2,
      P_FI_SUBJECT_CODE IN VARCHAR2,
      P_FI_SUBJECT_NAME IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_INST_CONTRACT_ERROR(
      P_BRANCH_CODE      IN VARCHAR2,
      P_FI_SUBJECT_CODE  IN VARCHAR2,
      P_FI_CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_NON_INST_CONTRACT_ERROR(
      P_BRANCH_CODE      IN VARCHAR2,
      P_FI_SUBJECT_CODE  IN VARCHAR2,
      P_FI_CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_CARD_CONTRACT_ERROR(
      P_BRANCH_CODE      IN VARCHAR2,
      P_FI_SUBJECT_CODE  IN VARCHAR2,
      P_FI_CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
END PKG_ERROR;
 
