CREATE OR REPLACE PACKAGE PKG_FILE AS 

  PROCEDURE SP_GET_SUBJECT_FILE_DATA(IN_REPORTING_PERIOD IN DATE, REF_CURSOR OUT SYS_REFCURSOR); 
  PROCEDURE SP_GET_CONTRACT_FILE_DATA(IN_REPORTING_PERIOD IN DATE, REF_CURSOR OUT SYS_REFCURSOR); 
  PROCEDURE SP_GET_SECURITY_FILE_DATA(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_SEC_SUBJECT_FILE_DATA(REF_CURSOR OUT SYS_REFCURSOR); 

END PKG_FILE;

