CREATE OR REPLACE PACKAGE PKG_ADMIN AS 

  PROCEDURE SP_GET_USERS_BY_FILTERS(
      EMP_ID_IN     IN NUMBER,
      EMP_NAME_IN IN VARCHAR2,
      BRANCH_CODE_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR); 
      
  PROCEDURE SP_USERINFO_INSERT(
      EMP_ID_IN            NUMBER,
      AD_ID_IN             VARCHAR2,
      FULLNAME_IN          VARCHAR2,
      BRANCH_CODE_IN       VARCHAR2,
      STATUS_IN            VARCHAR2,
      AD_IN                VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
      
  PROCEDURE SP_USERINFO_DELETE(
      EMP_ID_IN            NUMBER,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);

  PROCEDURE SP_GET_ROLES_BY_FILTERS(
      ROLE_CODE_IN IN VARCHAR2,
      DESCRIPTION_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
      
  PROCEDURE SP_ROLE_INSERT(

      ROLE_CODE_IN         VARCHAR2,
      DESCRIPTION_IN       VARCHAR2,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
      
  PROCEDURE SP_ROLE_DELETE(
      ROLE_CODE_IN         VARCHAR2,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
  
  
  PROCEDURE SP_GET_GROUP_BY_FILTERS(
      GROUP_CODE_IN IN VARCHAR2,
      DESCRIPTION_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
      
  PROCEDURE SP_GROUP_INSERT(
      GROUP_CODE_IN        VARCHAR2,
      DESCRIPTION_IN       VARCHAR2,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
      
  PROCEDURE SP_GROUP_DELETE(
      GROUP_CODE_IN        VARCHAR2,
      STATUS_IN            VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
  
  
  PROCEDURE SP_GET_USERROLE_BY_FILTERS(
      EMP_ID_IN       IN NUMBER,
      ROLE_CODE_IN    IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
      
  PROCEDURE SP_EMPID(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_ROLECODE(REF_CURSOR OUT SYS_REFCURSOR);
  
  PROCEDURE SP_USERROLE_INSERT(
      EMP_ID_IN            NUMBER,
      ROLE_CODE_IN         VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
      
  PROCEDURE SP_USERROLE_DELETE(
      EMP_ID_IN            NUMBER,
      ROLE_CODE_IN         VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
      
      
  PROCEDURE SP_GET_USERGROUP_BY_FILTERS(
      EMP_ID_IN        IN NUMBER,
      GROUP_CODE_IN    IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
      
  PROCEDURE SP_EMPID_USERGROUP(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GROUPCODE_USERGROUP(REF_CURSOR OUT SYS_REFCURSOR);
  
  PROCEDURE SP_USERGROUP_INSERT(
      EMP_ID_IN            NUMBER,
      GROUP_CODE_IN        VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
      
  PROCEDURE SP_USERGROUP_DELETE(
      EMP_ID_IN            NUMBER,
      GROUP_CODE_IN        VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
      
      
  PROCEDURE SP_GET_GROUPROLE_BY_FILTERS(
      GROUP_CODE_IN    IN VARCHAR2,
      ROLE_CODE_IN     IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR);
      
  PROCEDURE SP_GROUPCODE_GROUPROLE(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_ROLECODE_GROUPROLE(REF_CURSOR OUT SYS_REFCURSOR);
  
  PROCEDURE SP_GROUPROLE_INSERT(
      GROUP_CODE_IN        VARCHAR2,
      ROLE_CODE_IN         VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE);
      
  PROCEDURE SP_GROUPROLE_DELETE(
      GROUP_CODE_IN       VARCHAR2,
      ROLE_CODE_IN        VARCHAR2,
      MAKE_BY_IN          VARCHAR2,
      MAKE_DATE_IN        DATE);
      
      
END PKG_ADMIN;
 
