CREATE OR REPLACE PACKAGE BODY PKG_ERROR AS

  PROCEDURE SP_GET_PERSONAL_DATA_ERROR
  (
    P_BRANCH_CODE IN VARCHAR2, 
    P_FI_SUBJECT_CODE IN VARCHAR2, 
    P_FI_SUBJECT_NAME IN VARCHAR2, 
    REF_CURSOR OUT SYS_REFCURSOR
  )    
  AS
    L_VERSION_NO NUMBER;
    L_REPORTING_PERIOD DATE;
  BEGIN
    SELECT TO_DATE(VALUE, 'DD-MON-YYYY') INTO L_REPORTING_PERIOD FROM REPORTING_PARAMETERS WHERE KEY = 'REPORTING_PERIOD';
    
    SELECT MAX(VERSION_NO) INTO L_VERSION_NO FROM PERSONAL_DATA_REPORT WHERE REPORTING_PERIOD = L_REPORTING_PERIOD;
        
    OPEN REF_CURSOR FOR
    SELECT A.VERSION_NO ,
           REPORTING_PERIOD ,
           A.FI_SUBJECT_CODE ,
           B.NAME SUBJECT_NAME,
           ERROR_CODE ,
           ERROR_DESCRIPTION ,
           A.MAKE_BY ,
           A.MAKE_DATE  
    FROM PERSONAL_DATA_ERROR A 
    JOIN PERSONAL_DATA B ON A.FI_SUBJECT_CODE = B.FI_SUBJECT_CODE
    WHERE A.REPORTING_PERIOD = L_REPORTING_PERIOD 
    AND A.VERSION_NO = L_VERSION_NO
    AND A.FI_SUBJECT_CODE = NVL(P_FI_SUBJECT_CODE, A.FI_SUBJECT_CODE)
    AND BRANCH_CODE = NVL(P_BRANCH_CODE, BRANCH_CODE)
    AND LOWER(B.NAME) LIKE LOWER(NVL('%'||P_FI_SUBJECT_NAME||'%','%'));
  END SP_GET_PERSONAL_DATA_ERROR;

  PROCEDURE SP_GET_INSTITUTION_ERROR
  (
    P_BRANCH_CODE     IN VARCHAR2,
    P_FI_SUBJECT_CODE IN VARCHAR2,
    P_FI_SUBJECT_NAME IN VARCHAR2,
    REF_CURSOR OUT SYS_REFCURSOR
  )
  AS
    L_VERSION_NO NUMBER;
    L_REPORTING_PERIOD DATE;
  BEGIN
    SELECT TO_DATE(VALUE, 'DD-MON-YYYY') INTO L_REPORTING_PERIOD FROM REPORTING_PARAMETERS WHERE KEY = 'REPORTING_PERIOD';
    
    SELECT MAX(VERSION_NO) INTO L_VERSION_NO FROM PERSONAL_DATA_REPORT WHERE REPORTING_PERIOD = L_REPORTING_PERIOD;
        
    OPEN REF_CURSOR FOR
    SELECT A.VERSION_NO ,
           REPORTING_PERIOD ,
           A.FI_SUBJECT_CODE ,
           B.TRADE_NAME SUBJECT_NAME,
           ERROR_CODE ,
           ERROR_DESCRIPTION ,
           A.MAKE_BY ,
           A.MAKE_DATE  
    FROM INSTITUTION_ERROR A 
    JOIN INSTITUTIONS B ON A.FI_SUBJECT_CODE = B.FI_SUBJECT_CODE
    WHERE A.REPORTING_PERIOD = L_REPORTING_PERIOD 
    AND A.VERSION_NO = L_VERSION_NO
    AND A.FI_SUBJECT_CODE = NVL(P_FI_SUBJECT_CODE, A.FI_SUBJECT_CODE)
    AND BRANCH_CODE = NVL(P_BRANCH_CODE, BRANCH_CODE)
    AND LOWER(B.TRADE_NAME) LIKE LOWER(NVL('%'||P_FI_SUBJECT_NAME||'%','%'));
  END SP_GET_INSTITUTION_ERROR;

  PROCEDURE SP_GET_INST_CONTRACT_ERROR
  (
      P_BRANCH_CODE      IN VARCHAR2,
      P_FI_SUBJECT_CODE  IN VARCHAR2,
      P_FI_CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR
  )
  AS
    L_VERSION_NO NUMBER;
    L_REPORTING_PERIOD DATE;
  BEGIN
    SELECT TO_DATE(VALUE, 'DD-MON-YYYY') INTO L_REPORTING_PERIOD FROM REPORTING_PARAMETERS WHERE KEY = 'REPORTING_PERIOD';
    
    SELECT MAX(VERSION_NO) INTO L_VERSION_NO FROM PERSONAL_DATA_REPORT WHERE REPORTING_PERIOD = L_REPORTING_PERIOD;
    
    OPEN REF_CURSOR FOR
    SELECT A.VERSION_NO ,
           A.REPORTING_PERIOD ,
           A.FI_CONTRACT_CODE ,
           B.FI_SUBJECT_CODE  FI_PRIMARY_CODE,
           C.SUBJECT_NAME FI_PRIMARY_NAME,
           A.ERROR_CODE ,
           A.ERROR_DESCRIPTION ,
           A.MAKE_BY ,
           A.MAKE_DATE  
    FROM INSTALMENT_CONTRACT_ERROR A
    JOIN INSTALMENT_CONTRACTS B ON A.FI_CONTRACT_CODE = B.FI_CONTRACT_CODE
    JOIN VW_SUBJECTS C ON B.FI_SUBJECT_CODE = C.FI_SUBJECT_CODE
    WHERE A.REPORTING_PERIOD = L_REPORTING_PERIOD
    AND A.VERSION_NO = L_VERSION_NO
    AND A.FI_CONTRACT_CODE = NVL(P_FI_CONTRACT_CODE, A.FI_CONTRACT_CODE)
    AND B.FI_SUBJECT_CODE = NVL(P_FI_SUBJECT_CODE, B.FI_SUBJECT_CODE)
    AND B.BRANCH_CODE = NVL(P_BRANCH_CODE, B.BRANCH_CODE)
    ;
  END SP_GET_INST_CONTRACT_ERROR;
  PROCEDURE SP_GET_NON_INST_CONTRACT_ERROR
  (
      P_BRANCH_CODE      IN VARCHAR2,
      P_FI_SUBJECT_CODE  IN VARCHAR2,
      P_FI_CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR
  )
  AS
    L_VERSION_NO NUMBER;
    L_REPORTING_PERIOD DATE;
  BEGIN
    SELECT TO_DATE(VALUE, 'DD-MON-YYYY') INTO L_REPORTING_PERIOD FROM REPORTING_PARAMETERS WHERE KEY = 'REPORTING_PERIOD';
    
    SELECT MAX(VERSION_NO) INTO L_VERSION_NO FROM PERSONAL_DATA_REPORT WHERE REPORTING_PERIOD = L_REPORTING_PERIOD;
    
    OPEN REF_CURSOR FOR
    SELECT A.VERSION_NO ,
           A.REPORTING_PERIOD ,
           A.FI_CONTRACT_CODE ,
           B.FI_SUBJECT_CODE  FI_PRIMARY_CODE,
           C.SUBJECT_NAME FI_PRIMARY_NAME,
           A.ERROR_CODE ,
           A.ERROR_DESCRIPTION ,
           A.MAKE_BY ,
           A.MAKE_DATE  
    FROM NON_INSTALMENT_CONTRACT_ERROR A
    JOIN NON_INSTALMENT_CONTRACTS B ON A.FI_CONTRACT_CODE = B.FI_CONTRACT_CODE
    JOIN VW_SUBJECTS C ON B.FI_SUBJECT_CODE = C.FI_SUBJECT_CODE
    WHERE A.REPORTING_PERIOD = L_REPORTING_PERIOD
    AND A.VERSION_NO = L_VERSION_NO
    AND A.FI_CONTRACT_CODE = NVL(P_FI_CONTRACT_CODE, A.FI_CONTRACT_CODE)
    AND B.FI_SUBJECT_CODE = NVL(P_FI_SUBJECT_CODE, B.FI_SUBJECT_CODE)
    AND B.BRANCH_CODE = NVL(P_BRANCH_CODE, B.BRANCH_CODE)
    ;
  END SP_GET_NON_INST_CONTRACT_ERROR;
  
  PROCEDURE SP_GET_CARD_CONTRACT_ERROR
  (
      P_BRANCH_CODE      IN VARCHAR2,
      P_FI_SUBJECT_CODE  IN VARCHAR2,
      P_FI_CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR
  )
  AS
    L_VERSION_NO NUMBER;
    L_REPORTING_PERIOD DATE;
  BEGIN
    SELECT TO_DATE(VALUE, 'DD-MON-YYYY') INTO L_REPORTING_PERIOD FROM REPORTING_PARAMETERS WHERE KEY = 'REPORTING_PERIOD';
    
    SELECT MAX(VERSION_NO) INTO L_VERSION_NO FROM PERSONAL_DATA_REPORT WHERE REPORTING_PERIOD = L_REPORTING_PERIOD;
    
    OPEN REF_CURSOR FOR
    SELECT A.VERSION_NO ,
           A.REPORTING_PERIOD ,
           A.FI_CONTRACT_CODE ,
           B.FI_SUBJECT_CODE  FI_PRIMARY_CODE,
           C.SUBJECT_NAME FI_PRIMARY_NAME,
           A.ERROR_CODE ,
           A.ERROR_DESCRIPTION ,
           A.MAKE_BY ,
           A.MAKE_DATE  
    FROM CARD_CONTRACT_ERROR A
    JOIN CARD_CONTRACTS B ON A.FI_CONTRACT_CODE = B.FI_CONTRACT_CODE
    JOIN VW_SUBJECTS C ON B.FI_SUBJECT_CODE = C.FI_SUBJECT_CODE
    WHERE A.REPORTING_PERIOD = L_REPORTING_PERIOD
    AND A.VERSION_NO = L_VERSION_NO
    AND A.FI_CONTRACT_CODE = NVL(P_FI_CONTRACT_CODE, A.FI_CONTRACT_CODE)
    AND B.FI_SUBJECT_CODE = NVL(P_FI_SUBJECT_CODE, B.FI_SUBJECT_CODE)
    AND B.BRANCH_CODE = NVL(P_BRANCH_CODE, B.BRANCH_CODE)
    ;
  END SP_GET_CARD_CONTRACT_ERROR;
END PKG_ERROR;
