CREATE OR REPLACE PACKAGE PKG_ACCOUNT AS 

  PROCEDURE SP_GET_APP_USER_BY_AD(ADID_IN IN VARCHAR2, REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_USER_ROLES_BY_AD(ADID_IN IN VARCHAR2, REF_CURSOR OUT SYS_REFCURSOR);

END PKG_ACCOUNT;
 
