CREATE OR REPLACE PACKAGE BODY PKG_MTH_END AS

  PROCEDURE SP_LOCK_SUBJECTS AS
  L_REP_DATE DATE;
  BEGIN
    SELECT TO_DATE(A.VALUE) INTO L_REP_DATE FROM REPORTING_PARAMETERS A WHERE A.KEY = 'REPORTING_PERIOD';
    
    UPDATE PERSONAL_DATA
    SET RECORD_STATUS = 'R'
    WHERE FI_SUBJECT_CODE IN 
    (
      SELECT FI_SUBJECT_CODE FROM PERSONAL_DATA_REPORT WHERE REPORTING_PERIOD = L_REP_DATE
    );
    
    UPDATE INSTITUTIONS
    SET RECORD_STATUS = 'R'
    WHERE FI_SUBJECT_CODE IN
    (
      SELECT FI_SUBJECT_CODE FROM INSTITUTION_REPORT WHERE REPORTING_PERIOD = L_REP_DATE
    );
    
  END SP_LOCK_SUBJECTS;

  PROCEDURE SP_LOCK_LINKS AS
  L_REP_DATE DATE;
  BEGIN
    SELECT TO_DATE(A.VALUE) INTO L_REP_DATE FROM REPORTING_PARAMETERS A WHERE A.KEY = 'REPORTING_PERIOD';
    
    UPDATE INSTITUTION_OWNER_LINKS
    SET RECORD_STATUS = 'R'
    WHERE RECORD_STATUS not in ('D','R','E')
    AND INSTITUTION_FI_SUBJECT_CODE IN 
    ( 
    SELECT FI_SUBJECT_CODE FROM INSTITUTION_REPORT WHERE REPORTING_PERIOD = L_REP_DATE
    );
    
    UPDATE CONTRACT_LINKS
    SET RECORD_STATUS = 'R'
    WHERE RECORD_STATUS not in ('D','R','E')
    AND FI_CONTRACT_CODE IN 
    ( 
    SELECT FI_CONTRACT_CODE FROM VW_CONTRACT_REPORT WHERE REPORTING_PERIOD = L_REP_DATE
    );    
  END SP_LOCK_LINKS;

  PROCEDURE SP_CLEAR_ERROR_LIST AS
  BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CARD_CONTRACT_ERROR';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CONTRACT_LINK_ERROR';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INSTALMENT_CONTRACT_ERROR';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INSTITUTION_ERROR';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE NON_INSTALMENT_CONTRACT_ERROR';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE OWNER_LINK_ERROR';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PERSONAL_DATA_ERROR';
  END SP_CLEAR_ERROR_LIST;

  PROCEDURE SP_TERMINATE_TMTA_CONTRACTS AS
  BEGIN
    update 
    INSTALMENT_CONTRACTS
    set RECORD_STATUS = 'T' --terminated
    where CONTRACT_PHASE in ('TM', 'TA') and RECORD_STATUS = 'U';
    
    update 
    non_INSTALMENT_CONTRACTS
    set RECORD_STATUS = 'T' --terminated
    where CONTRACT_PHASE in ('TM', 'TA') and RECORD_STATUS = 'U';
    
    update 
    card_CONTRACTS
    set RECORD_STATUS = 'T' --terminated
    where CONTRACT_PHASE in ('TM', 'TA') and RECORD_STATUS = 'U';
    
  END SP_TERMINATE_TMTA_CONTRACTS;

END PKG_MTH_END;
