CREATE OR REPLACE PACKAGE BODY PKG_ACCOUNT
AS
  PROCEDURE SP_GET_APP_USER_BY_AD(
      ADID_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT EMPID , ADID , FULLNAME , A.BRANCH_CODE , B.BRANCH_NAME, B.CIB_BRANCH_CODE , STATUS , AD
    FROM APP_USERS A JOIN BRANCHES B ON A.BRANCH_CODE = B.BRANCH_CODE WHERE STATUS = 'A' AND ADID = ADID_IN ;
  END SP_GET_APP_USER_BY_AD;
  
  
  PROCEDURE SP_GET_USER_ROLES_BY_AD(
      ADID_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT R.ROLE_CODE FROM APP_ROLES R JOIN APP_USER_ROLES UR ON R.ROLE_CODE = UR.ROLE_CODE AND
    R.STATUS = 'A' JOIN APP_USERS
    U ON UR.EMPID = U.EMPID AND
    U.STATUS = 'A' WHERE U.ADID = ADID_IN
    UNION
    SELECT
      R.ROLE_CODE
    FROM
      APP_ROLES R
    JOIN APP_ROLE_GROUP_ROLES RGR
    ON
      R.ROLE_CODE = RGR.ROLE_CODE
    AND R.STATUS  = 'A'
    JOIN APP_ROLE_GROUP_USERS RGU
    ON
      RGU.GROUP_CODE = RGR.GROUP_CODE
    JOIN APP_USERS U
    ON
      RGU.EMPID  = U.EMPID
    AND U.STATUS = 'A'
    WHERE
      U.ADID = ADID_IN ;
  END SP_GET_USER_ROLES_BY_AD;
END PKG_ACCOUNT;
