CREATE OR REPLACE PACKAGE BODY PKG_LOV 
AS
  PROCEDURE SP_3RD_PARTY_GUARANTEE_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_3RD_PARTY_GUARANTEE_TYPES;
  END SP_3RD_PARTY_GUARANTEE_TYPES;
  PROCEDURE SP_CONTRACT_PHASES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_CONTRACT_PHASES;
  END SP_CONTRACT_PHASES;
  PROCEDURE SP_CONTRACT_STATUS(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_CONTRACT_STATUS;
  END SP_CONTRACT_STATUS;
  PROCEDURE SP_CONTRACT_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_CONTRACT_TYPES;
  END SP_CONTRACT_TYPES;
  PROCEDURE SP_CONTRACT_TYPES_INST(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_CONTRACT_TYPES WHERE CATEGORY = 'Instalment';
  END SP_CONTRACT_TYPES_INST;
  PROCEDURE SP_CONTRACT_TYPES_NONINST(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_CONTRACT_TYPES WHERE CATEGORY = 'NonInstalment';
  END SP_CONTRACT_TYPES_NONINST;
  PROCEDURE SP_CONTRACT_TYPES_CARD(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_CONTRACT_TYPES WHERE CATEGORY = 'CreditCard';
  END SP_CONTRACT_TYPES_CARD;
  PROCEDURE SP_COUNTRIES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_COUNTRIES;
  END SP_COUNTRIES;
  PROCEDURE SP_CURRENCIES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_CURRENCIES;
  END SP_CURRENCIES;
  PROCEDURE SP_ECONOMIC_PURPOSE_CODES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , CODE||' - '||NAME NAME FROM LOV_ECONOMIC_PURPOSE_CODES;
  END SP_ECONOMIC_PURPOSE_CODES;
  PROCEDURE SP_ENTERPRISE_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_ENTERPRISE_TYPES;
  END SP_ENTERPRISE_TYPES;
  PROCEDURE SP_GENDER(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_GENDER;
  END SP_GENDER;
  PROCEDURE SP_ID_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_ID_TYPES;
  END SP_ID_TYPES;
  PROCEDURE SP_INSTALMENT_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_INSTALMENT_TYPES;
  END SP_INSTALMENT_TYPES;
  PROCEDURE SP_INSTITUTION_LEGAL_FORMS(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_INSTITUTION_LEGAL_FORMS;
  END SP_INSTITUTION_LEGAL_FORMS;
  PROCEDURE SP_LEASED_GOOD_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_LEASED_GOOD_TYPES;
  END SP_LEASED_GOOD_TYPES;
  PROCEDURE SP_LINK_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_LINK_TYPES;
  END SP_LINK_TYPES;
  PROCEDURE SP_NO_OF_DAYS(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_NO_OF_DAYS;
  END SP_NO_OF_DAYS;
  PROCEDURE SP_OWNER_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_OWNER_TYPES;
  END SP_OWNER_TYPES;
  PROCEDURE SP_PAYMENT_METHODS(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_PAYMENT_METHODS;
  END SP_PAYMENT_METHODS;
  PROCEDURE SP_PERIODICITY_OF_PAYMENT(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_PERIODICITY_OF_PAYMENT;
  END SP_PERIODICITY_OF_PAYMENT;
  PROCEDURE SP_PRE_FINANCE_OF_LOAN(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_PRE_FINANCE_OF_LOAN;
  END SP_PRE_FINANCE_OF_LOAN;
  PROCEDURE SP_REORGANIZED_CREDIT(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_REORGANIZED_CREDIT;
  END SP_REORGANIZED_CREDIT;
  PROCEDURE SP_SECTOR_CODES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , CODE||' - '||NAME NAME FROM LOV_SECTOR_CODES;
  END SP_SECTOR_CODES;
  PROCEDURE SP_SECTOR_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_SECTOR_TYPES;
  END SP_SECTOR_TYPES;
  PROCEDURE SP_SECURITY_TYPES(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_SECURITY_TYPES;
  END SP_SECURITY_TYPES;
  PROCEDURE SP_SUBSIDIZED_CREDIT(
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE , NAME FROM LOV_SUBSIDIZED_CREDIT;
  END SP_SUBSIDIZED_CREDIT;
  PROCEDURE SP_DISTRICTS(
      COUNTRY_CODE_IN IN VARCHAR,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT DISTRICT_NAME , COUNTRY_CODE FROM LOV_DISTRICTS WHERE COUNTRY_CODE = COUNTRY_CODE_IN;
  END SP_DISTRICTS;
  PROCEDURE SP_SUB_REGISTRY_OFFICES(
      IN_DISTRICT IN VARCHAR,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT SRO FROM LOV_SUB_REGISTRY_OFFICES 
    WHERE DISTRICT = IN_DISTRICT;
  END SP_SUB_REGISTRY_OFFICES;
  PROCEDURE SP_THANAS(      
      IN_DISTRICT IN VARCHAR,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT THANA FROM LOV_THANAS
    WHERE DISTRICT = IN_DISTRICT;
  END SP_THANAS;
  PROCEDURE SP_MOUZAS(      
      IN_DISTRICT IN VARCHAR,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT MOUZA FROM LOV_MOUZAS
    WHERE DISTRICT = IN_DISTRICT;
  END SP_MOUZAS;
  PROCEDURE SP_DEED_TYPES(      
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT CODE, NAME FROM LOV_DEED_TYPES;
  END SP_DEED_TYPES;
END PKG_LOV;
