CREATE OR REPLACE PACKAGE BODY UCIB.PKG_CONTRACT
AS
  PROCEDURE SP_INSTALMENT_CONTRACT_INSERT(
      IN_RECORD_TYPE                IN VARCHAR2,
      IN_FI_CODE                    IN VARCHAR2,
      IN_BRANCH_CODE                IN VARCHAR2,
      IN_FI_SUBJECT_CODE            IN VARCHAR2,
      IN_FI_CONTRACT_CODE           IN VARCHAR2,
      IN_CONTRACT_TYPE              IN VARCHAR2,
      IN_CONTRACT_PHASE             IN VARCHAR2,
      IN_CONTRACT_STATUS            IN VARCHAR2,
      IN_CURRENCY_CODE              IN VARCHAR2,
      IN_STARTING_DATE              IN DATE,
      IN_REQUEST_DATE               IN DATE,
      IN_PLANNED_END_DATE           IN DATE,
      IN_ACTUAL_END_DATE            IN DATE,
      IN_DEFAULTER_STATUS           IN VARCHAR2,
      IN_LAST_PAYMENT_DATE          IN DATE,
      IN_SUBSIDIZED_CREDIT          IN VARCHAR2,
      IN_PRE_FINANCE_LOAN           IN VARCHAR2,
      IN_REORGANIZED_CREDIT         IN VARCHAR2,
      IN_THIRD_PARTY_GUARANTEE_TYPE IN VARCHAR2,
      IN_SECURITY_TYPE              IN VARCHAR2,
      IN_AMOUNT_GURANTEED_3RD_PARTY IN NUMBER,
      IN_AMOUNT_GUARANTEED_SECURITY IN NUMBER,
      IN_QUALIFICATION_JUDGEMENT    IN VARCHAR2,
      IN_SANCTION_LIMIT             IN NUMBER,
      IN_TOTAL_DISBURSED_AMOUNT     IN NUMBER,
      IN_TOTAL_OUTSTANDING_AMOUNT   IN NUMBER,
      IN_TOTAL_NUMBER_INSTALMENTS   IN NUMBER,
      IN_PERIODICITY_PAYMENT        IN VARCHAR2,
      IN_METHOD_PAYMENT             IN VARCHAR2,
      IN_INSTALMENT_AMOUNT          IN NUMBER,
      IN_EXPIRATION_DATE_NEXT_INST  IN DATE,
      IN_AMOUNT_NEXT_EXPIRING_INST  IN NUMBER,
      IN_NO_OF_REMAINING_INSTALMENT IN NUMBER,
      IN_REMAINING_AMOUNT           IN NUMBER,
      IN_NO_OF_OVERDUE_INSTALMENT   IN NUMBER,
      IN_OVERDUE_AMOUNT             IN NUMBER,
      IN_NO_OF_DAYS_PAYMENT_DELAY   IN NUMBER,
      IN_TYPE_OF_LEASED_GOOD        IN VARCHAR2,
      IN_VALUE_OF_LEASED_GOOD       IN NUMBER,
      IN_REGISTRATION_NUMBER        IN VARCHAR2,
      IN_DATE_OF_MANUFACTURING      IN DATE,
      IN_DUE_FOR_RECOVERY           IN NUMBER,
      IN_RECOVERY_DURING_REPORTING  IN NUMBER,
      IN_CUMULATIVE_RECOVERY        IN NUMBER,
      IN_DATE_OF_LAW_SUIT           IN DATE,
      IN_DATE_OF_CLASSIFICATION     IN DATE,
      IN_NO_TIMES_RESCHEDULING      IN VARCHAR2,
      IN_DATE_LAST_RESCHEDULING     IN DATE,
      IN_ECONOMIC_PURPOSE_CODE      IN VARCHAR2,
      IN_SME                        IN VARCHAR2,
      IN_ENTERPRISE_TYPE            IN VARCHAR2,
      IN_MAKE_BY                    IN VARCHAR2,
      IN_MAKE_DATE                  IN DATE,
      IN_UBS_ACCOUNT_NO             IN VARCHAR2,
      IN_RECORD_STATUS              IN VARCHAR2 )
  AS
    C_EXISTS INT;
    S_EXISTS INT;
  BEGIN
    SELECT
      COUNT(1)
    INTO
      C_EXISTS
    FROM
      INSTALMENT_CONTRACTS A
    WHERE
      A.FI_CONTRACT_CODE = IN_FI_CONTRACT_CODE;
    SELECT
      COUNT(1)
    INTO
      S_EXISTS
    FROM
      INSTALMENT_CONTRACTS A
    WHERE
      A.FI_CONTRACT_CODE = IN_FI_CONTRACT_CODE
    AND
      A.FI_SUBJECT_CODE = IN_FI_SUBJECT_CODE;
    IF C_EXISTS          = 0 AND S_EXISTS = 0 THEN
      INSERT
      INTO
        INSTALMENT_CONTRACTS
        (
          RECORD_TYPE,
          FI_CODE,
          BRANCH_CODE,
          FI_SUBJECT_CODE,
          FI_CONTRACT_CODE,
          CONTRACT_TYPE,
          CONTRACT_PHASE,
          CONTRACT_STATUS,
          CURRENCY_CODE,
          STARTING_DATE,
          REQUEST_DATE,
          PLANNED_END_DATE,
          ACTUAL_END_DATE,
          DEFAULTER_STATUS,
          LAST_PAYMENT_DATE,
          SUBSIDIZED_CREDIT,
          PRE_FINANCE_LOAN,
          REORGANIZED_CREDIT,
          THIRD_PARTY_GUARANTEE_TYPE,
          SECURITY_TYPE,
          AMOUNT_GURANTEED_THIRD_PARTY,
          AMOUNT_GUARANTEED_SECURITY,
          QUALIFICATION_JUDGEMENT,
          SANCTION_LIMIT,
          TOTAL_DISBURSED_AMOUNT,
          TOTAL_OUTSTANDING_AMOUNT,
          TOTAL_NUMBER_INSTALMENTS,
          PERIODICITY_PAYMENT,
          METHOD_PAYMENT,
          INSTALMENT_AMOUNT,
          EXPIRATION_DATE_NEXT_INST,
          AMOUNT_NEXT_EXPIRING_INST,
          NO_OF_REMAINING_INSTALMENT,
          REMAINING_AMOUNT,
          NO_OF_OVERDUE_INSTALMENT,
          OVERDUE_AMOUNT,
          NO_OF_DAYS_PAYMENT_DELAY,
          TYPE_OF_LEASED_GOOD,
          VALUE_OF_LEASED_GOOD,
          REGISTRATION_NUMBER,
          DATE_OF_MANUFACTURING,
          DUE_FOR_RECOVERY,
          RECOVERY_DURING_REPORTING,
          CUMULATIVE_RECOVERY,
          DATE_OF_LAW_SUIT,
          DATE_OF_CLASSIFICATION,
          NO_TIMES_RESCHEDULING,
          DATE_LAST_RESCHEDULING,
          ECONOMIC_PURPOSE_CODE,
          SME,
          ENTERPRISE_TYPE,
          MAKE_BY,
          MAKE_DATE,
          RECORD_STATUS,
          UBS_ACCOUNT_NO
        )
        VALUES
        (
          IN_RECORD_TYPE ,
          IN_FI_CODE ,
          IN_BRANCH_CODE ,
          IN_FI_SUBJECT_CODE ,
          IN_FI_CONTRACT_CODE ,
          IN_CONTRACT_TYPE ,
          IN_CONTRACT_PHASE ,
          IN_CONTRACT_STATUS ,
          IN_CURRENCY_CODE ,
          IN_STARTING_DATE ,
          IN_REQUEST_DATE ,
          IN_PLANNED_END_DATE ,
          IN_ACTUAL_END_DATE ,
          IN_DEFAULTER_STATUS ,
          IN_LAST_PAYMENT_DATE ,
          IN_SUBSIDIZED_CREDIT ,
          IN_PRE_FINANCE_LOAN ,
          IN_REORGANIZED_CREDIT ,
          IN_THIRD_PARTY_GUARANTEE_TYPE ,
          IN_SECURITY_TYPE ,
          IN_AMOUNT_GURANTEED_3RD_PARTY ,
          IN_AMOUNT_GUARANTEED_SECURITY ,
          IN_QUALIFICATION_JUDGEMENT ,
          IN_SANCTION_LIMIT ,
          IN_TOTAL_DISBURSED_AMOUNT ,
          IN_TOTAL_OUTSTANDING_AMOUNT ,
          IN_TOTAL_NUMBER_INSTALMENTS ,
          IN_PERIODICITY_PAYMENT ,
          IN_METHOD_PAYMENT ,
          IN_INSTALMENT_AMOUNT ,
          IN_EXPIRATION_DATE_NEXT_INST ,
          IN_AMOUNT_NEXT_EXPIRING_INST ,
          IN_NO_OF_REMAINING_INSTALMENT ,
          IN_REMAINING_AMOUNT ,
          IN_NO_OF_OVERDUE_INSTALMENT ,
          IN_OVERDUE_AMOUNT ,
          IN_NO_OF_DAYS_PAYMENT_DELAY ,
          IN_TYPE_OF_LEASED_GOOD ,
          IN_VALUE_OF_LEASED_GOOD ,
          IN_REGISTRATION_NUMBER ,
          IN_DATE_OF_MANUFACTURING ,
          IN_DUE_FOR_RECOVERY ,
          IN_RECOVERY_DURING_REPORTING ,
          IN_CUMULATIVE_RECOVERY ,
          IN_DATE_OF_LAW_SUIT ,
          IN_DATE_OF_CLASSIFICATION ,
          IN_NO_TIMES_RESCHEDULING ,
          IN_DATE_LAST_RESCHEDULING ,
          IN_ECONOMIC_PURPOSE_CODE ,
          IN_SME ,
          IN_ENTERPRISE_TYPE ,
          IN_MAKE_BY ,
          SYSDATE ,
          IN_RECORD_STATUS,
          IN_UBS_ACCOUNT_NO
        );
    ELSIF C_EXISTS = 1 AND S_EXISTS = 1 THEN
      SP_INSTALMENT_CONTRACT_UPDATE ( IN_RECORD_TYPE , IN_FI_CODE , IN_BRANCH_CODE , IN_FI_SUBJECT_CODE ,
      IN_FI_CONTRACT_CODE , IN_CONTRACT_TYPE , IN_CONTRACT_PHASE , IN_CONTRACT_STATUS , IN_CURRENCY_CODE ,
      IN_STARTING_DATE , IN_REQUEST_DATE , IN_PLANNED_END_DATE , IN_ACTUAL_END_DATE , IN_DEFAULTER_STATUS ,
      IN_LAST_PAYMENT_DATE , IN_SUBSIDIZED_CREDIT , IN_PRE_FINANCE_LOAN , IN_REORGANIZED_CREDIT ,
      IN_THIRD_PARTY_GUARANTEE_TYPE , IN_SECURITY_TYPE , IN_AMOUNT_GURANTEED_3RD_PARTY , IN_AMOUNT_GUARANTEED_SECURITY
      , IN_QUALIFICATION_JUDGEMENT , IN_SANCTION_LIMIT , IN_TOTAL_DISBURSED_AMOUNT , IN_TOTAL_OUTSTANDING_AMOUNT ,
      IN_TOTAL_NUMBER_INSTALMENTS , IN_PERIODICITY_PAYMENT , IN_METHOD_PAYMENT , IN_INSTALMENT_AMOUNT ,
      IN_EXPIRATION_DATE_NEXT_INST , IN_AMOUNT_NEXT_EXPIRING_INST , IN_NO_OF_REMAINING_INSTALMENT , IN_REMAINING_AMOUNT
      , IN_NO_OF_OVERDUE_INSTALMENT , IN_OVERDUE_AMOUNT , IN_NO_OF_DAYS_PAYMENT_DELAY , IN_TYPE_OF_LEASED_GOOD ,
      IN_VALUE_OF_LEASED_GOOD , IN_REGISTRATION_NUMBER , IN_DATE_OF_MANUFACTURING , IN_DUE_FOR_RECOVERY ,
      IN_RECOVERY_DURING_REPORTING , IN_CUMULATIVE_RECOVERY , IN_DATE_OF_LAW_SUIT , IN_DATE_OF_CLASSIFICATION ,
      IN_NO_TIMES_RESCHEDULING , IN_DATE_LAST_RESCHEDULING , IN_ECONOMIC_PURPOSE_CODE , IN_SME , IN_ENTERPRISE_TYPE ,
      IN_MAKE_BY , IN_MAKE_DATE , IN_UBS_ACCOUNT_NO, 'U' --updated
      ) ;
    END IF;
  END SP_INSTALMENT_CONTRACT_INSERT;
  PROCEDURE SP_INST_CONTRACT_HIST_INSERT
    (
      FI_CONTRACT_CODE_IN IN VARCHAR2
    )
  AS
    L_VERSION_NO NUMBER
    (
      10
    )
    ;
  BEGIN
    SELECT
      MAX(VERSION_NO)+1
    INTO
      L_VERSION_NO
    FROM
      INSTALMENT_CONTRACTS_HIST
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
    IF L_VERSION_NO   IS NULL THEN
      L_VERSION_NO    := 1;
    END IF;
    INSERT
    INTO
      INSTALMENT_CONTRACTS_HIST
    SELECT
      L_VERSION_NO,
      SYSDATE,
      A.*
    FROM
      INSTALMENT_CONTRACTS A
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
  END SP_INST_CONTRACT_HIST_INSERT;
  PROCEDURE SP_INSTALMENT_CONTRACT_UPDATE(
      RECORD_TYPE_IN                IN VARCHAR2,
      FI_CODE_IN                    IN VARCHAR2,
      BRANCH_CODE_IN                IN VARCHAR2,
      FI_SUBJECT_CODE_IN            IN VARCHAR2,
      FI_CONTRACT_CODE_IN           IN VARCHAR2,
      CONTRACT_TYPE_IN              IN VARCHAR2,
      CONTRACT_PHASE_IN             IN VARCHAR2,
      CONTRACT_STATUS_IN            IN VARCHAR2,
      CURRENCY_CODE_IN              IN VARCHAR2,
      STARTING_DATE_IN              IN DATE,
      REQUEST_DATE_IN               IN DATE,
      PLANNED_END_DATE_IN           IN DATE,
      ACTUAL_END_DATE_IN            IN DATE,
      DEFAULTER_STATUS_IN           IN VARCHAR2,
      LAST_PAYMENT_DATE_IN          IN DATE,
      SUBSIDIZED_CREDIT_IN          IN VARCHAR2,
      PRE_FINANCE_LOAN_IN           IN VARCHAR2,
      REORGANIZED_CREDIT_IN         IN VARCHAR2,
      THIRD_PARTY_GUARANTEE_TYPE_IN IN VARCHAR2,
      SECURITY_TYPE_IN              IN VARCHAR2,
      AMOUNT_GURANTEED_3RD_PARTY_IN IN NUMBER,
      AMOUNT_GUARANTEED_SECURITY_IN IN NUMBER,
      QUALIFICATION_JUDGEMENT_IN    IN VARCHAR2,
      SANCTION_LIMIT_IN             IN NUMBER,
      TOTAL_DISBURSED_AMOUNT_IN     IN NUMBER,
      TOTAL_OUTSTANDING_AMOUNT_IN   IN NUMBER,
      TOTAL_NUMBER_INSTALMENTS_IN   IN NUMBER,
      PERIODICITY_PAYMENT_IN        IN VARCHAR2,
      METHOD_PAYMENT_IN             IN VARCHAR2,
      INSTALMENT_AMOUNT_IN          IN NUMBER,
      EXPIRATION_DATE_NEXT_INST_IN  IN DATE,
      AMOUNT_NEXT_EXPIRING_INST_IN  IN NUMBER,
      NO_OF_REMAINING_INSTALMENT_IN IN NUMBER,
      REMAINING_AMOUNT_IN           IN NUMBER,
      NO_OF_OVERDUE_INSTALMENT_IN   IN NUMBER,
      OVERDUE_AMOUNT_IN             IN NUMBER,
      NO_OF_DAYS_PAYMENT_DELAY_IN   IN NUMBER,
      TYPE_OF_LEASED_GOOD_IN        IN VARCHAR2,
      VALUE_OF_LEASED_GOOD_IN       IN NUMBER,
      REGISTRATION_NUMBER_IN        IN VARCHAR2,
      DATE_OF_MANUFACTURING_IN      IN DATE,
      DUE_FOR_RECOVERY_IN           IN NUMBER,
      RECOVERY_DURING_REPORTING_IN  IN NUMBER,
      CUMULATIVE_RECOVERY_IN        IN NUMBER,
      DATE_OF_LAW_SUIT_IN           IN DATE,
      DATE_OF_CLASSIFICATION_IN     IN DATE,
      NO_TIMES_RESCHEDULING_IN      IN VARCHAR2,
      DATE_LAST_RESCHEDULING_IN     IN DATE,
      ECONOMIC_PURPOSE_CODE_IN      IN VARCHAR2,
      SME_IN                        IN VARCHAR2,
      ENTERPRISE_TYPE_IN            IN VARCHAR2,
      MAKE_BY_IN                    IN VARCHAR2,
      MAKE_DATE_IN                  IN DATE,
      UBS_ACCOUNT_NO_IN             IN VARCHAR2,
      RECORD_STATUS_IN              IN VARCHAR2 )
  AS
    L_RECORD_STATUS VARCHAR2(1);
  BEGIN
    SELECT RECORD_STATUS INTO L_RECORD_STATUS FROM INSTALMENT_CONTRACTS WHERE FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
    IF L_RECORD_STATUS != 'T' THEN
      SP_INST_CONTRACT_HIST_INSERT(FI_CONTRACT_CODE_IN);
      UPDATE
        INSTALMENT_CONTRACTS
      SET
        RECORD_TYPE                  = RECORD_TYPE_IN,
        FI_CODE                      = FI_CODE_IN,
        BRANCH_CODE                  = DECODE(BRANCH_CODE_IN,'0000',BRANCH_CODE,BRANCH_CODE_IN),
        --FI_SUBJECT_CODE              = FI_SUBJECT_CODE_IN,
        --CONTRACT_TYPE                = CONTRACT_TYPE_IN,
        CONTRACT_PHASE               = CONTRACT_PHASE_IN,
        CONTRACT_STATUS              = CONTRACT_STATUS_IN,
        CURRENCY_CODE                = CURRENCY_CODE_IN,
        STARTING_DATE                = STARTING_DATE_IN,
        REQUEST_DATE                 = REQUEST_DATE_IN,
        PLANNED_END_DATE             = PLANNED_END_DATE_IN,
        ACTUAL_END_DATE              = ACTUAL_END_DATE_IN,
        DEFAULTER_STATUS             = DEFAULTER_STATUS_IN,
        LAST_PAYMENT_DATE            = LAST_PAYMENT_DATE_IN,
        SUBSIDIZED_CREDIT            = SUBSIDIZED_CREDIT_IN,
        PRE_FINANCE_LOAN             = PRE_FINANCE_LOAN,
        --REORGANIZED_CREDIT           = REORGANIZED_CREDIT_IN,
        THIRD_PARTY_GUARANTEE_TYPE   = THIRD_PARTY_GUARANTEE_TYPE_IN,
        SECURITY_TYPE                = SECURITY_TYPE_IN,
        AMOUNT_GURANTEED_THIRD_PARTY = AMOUNT_GURANTEED_3RD_PARTY_IN,
        AMOUNT_GUARANTEED_SECURITY   = AMOUNT_GUARANTEED_SECURITY_IN,
        QUALIFICATION_JUDGEMENT      = QUALIFICATION_JUDGEMENT_IN,
        SANCTION_LIMIT               = SANCTION_LIMIT_IN,
        TOTAL_DISBURSED_AMOUNT       = TOTAL_DISBURSED_AMOUNT_IN,
        TOTAL_OUTSTANDING_AMOUNT     = TOTAL_OUTSTANDING_AMOUNT_IN,
        TOTAL_NUMBER_INSTALMENTS     = TOTAL_NUMBER_INSTALMENTS_IN,
        PERIODICITY_PAYMENT          = PERIODICITY_PAYMENT_IN,
        METHOD_PAYMENT               = METHOD_PAYMENT_IN,
        INSTALMENT_AMOUNT            = INSTALMENT_AMOUNT_IN,
        EXPIRATION_DATE_NEXT_INST    = EXPIRATION_DATE_NEXT_INST_IN,
        AMOUNT_NEXT_EXPIRING_INST    = AMOUNT_NEXT_EXPIRING_INST_IN,
        NO_OF_REMAINING_INSTALMENT   = NO_OF_REMAINING_INSTALMENT_IN,
        REMAINING_AMOUNT             = REMAINING_AMOUNT_IN,
        NO_OF_OVERDUE_INSTALMENT     = NO_OF_OVERDUE_INSTALMENT_IN,
        OVERDUE_AMOUNT               = OVERDUE_AMOUNT_IN,
        NO_OF_DAYS_PAYMENT_DELAY     = NO_OF_DAYS_PAYMENT_DELAY_IN,
        TYPE_OF_LEASED_GOOD          = TYPE_OF_LEASED_GOOD_IN,
        VALUE_OF_LEASED_GOOD         = VALUE_OF_LEASED_GOOD_IN,
        REGISTRATION_NUMBER          = REGISTRATION_NUMBER_IN,
        DATE_OF_MANUFACTURING        = DATE_OF_MANUFACTURING_IN,
        DUE_FOR_RECOVERY             = DUE_FOR_RECOVERY_IN,
        RECOVERY_DURING_REPORTING    = RECOVERY_DURING_REPORTING_IN,
        CUMULATIVE_RECOVERY          = CUMULATIVE_RECOVERY_IN,
        DATE_OF_LAW_SUIT             = DATE_OF_LAW_SUIT_IN,
        DATE_OF_CLASSIFICATION       = DATE_OF_CLASSIFICATION_IN,
        NO_TIMES_RESCHEDULING        = NO_TIMES_RESCHEDULING_IN,
        DATE_LAST_RESCHEDULING       = DATE_LAST_RESCHEDULING_IN,
        ECONOMIC_PURPOSE_CODE        = ECONOMIC_PURPOSE_CODE_IN,
        SME                          = SME_IN,
        ENTERPRISE_TYPE              = ENTERPRISE_TYPE_IN,
        MAKE_BY                      = MAKE_BY_IN,
        MAKE_DATE                    = SYSDATE,
        UBS_ACCOUNT_NO               = NVL(UBS_ACCOUNT_NO, UBS_ACCOUNT_NO_IN),
        RECORD_STATUS                = RECORD_STATUS_IN
      WHERE
        FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN ;
    END IF;
  END SP_INSTALMENT_CONTRACT_UPDATE;
  PROCEDURE SP_NON_INSTL_CONTRACT_INSERT(
      IN_RECORD_TYPE                 IN VARCHAR2,
      IN_FI_CODE                     IN VARCHAR2,
      IN_BRANCH_CODE                 IN VARCHAR2,
      IN_FI_SUBJECT_CODE             IN VARCHAR2,
      IN_FI_CONTRACT_CODE            IN VARCHAR2,
      IN_CONTRACT_TYPE               IN VARCHAR2,
      IN_CONTRACT_PHASE              IN VARCHAR2,
      IN_CONTRACT_STATUS             IN VARCHAR2,
      IN_CURRENCY_CODE               IN VARCHAR2,
      IN_STARTING_DATE               IN DATE,
      IN_REQUEST_DATE                IN DATE,
      IN_PLANNED_END_DATE            IN DATE,
      IN_ACTUAL_END_DATE             IN DATE,
      IN_DEFAULTER_STATUS            IN VARCHAR2,
      IN_DATE_OF_LAST_PAYMENT        IN DATE,
      IN_SUBSIDIZED_CREDIT           IN VARCHAR2,
      IN_PRE_FINANCE_LOAN            IN VARCHAR2,
      IN_REORGANIZED_CREDIT          IN VARCHAR2,
      IN_THIRD_PARTY_GUARANTEE_TYPE  IN VARCHAR2,
      IN_SECURITY_TYPE               IN VARCHAR2,
      IN_AMOUNT_GUARANTEED_3RD_PARTY IN NUMBER,
      IN_AMOUNT_GUARANTEED_SECURITY  IN NUMBER,
      IN_QUALITATIVE_JUDGEMENT       IN VARCHAR2,
      IN_SANCTION_LIMIT              IN NUMBER,
      IN_TOTAL_OUTSTANDING_AMOUNT    IN NUMBER,
      IN_NO_OF_DAYS_PAYMENT_DELAY    IN NUMBER,
      IN_DUE_FOR_RECOVERY            IN NUMBER,
      IN_RECOVERY_DURING_REPORTING   IN NUMBER,
      IN_CUMULATIVE_RECOVERY         IN NUMBER,
      IN_DATE_OF_LAW_SUIT            IN DATE,
      IN_DATE_OF_CLASSIFICATION      IN DATE,
      IN_NO_OF_TIMES_RESCHEDULING    IN VARCHAR2,
      IN_DATE_LAST_RESCHEDULING      IN DATE,
      IN_ECONOMIC_PURPOSE_CODE       IN VARCHAR2,
      IN_SME                         IN VARCHAR2,
      IN_ENTERPRISE_TYPE             IN VARCHAR2,
      IN_MAKE_BY                     IN VARCHAR2,
      IN_MAKE_DATE                   IN DATE,
      IN_UBS_ACCOUNT_NO              IN VARCHAR2,
      IN_RECORD_STATUS               IN VARCHAR2 )
  AS
    L_CONTRACT_EXIST INT;
    L_SUBJECT_EXIST INT;
  BEGIN
    SELECT
      COUNT(1)
    INTO
      L_CONTRACT_EXIST
    FROM
      NON_INSTALMENT_CONTRACTS A
    WHERE
      A.FI_CONTRACT_CODE = IN_FI_CONTRACT_CODE;
    SELECT
      COUNT(1)
    INTO
      L_SUBJECT_EXIST
    FROM
      NON_INSTALMENT_CONTRACTS A
    WHERE
      A.FI_CONTRACT_CODE = IN_FI_CONTRACT_CODE
    AND
      A.FI_SUBJECT_CODE = IN_FI_SUBJECT_CODE;
    IF L_CONTRACT_EXIST  = 0 AND L_SUBJECT_EXIST = 0 THEN
      INSERT
      INTO
        NON_INSTALMENT_CONTRACTS
        (
          RECORD_TYPE,
          FI_CODE,
          BRANCH_CODE,
          FI_SUBJECT_CODE,
          FI_CONTRACT_CODE,
          CONTRACT_TYPE,
          CONTRACT_PHASE,
          CONTRACT_STATUS,
          CURRENCY_CODE,
          STARTING_DATE,
          REQUEST_DATE,
          PLANNED_END_DATE,
          ACTUAL_END_DATE,
          DEFAULTER_STATUS,
          DATE_OF_LAST_PAYMENT,
          SUBSIDIZED_CREDIT,
          PRE_FINANCE_LOAN,
          REORGANIZED_CREDIT,
          THIRD_PARTY_GUARANTEE_TYPE,
          SECURITY_TYPE,
          AMOUNT_GUARANTEED_THIRD_PARTY,
          AMOUNT_GUARANTEED_SECURITY,
          QUALITATIVE_JUDGEMENT,
          SANCTION_LIMIT,
          TOTAL_OUTSTANDING_AMOUNT,
          NO_OF_DAYS_PAYMENT_DELAY,
          DUE_FOR_RECOVERY,
          RECOVERY_DURING_REPORTING,
          CUMULATIVE_RECOVERY,
          DATE_OF_LAW_SUIT,
          DATE_OF_CLASSIFICATION,
          NO_OF_TIMES_RESCHEDULING,
          DATE_LAST_RESCHEDULING,
          ECONOMIC_PURPOSE_CODE,
          SME,
          ENTERPRISE_TYPE,
          MAKE_BY,
          MAKE_DATE,
          UBS_ACCOUNT_NO,
          RECORD_STATUS
        )
        VALUES
        (
          IN_RECORD_TYPE ,
          IN_FI_CODE ,
          IN_BRANCH_CODE ,
          IN_FI_SUBJECT_CODE ,
          IN_FI_CONTRACT_CODE ,
          IN_CONTRACT_TYPE ,
          IN_CONTRACT_PHASE ,
          IN_CONTRACT_STATUS ,
          IN_CURRENCY_CODE ,
          IN_STARTING_DATE ,
          IN_REQUEST_DATE ,
          IN_PLANNED_END_DATE ,
          IN_ACTUAL_END_DATE ,
          IN_DEFAULTER_STATUS ,
          IN_DATE_OF_LAST_PAYMENT ,
          IN_SUBSIDIZED_CREDIT ,
          IN_PRE_FINANCE_LOAN ,
          IN_REORGANIZED_CREDIT ,
          IN_THIRD_PARTY_GUARANTEE_TYPE ,
          IN_SECURITY_TYPE ,
          IN_AMOUNT_GUARANTEED_3RD_PARTY ,
          IN_AMOUNT_GUARANTEED_SECURITY ,
          IN_QUALITATIVE_JUDGEMENT ,
          IN_SANCTION_LIMIT ,
          IN_TOTAL_OUTSTANDING_AMOUNT ,
          IN_NO_OF_DAYS_PAYMENT_DELAY ,
          IN_DUE_FOR_RECOVERY ,
          IN_RECOVERY_DURING_REPORTING ,
          IN_CUMULATIVE_RECOVERY ,
          IN_DATE_OF_LAW_SUIT ,
          IN_DATE_OF_CLASSIFICATION ,
          IN_NO_OF_TIMES_RESCHEDULING ,
          IN_DATE_LAST_RESCHEDULING ,
          IN_ECONOMIC_PURPOSE_CODE ,
          IN_SME ,
          IN_ENTERPRISE_TYPE ,
          IN_MAKE_BY ,
          SYSDATE ,
          IN_UBS_ACCOUNT_NO,
          IN_RECORD_STATUS
        );
    ELSIF L_CONTRACT_EXIST  = 1 AND L_SUBJECT_EXIST = 1 THEN
      SP_NON_INSTL_CONTRACT_UPDATE ( IN_RECORD_TYPE , IN_FI_CODE , IN_BRANCH_CODE , IN_FI_SUBJECT_CODE ,
      IN_FI_CONTRACT_CODE , IN_CONTRACT_TYPE , IN_CONTRACT_PHASE , IN_CONTRACT_STATUS , IN_CURRENCY_CODE ,
      IN_STARTING_DATE , IN_REQUEST_DATE , IN_PLANNED_END_DATE , IN_ACTUAL_END_DATE , IN_DEFAULTER_STATUS ,
      IN_DATE_OF_LAST_PAYMENT , IN_SUBSIDIZED_CREDIT , IN_PRE_FINANCE_LOAN , IN_REORGANIZED_CREDIT ,
      IN_THIRD_PARTY_GUARANTEE_TYPE , IN_SECURITY_TYPE , IN_AMOUNT_GUARANTEED_3RD_PARTY , IN_AMOUNT_GUARANTEED_SECURITY
      , IN_QUALITATIVE_JUDGEMENT , IN_SANCTION_LIMIT , IN_TOTAL_OUTSTANDING_AMOUNT , IN_NO_OF_DAYS_PAYMENT_DELAY ,
      IN_DUE_FOR_RECOVERY , IN_RECOVERY_DURING_REPORTING , IN_CUMULATIVE_RECOVERY , IN_DATE_OF_LAW_SUIT ,
      IN_DATE_OF_CLASSIFICATION , IN_NO_OF_TIMES_RESCHEDULING , IN_DATE_LAST_RESCHEDULING , IN_ECONOMIC_PURPOSE_CODE ,
      IN_SME , IN_ENTERPRISE_TYPE , IN_MAKE_BY , IN_MAKE_DATE , IN_UBS_ACCOUNT_NO, 'U' ) ;
    END IF;
  END SP_NON_INSTL_CONTRACT_INSERT;
  PROCEDURE SP_NON_INST_CONTRACT_HIST_INS
    (
      FI_CONTRACT_CODE_IN IN VARCHAR2
    )
  AS
    L_VERSION_NO NUMBER
    (
      10
    )
    ;
  BEGIN
    SELECT
      MAX(VERSION_NO)+1
    INTO
      L_VERSION_NO
    FROM
      NON_INSTALMENT_CONTRACTS_HIST
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
    IF L_VERSION_NO   IS NULL THEN
      L_VERSION_NO    := 1;
    END IF;
    INSERT
    INTO
      NON_INSTALMENT_CONTRACTS_HIST
    SELECT
      L_VERSION_NO,
      SYSDATE,
      A.*
    FROM
      NON_INSTALMENT_CONTRACTS A
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
  END SP_NON_INST_CONTRACT_HIST_INS;
  PROCEDURE SP_NON_INSTL_CONTRACT_UPDATE(
      RECORD_TYPE_IN                 IN VARCHAR2,
      FI_CODE_IN                     IN VARCHAR2,
      BRANCH_CODE_IN                 IN VARCHAR2,
      FI_SUBJECT_CODE_IN             IN VARCHAR2,
      FI_CONTRACT_CODE_IN            IN VARCHAR2,
      CONTRACT_TYPE_IN               IN VARCHAR2,
      CONTRACT_PHASE_IN              IN VARCHAR2,
      CONTRACT_STATUS_IN             IN VARCHAR2,
      CURRENCY_CODE_IN               IN VARCHAR2,
      STARTING_DATE_IN               IN DATE,
      REQUEST_DATE_IN                IN DATE,
      PLANNED_END_DATE_IN            IN DATE,
      ACTUAL_END_DATE_IN             IN DATE,
      DEFAULTER_STATUS_IN            IN VARCHAR2,
      DATE_OF_LAST_PAYMENT_IN        IN DATE,
      SUBSIDIZED_CREDIT_IN           IN VARCHAR2,
      PRE_FINANCE_LOAN_IN            IN VARCHAR2,
      REORGANIZED_CREDIT_IN          IN VARCHAR2,
      THIRD_PARTY_GUARANTEE_TYPE_IN  IN VARCHAR2,
      SECURITY_TYPE_IN               IN VARCHAR2,
      AMOUNT_GUARANTEED_3RD_PARTY_IN IN NUMBER,
      AMOUNT_GUARANTEED_SECURITY_IN  IN NUMBER,
      QUALITATIVE_JUDGEMENT_IN       IN VARCHAR2,
      SANCTION_LIMIT_IN              IN NUMBER,
      TOTAL_OUTSTANDING_AMOUNT_IN    IN NUMBER,
      NO_OF_DAYS_PAYMENT_DELAY_IN    IN NUMBER,
      DUE_FOR_RECOVERY_IN            IN NUMBER,
      RECOVERY_DURING_REPORTING_IN   IN NUMBER,
      CUMULATIVE_RECOVERY_IN         IN NUMBER,
      DATE_OF_LAW_SUIT_IN            IN DATE,
      DATE_OF_CLASSIFICATION_IN      IN DATE,
      NO_OF_TIMES_RESCHEDULING_IN    IN VARCHAR2,
      DATE_LAST_RESCHEDULING_IN      IN DATE,
      ECONOMIC_PURPOSE_CODE_IN       IN VARCHAR2,
      SME_IN                         IN VARCHAR2,
      ENTERPRISE_TYPE_IN             IN VARCHAR2,
      MAKE_BY_IN                     IN VARCHAR2,
      MAKE_DATE_IN                   IN DATE,
      UBS_ACCOUNT_NO_IN              IN VARCHAR2,
      RECORD_STATUS_IN               IN VARCHAR2 )
  AS
    L_RECORD_STATUS VARCHAR2(1);
  BEGIN
    SELECT RECORD_STATUS INTO L_RECORD_STATUS FROM NON_INSTALMENT_CONTRACTS WHERE FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
    IF L_RECORD_STATUS != 'T' THEN
      SP_NON_INST_CONTRACT_HIST_INS(FI_CONTRACT_CODE_IN);
      UPDATE
        NON_INSTALMENT_CONTRACTS
      SET
        RECORD_TYPE                   = RECORD_TYPE_IN ,
        FI_CODE                       = FI_CODE_IN ,
        BRANCH_CODE                   = DECODE(BRANCH_CODE_IN,'0000',BRANCH_CODE,BRANCH_CODE_IN) ,
        --FI_SUBJECT_CODE               = FI_SUBJECT_CODE_IN ,
        --CONTRACT_TYPE                 = CONTRACT_TYPE_IN ,
        CONTRACT_PHASE                = CONTRACT_PHASE_IN ,
        CONTRACT_STATUS               = CONTRACT_STATUS_IN ,
        CURRENCY_CODE                 = CURRENCY_CODE_IN ,
        STARTING_DATE                 = STARTING_DATE_IN ,
        REQUEST_DATE                  = REQUEST_DATE_IN ,
        PLANNED_END_DATE              = PLANNED_END_DATE_IN ,
        ACTUAL_END_DATE               = ACTUAL_END_DATE_IN ,
        DEFAULTER_STATUS              = DEFAULTER_STATUS_IN ,
        DATE_OF_LAST_PAYMENT          = DATE_OF_LAST_PAYMENT_IN ,
        SUBSIDIZED_CREDIT             = SUBSIDIZED_CREDIT_IN ,
        PRE_FINANCE_LOAN              = PRE_FINANCE_LOAN_IN ,
        --REORGANIZED_CREDIT            = REORGANIZED_CREDIT_IN ,
        THIRD_PARTY_GUARANTEE_TYPE    = THIRD_PARTY_GUARANTEE_TYPE_IN ,
        SECURITY_TYPE                 = SECURITY_TYPE_IN ,
        AMOUNT_GUARANTEED_THIRD_PARTY = AMOUNT_GUARANTEED_3RD_PARTY_IN,
        AMOUNT_GUARANTEED_SECURITY    = AMOUNT_GUARANTEED_SECURITY_IN ,
        QUALITATIVE_JUDGEMENT         = QUALITATIVE_JUDGEMENT_IN ,
        SANCTION_LIMIT                = SANCTION_LIMIT_IN ,
        TOTAL_OUTSTANDING_AMOUNT      = TOTAL_OUTSTANDING_AMOUNT_IN ,
        NO_OF_DAYS_PAYMENT_DELAY      = NO_OF_DAYS_PAYMENT_DELAY_IN ,
        DUE_FOR_RECOVERY              = DUE_FOR_RECOVERY_IN ,
        RECOVERY_DURING_REPORTING     = RECOVERY_DURING_REPORTING_IN ,
        CUMULATIVE_RECOVERY           = CUMULATIVE_RECOVERY_IN ,
        DATE_OF_LAW_SUIT              = DATE_OF_LAW_SUIT_IN ,
        DATE_OF_CLASSIFICATION        = DATE_OF_CLASSIFICATION_IN ,
        NO_OF_TIMES_RESCHEDULING      = NO_OF_TIMES_RESCHEDULING_IN ,
        DATE_LAST_RESCHEDULING        = DATE_LAST_RESCHEDULING_IN ,
        ECONOMIC_PURPOSE_CODE         = ECONOMIC_PURPOSE_CODE_IN ,
        SME                           = SME_IN ,
        ENTERPRISE_TYPE               = ENTERPRISE_TYPE_IN ,
        MAKE_BY                       = MAKE_BY_IN ,
        MAKE_DATE                     = SYSDATE ,
        RECORD_STATUS                 = RECORD_STATUS_IN,
        UBS_ACCOUNT_NO                = UBS_ACCOUNT_NO_IN
      WHERE
        FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
    END IF;
  END SP_NON_INSTL_CONTRACT_UPDATE;
  PROCEDURE SP_CARD_CONTRACT_INSERT(
      IN_RECORD_TYPE                 IN VARCHAR2,
      IN_FI_CODE                     IN VARCHAR2,
      IN_BRANCH_CODE                 IN VARCHAR2,
      IN_FI_SUBJECT_CODE             IN VARCHAR2,
      IN_FI_CONTRACT_CODE            IN VARCHAR2,
      IN_CONTRACT_TYPE               IN VARCHAR2,
      IN_CONTRACT_PHASE              IN VARCHAR2,
      IN_CONTRACT_STATUS             IN VARCHAR2,
      IN_CURRENCY_CODE               IN VARCHAR2,
      IN_STARTING_DATE               IN DATE,
      IN_REQUEST_DATE                IN DATE,
      IN_PLANNED_END_DATE            IN DATE,
      IN_ACTUAL_END_DATE             IN DATE,
      IN_DEFAULTER_STATUS            IN VARCHAR2,
      IN_DATE_LAST_PAYMENT           IN DATE,
      IN_SUBSIDIZED_CREDIT           IN VARCHAR2,
      IN_PRE_FINANCE_OF_LOAN         IN VARCHAR2,
      IN_REORGANIZED_CREDIT          IN VARCHAR2,
      IN_THIRD_PARTY_GUARANTEE_TYPE  IN VARCHAR2,
      IN_SECURITY_TYPE               IN VARCHAR2,
      IN_AMOUNT_GUARANTEED_3RD_PARTY IN NUMBER,
      IN_AMOUNT_GUARANTEED_SECURITY  IN NUMBER,
      IN_QUALITATIVE_JUDGEMENT       IN VARCHAR2,
      IN_PERIODICITY_PAYMENT         IN VARCHAR2,
      IN_METHOD_OF_PAYMENT           IN VARCHAR2,
      IN_INSTALMENT_AMOUNT           IN NUMBER,
      IN_CREDIT_LIMIT                IN NUMBER,
      IN_TOTAL_OUTSTANDING_AMOUNT    IN NUMBER,
      IN_EXPIRATION_DATE_NEXT_INST   IN DATE,
      IN_REMAINING_AMOUNT            IN NUMBER,
      IN_NUMBER_OF_OVERDUE           IN NUMBER,
      IN_OVERDUE_AMOUNT              IN NUMBER,
      IN_DATE_OF_LAST_CHARGE         IN DATE,
      IN_TYPE_OF_INSTALMENT          IN VARCHAR2,
      IN_NO_OF_DAYS_PAYMENT_DELAY    IN NUMBER,
      IN_DUE_FOR_RECOVERY            IN NUMBER,
      IN_RECOVERY_DURING_REPORTING   IN NUMBER,
      IN_CUMULATIVE_RECOVERY         IN NUMBER,
      IN_DATE_OF_LAW_SUIT            IN DATE,
      IN_ECONOMIC_PURPOSE_CODE       IN VARCHAR2,
      IN_MAKE_BY                     IN VARCHAR2,
      IN_MAKE_DATE                   IN DATE,
      IN_RECORD_STATUS               IN VARCHAR2,
      IN_DATE_OF_CLASSIFICATION      IN DATE)
  AS
    L_CONTRACT_EXIST INT;
  BEGIN
    SELECT
      COUNT(1)
    INTO
      L_CONTRACT_EXIST
    FROM
      CARD_CONTRACTS A
    WHERE
      A.FI_CONTRACT_CODE = IN_FI_CONTRACT_CODE;
    IF L_CONTRACT_EXIST IS NULL OR L_CONTRACT_EXIST = 0 THEN
      INSERT
      INTO
        CARD_CONTRACTS
        (
          RECORD_TYPE,
          FI_CODE,
          BRANCH_CODE,
          FI_SUBJECT_CODE,
          FI_CONTRACT_CODE,
          CONTRACT_TYPE,
          CONTRACT_PHASE,
          CONTRACT_STATUS,
          CURRENCY_CODE,
          STARTING_DATE,
          REQUEST_DATE,
          PLANNED_END_DATE,
          ACTUAL_END_DATE,
          DEFAULTER_STATUS,
          DATE_LAST_PAYMENT,
          SUBSIDIZED_CREDIT,
          PRE_FINANCE_OF_LOAN,
          REORGANIZED_CREDIT,
          THIRD_PARTY_GUARANTEE_TYPE,
          SECURITY_TYPE,
          AMOUNT_GUARANTEED_THIRD_PARTY,
          AMOUNT_GUARANTEED_SECURITY,
          QUALITATIVE_JUDGEMENT,
          PERIODICITY_PAYMENT,
          METHOD_OF_PAYMENT,
          INSTALMENT_AMOUNT,
          CREDIT_LIMIT,
          TOTAL_OUTSTANDING_AMOUNT,
          EXPIRATION_DATE_NEXT_INST,
          REMAINING_AMOUNT,
          NUMBER_OF_OVERDUE,
          OVERDUE_AMOUNT,
          DATE_OF_LAST_CHARGE,
          TYPE_OF_INSTALMENT,
          NO_OF_DAYS_PAYMENT_DELAY,
          DUE_FOR_RECOVERY,
          RECOVERY_DURING_REPORTING,
          CUMULATIVE_RECOVERY,
          DATE_OF_LAW_SUIT,
          ECONOMIC_PURPOSE_CODE,
          MAKE_BY,
          MAKE_DATE,
          RECORD_STATUS,
          DATE_OF_CLASSIFICATION
        )
        VALUES
        (
          IN_RECORD_TYPE ,
          IN_FI_CODE ,
          IN_BRANCH_CODE ,
          IN_FI_SUBJECT_CODE ,
          IN_FI_CONTRACT_CODE ,
          IN_CONTRACT_TYPE ,
          IN_CONTRACT_PHASE ,
          IN_CONTRACT_STATUS ,
          IN_CURRENCY_CODE ,
          IN_STARTING_DATE ,
          IN_REQUEST_DATE ,
          IN_PLANNED_END_DATE ,
          IN_ACTUAL_END_DATE ,
          IN_DEFAULTER_STATUS ,
          IN_DATE_LAST_PAYMENT ,
          IN_SUBSIDIZED_CREDIT ,
          IN_PRE_FINANCE_OF_LOAN ,
          IN_REORGANIZED_CREDIT ,
          IN_THIRD_PARTY_GUARANTEE_TYPE ,
          IN_SECURITY_TYPE ,
          IN_AMOUNT_GUARANTEED_3RD_PARTY ,
          IN_AMOUNT_GUARANTEED_SECURITY ,
          IN_QUALITATIVE_JUDGEMENT ,
          IN_PERIODICITY_PAYMENT ,
          IN_METHOD_OF_PAYMENT ,
          IN_INSTALMENT_AMOUNT ,
          IN_CREDIT_LIMIT ,
          IN_TOTAL_OUTSTANDING_AMOUNT ,
          IN_EXPIRATION_DATE_NEXT_INST ,
          IN_REMAINING_AMOUNT ,
          IN_NUMBER_OF_OVERDUE ,
          IN_OVERDUE_AMOUNT ,
          IN_DATE_OF_LAST_CHARGE ,
          IN_TYPE_OF_INSTALMENT ,
          IN_NO_OF_DAYS_PAYMENT_DELAY ,
          IN_DUE_FOR_RECOVERY ,
          IN_RECOVERY_DURING_REPORTING ,
          IN_CUMULATIVE_RECOVERY ,
          IN_DATE_OF_LAW_SUIT ,
          IN_ECONOMIC_PURPOSE_CODE ,
          IN_MAKE_BY ,
          SYSDATE ,
          IN_RECORD_STATUS,
          IN_DATE_OF_CLASSIFICATION
        );
    ELSE
      SP_CARD_CONTRACT_UPDATE ( IN_RECORD_TYPE , IN_FI_CODE , IN_BRANCH_CODE , IN_FI_SUBJECT_CODE , IN_FI_CONTRACT_CODE
      , IN_CONTRACT_TYPE , IN_CONTRACT_PHASE , IN_CONTRACT_STATUS , IN_CURRENCY_CODE , IN_STARTING_DATE ,
      IN_REQUEST_DATE , IN_PLANNED_END_DATE , IN_ACTUAL_END_DATE , IN_DEFAULTER_STATUS , IN_DATE_LAST_PAYMENT ,
      IN_SUBSIDIZED_CREDIT , IN_PRE_FINANCE_OF_LOAN , IN_REORGANIZED_CREDIT , IN_THIRD_PARTY_GUARANTEE_TYPE ,
      IN_SECURITY_TYPE , IN_AMOUNT_GUARANTEED_3RD_PARTY , IN_AMOUNT_GUARANTEED_SECURITY , IN_QUALITATIVE_JUDGEMENT ,
      IN_PERIODICITY_PAYMENT , IN_METHOD_OF_PAYMENT , IN_INSTALMENT_AMOUNT , IN_CREDIT_LIMIT ,
      IN_TOTAL_OUTSTANDING_AMOUNT , IN_EXPIRATION_DATE_NEXT_INST , IN_REMAINING_AMOUNT , IN_NUMBER_OF_OVERDUE ,
      IN_OVERDUE_AMOUNT , IN_DATE_OF_LAST_CHARGE , IN_TYPE_OF_INSTALMENT , IN_NO_OF_DAYS_PAYMENT_DELAY ,
      IN_DUE_FOR_RECOVERY , IN_RECOVERY_DURING_REPORTING , IN_CUMULATIVE_RECOVERY , IN_DATE_OF_LAW_SUIT ,
      IN_ECONOMIC_PURPOSE_CODE , IN_MAKE_BY , IN_MAKE_DATE , 'U', IN_DATE_OF_CLASSIFICATION ) ;
    END IF;
  END SP_CARD_CONTRACT_INSERT;
  PROCEDURE SP_CARD_CONTRACT_HIST_INSERT
    (
      FI_CONTRACT_CODE_IN IN VARCHAR2
    )
  AS
    L_VERSION_NO NUMBER
    (
      10
    )
    ;
  BEGIN
    SELECT
      MAX(VERSION_NO)+1
    INTO
      L_VERSION_NO
    FROM
      CARD_CONTRACTS_HIST
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
    IF L_VERSION_NO   IS NULL THEN
      L_VERSION_NO    := 1;
    END IF;
    INSERT
    INTO
      CARD_CONTRACTS_HIST
    SELECT
      L_VERSION_NO,
      SYSDATE,
      A.*
    FROM
      CARD_CONTRACTS A
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
  END SP_CARD_CONTRACT_HIST_INSERT;
  PROCEDURE SP_CARD_CONTRACT_UPDATE(
      RECORD_TYPE_IN                 IN VARCHAR2,
      FI_CODE_IN                     IN VARCHAR2,
      BRANCH_CODE_IN                 IN VARCHAR2,
      FI_SUBJECT_CODE_IN             IN VARCHAR2,
      FI_CONTRACT_CODE_IN            IN VARCHAR2,
      CONTRACT_TYPE_IN               IN VARCHAR2,
      CONTRACT_PHASE_IN              IN VARCHAR2,
      CONTRACT_STATUS_IN             IN VARCHAR2,
      CURRENCY_CODE_IN               IN VARCHAR2,
      STARTING_DATE_IN               IN DATE,
      REQUEST_DATE_IN                IN DATE,
      PLANNED_END_DATE_IN            IN DATE,
      ACTUAL_END_DATE_IN             IN DATE,
      DEFAULTER_STATUS_IN            IN VARCHAR2,
      DATE_LAST_PAYMENT_IN           IN DATE,
      SUBSIDIZED_CREDIT_IN           IN VARCHAR2,
      PRE_FINANCE_OF_LOAN_IN         IN VARCHAR2,
      REORGANIZED_CREDIT_IN          IN VARCHAR2,
      THIRD_PARTY_GUARANTEE_TYPE_IN  IN VARCHAR2,
      SECURITY_TYPE_IN               IN VARCHAR2,
      AMOUNT_GUARANTEED_3RD_PARTY_IN IN NUMBER,
      AMOUNT_GUARANTEED_SECURITY_IN  IN NUMBER,
      QUALITATIVE_JUDGEMENT_IN       IN VARCHAR2,
      PERIODICITY_PAYMENT_IN         IN VARCHAR2,
      METHOD_OF_PAYMENT_IN           IN VARCHAR2,
      INSTALMENT_AMOUNT_IN           IN NUMBER,
      CREDIT_LIMIT_IN                IN NUMBER,
      TOTAL_OUTSTANDING_AMOUNT_IN    IN NUMBER,
      EXPIRATION_DATE_NEXT_INST_IN   IN DATE,
      REMAINING_AMOUNT_IN            IN NUMBER,
      NUMBER_OF_OVERDUE_IN           IN NUMBER,
      OVERDUE_AMOUNT_IN              IN NUMBER,
      DATE_OF_LAST_CHARGE_IN         IN DATE,
      TYPE_OF_INSTALMENT_IN          IN VARCHAR2,
      NO_OF_DAYS_PAYMENT_DELAY_IN    IN NUMBER,
      DUE_FOR_RECOVERY_IN            IN NUMBER,
      RECOVERY_DURING_REPORTING_IN   IN NUMBER,
      CUMULATIVE_RECOVERY_IN         IN NUMBER,
      DATE_OF_LAW_SUIT_IN            IN DATE,
      ECONOMIC_PURPOSE_CODE_IN       IN VARCHAR2,
      MAKE_BY_IN                     IN VARCHAR2,
      MAKE_DATE_IN                   IN DATE,
      RECORD_STATUS_IN               IN VARCHAR2,
      IN_DATE_OF_CLASSIFICATION      IN DATE)
  AS
    L_RECORD_STATUS VARCHAR2(1);
  BEGIN
    SELECT RECORD_STATUS INTO L_RECORD_STATUS FROM CARD_CONTRACTS WHERE FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;

    IF L_RECORD_STATUS != 'R' AND L_RECORD_STATUS != 'T' THEN
      SP_CARD_CONTRACT_HIST_INSERT(FI_CONTRACT_CODE_IN);
      UPDATE
        CARD_CONTRACTS
      SET
        RECORD_TYPE                   = RECORD_TYPE_IN,
        FI_CODE                       = FI_CODE_IN,
        BRANCH_CODE                   = DECODE(BRANCH_CODE_IN,'0000',BRANCH_CODE,BRANCH_CODE_IN),
        FI_SUBJECT_CODE               = FI_SUBJECT_CODE_IN,
        CONTRACT_TYPE                 = CONTRACT_TYPE_IN,
        CONTRACT_PHASE                = CONTRACT_PHASE_IN,
        CONTRACT_STATUS               = CONTRACT_STATUS_IN,
        CURRENCY_CODE                 = CURRENCY_CODE_IN,
        STARTING_DATE                 = STARTING_DATE_IN,
        REQUEST_DATE                  = REQUEST_DATE_IN,
        PLANNED_END_DATE              = PLANNED_END_DATE_IN,
        ACTUAL_END_DATE               = ACTUAL_END_DATE_IN,
        DEFAULTER_STATUS              = DEFAULTER_STATUS_IN,
        DATE_LAST_PAYMENT             = DATE_LAST_PAYMENT_IN,
        SUBSIDIZED_CREDIT             = SUBSIDIZED_CREDIT_IN,
        PRE_FINANCE_OF_LOAN           = PRE_FINANCE_OF_LOAN_IN,
        REORGANIZED_CREDIT            = REORGANIZED_CREDIT_IN,
        THIRD_PARTY_GUARANTEE_TYPE    = THIRD_PARTY_GUARANTEE_TYPE_IN,
        SECURITY_TYPE                 = SECURITY_TYPE_IN,
        AMOUNT_GUARANTEED_THIRD_PARTY = AMOUNT_GUARANTEED_3RD_PARTY_IN,
        AMOUNT_GUARANTEED_SECURITY    = AMOUNT_GUARANTEED_SECURITY_IN,
        QUALITATIVE_JUDGEMENT         = QUALITATIVE_JUDGEMENT_IN,
        PERIODICITY_PAYMENT           = PERIODICITY_PAYMENT_IN,
        METHOD_OF_PAYMENT             = METHOD_OF_PAYMENT_IN,
        INSTALMENT_AMOUNT             = INSTALMENT_AMOUNT_IN,
        CREDIT_LIMIT                  = CREDIT_LIMIT_IN,
        TOTAL_OUTSTANDING_AMOUNT      = TOTAL_OUTSTANDING_AMOUNT_IN,
        EXPIRATION_DATE_NEXT_INST     = EXPIRATION_DATE_NEXT_INST_IN,
        REMAINING_AMOUNT              = REMAINING_AMOUNT_IN,
        NUMBER_OF_OVERDUE             = NUMBER_OF_OVERDUE_IN,
        OVERDUE_AMOUNT                = OVERDUE_AMOUNT_IN,
        DATE_OF_LAST_CHARGE           = DATE_OF_LAST_CHARGE_IN,
        TYPE_OF_INSTALMENT            = TYPE_OF_INSTALMENT_IN,
        NO_OF_DAYS_PAYMENT_DELAY      = NO_OF_DAYS_PAYMENT_DELAY_IN,
        DUE_FOR_RECOVERY              = DUE_FOR_RECOVERY_IN,
        RECOVERY_DURING_REPORTING     = RECOVERY_DURING_REPORTING_IN,
        CUMULATIVE_RECOVERY           = CUMULATIVE_RECOVERY_IN,
        DATE_OF_LAW_SUIT              = DATE_OF_LAW_SUIT_IN,
        ECONOMIC_PURPOSE_CODE         = ECONOMIC_PURPOSE_CODE_IN,
        MAKE_BY                       = MAKE_BY_IN,
        MAKE_DATE                     = SYSDATE,
        RECORD_STATUS                 = RECORD_STATUS_IN,
        DATE_OF_CLASSIFICATION        = IN_DATE_OF_CLASSIFICATION
      WHERE
        FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
    END IF;
  END SP_CARD_CONTRACT_UPDATE;
  PROCEDURE SP_CONTRACT_LINK_INSERT(
      RECORD_TYPE_IN       VARCHAR2,
      FI_CODE_IN           VARCHAR2,
      BRANCH_CODE_IN       VARCHAR2,
      TYPE_OF_LINK_IN      VARCHAR2,
      FI_PRIMARY_CODE_IN   VARCHAR2,
      FI_SECONDARY_CODE_IN VARCHAR2,
      FI_CONTRACT_CODE_IN  VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE,
      RECORD_STATUS_IN     VARCHAR2)
  AS
    L_EXISTS INT;
  BEGIN
    SELECT
      COUNT(1)
    INTO
      L_EXISTS
    FROM
      CONTRACT_LINKS A
    WHERE
      A.FI_CONTRACT_CODE    = FI_CONTRACT_CODE_IN
    AND A.FI_SECONDARY_CODE = FI_SECONDARY_CODE_IN;
    IF L_EXISTS            IS NULL OR L_EXISTS = 0 THEN
      INSERT
      INTO
        CONTRACT_LINKS
        (
          RECORD_TYPE,
          FI_CODE,
          BRANCH_CODE,
          TYPE_OF_LINK,
          FI_PRIMARY_CODE,
          FI_SECONDARY_CODE,
          FI_CONTRACT_CODE,
          MAKE_BY,
          MAKE_DATE,
          RECORD_STATUS
        )
        VALUES
        (
          RECORD_TYPE_IN,
          FI_CODE_IN,
          BRANCH_CODE_IN,
          TYPE_OF_LINK_IN,
          FI_PRIMARY_CODE_IN,
          FI_SECONDARY_CODE_IN,
          FI_CONTRACT_CODE_IN,
          MAKE_BY_IN,
          SYSDATE,
          RECORD_STATUS_IN
        );
    ELSE
      SP_CONTRACT_LINK_UPDATE( RECORD_TYPE_IN, FI_CODE_IN, BRANCH_CODE_IN, TYPE_OF_LINK_IN, FI_PRIMARY_CODE_IN,
      FI_SECONDARY_CODE_IN, FI_CONTRACT_CODE_IN, MAKE_BY_IN, MAKE_DATE_IN, 'U' );
    END IF;
  END SP_CONTRACT_LINK_INSERT;
  PROCEDURE SP_CONTRACT_LINK_HIST_INSERT
    (
      FI_CONTRACT_CODE_IN  IN VARCHAR2,
      FI_SECONDARY_CODE_IN IN VARCHAR2
    )
  AS
    L_VERSION_NO NUMBER
    (
      10
    )
    ;
  BEGIN
    SELECT
      MAX(VERSION_NO)+1
    INTO
      L_VERSION_NO
    FROM
      CONTRACT_LINKS_HIST A
    WHERE
      A.FI_CONTRACT_CODE    = FI_CONTRACT_CODE_IN
    AND A.FI_SECONDARY_CODE = FI_SECONDARY_CODE_IN;
    IF L_VERSION_NO        IS NULL THEN
      L_VERSION_NO         :=1;
    END IF;
    INSERT
    INTO
      CONTRACT_LINKS_HIST
    SELECT
      L_VERSION_NO,
      SYSDATE,
      A.*
    FROM
      CONTRACT_LINKS A
    WHERE
      A.FI_CONTRACT_CODE    = FI_CONTRACT_CODE_IN
    AND A.FI_SECONDARY_CODE = FI_SECONDARY_CODE_IN;
  END SP_CONTRACT_LINK_HIST_INSERT;
  PROCEDURE SP_CONTRACT_LINK_UPDATE(
      RECORD_TYPE_IN       VARCHAR2,
      FI_CODE_IN           VARCHAR2,
      BRANCH_CODE_IN       VARCHAR2,
      TYPE_OF_LINK_IN      VARCHAR2,
      FI_PRIMARY_CODE_IN   VARCHAR2,
      FI_SECONDARY_CODE_IN VARCHAR2,
      FI_CONTRACT_CODE_IN  VARCHAR2,
      MAKE_BY_IN           VARCHAR2,
      MAKE_DATE_IN         DATE,
      RECORD_STATUS_IN     VARCHAR2 )
  AS
  P_RECORD_STATUS VARCHAR2(1);
  BEGIN
    SELECT RECORD_STATUS INTO P_RECORD_STATUS FROM CONTRACT_LINKS WHERE FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN AND FI_SECONDARY_CODE = FI_SECONDARY_CODE_IN;
    IF P_RECORD_STATUS != 'R' THEN
      SP_CONTRACT_LINK_HIST_INSERT(FI_CONTRACT_CODE_IN,FI_SECONDARY_CODE_IN);
      UPDATE
        CONTRACT_LINKS
      SET
        RECORD_TYPE     = RECORD_TYPE_IN,
        FI_CODE         = FI_CODE_IN,
        BRANCH_CODE     = DECODE(BRANCH_CODE_IN,'0000',BRANCH_CODE,BRANCH_CODE_IN),
        TYPE_OF_LINK    = TYPE_OF_LINK_IN,
        FI_PRIMARY_CODE = NVL(FI_PRIMARY_CODE_IN, FI_PRIMARY_CODE),
        MAKE_BY         = MAKE_BY_IN,
        MAKE_DATE       = SYSDATE ,
        RECORD_STATUS   = RECORD_STATUS_IN
      WHERE
        FI_CONTRACT_CODE    = FI_CONTRACT_CODE_IN
      AND FI_SECONDARY_CODE = FI_SECONDARY_CODE_IN;
    END IF;
  END SP_CONTRACT_LINK_UPDATE;
  PROCEDURE SP_GET_INSTALMENT_CONTRACT(
      CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT A.RECORD_TYPE,
    A.FI_CODE,
    A.BRANCH_CODE,
    A.FI_SUBJECT_CODE,
    B.SUBJECT_NAME BORROWER_NAME,
    A.FI_CONTRACT_CODE,
    A.CONTRACT_TYPE,
    A.CONTRACT_PHASE,
    A.CONTRACT_STATUS,
    A.CURRENCY_CODE,
    A.STARTING_DATE,
    A.REQUEST_DATE,
    A.PLANNED_END_DATE,
    A.ACTUAL_END_DATE,
    A.DEFAULTER_STATUS,
    A.LAST_PAYMENT_DATE,
    A.SUBSIDIZED_CREDIT,
    A.PRE_FINANCE_LOAN,
    A.REORGANIZED_CREDIT,
    A.THIRD_PARTY_GUARANTEE_TYPE,
    A.SECURITY_TYPE,
    A.AMOUNT_GURANTEED_THIRD_PARTY,
    A.AMOUNT_GUARANTEED_SECURITY,
    A.QUALIFICATION_JUDGEMENT,
    A.SANCTION_LIMIT,
    A.TOTAL_DISBURSED_AMOUNT,
    A.TOTAL_OUTSTANDING_AMOUNT,
    A.TOTAL_NUMBER_INSTALMENTS,
    A.PERIODICITY_PAYMENT,
    A.METHOD_PAYMENT,
    A.INSTALMENT_AMOUNT,
    A.EXPIRATION_DATE_NEXT_INST,
    A.AMOUNT_NEXT_EXPIRING_INST,
    A.NO_OF_REMAINING_INSTALMENT,
    A.REMAINING_AMOUNT,
    A.NO_OF_OVERDUE_INSTALMENT,
    A.OVERDUE_AMOUNT,
    A.NO_OF_DAYS_PAYMENT_DELAY,
    A.TYPE_OF_LEASED_GOOD,
    A.VALUE_OF_LEASED_GOOD,
    A.REGISTRATION_NUMBER,
    A.DATE_OF_MANUFACTURING,
    A.DUE_FOR_RECOVERY,
    A.RECOVERY_DURING_REPORTING,
    A.CUMULATIVE_RECOVERY,
    A.DATE_OF_LAW_SUIT,
    A.DATE_OF_CLASSIFICATION,
    A.NO_TIMES_RESCHEDULING,
    A.DATE_LAST_RESCHEDULING,
    A.ECONOMIC_PURPOSE_CODE,
    A.SME,
    A.ENTERPRISE_TYPE,
    A.MAKE_BY,
    A.MAKE_DATE,
    A.UBS_ACCOUNT_NO,
    A.RECORD_STATUS FROM INSTALMENT_CONTRACTS A JOIN VW_SUBJECTS B ON A.FI_SUBJECT_CODE = B.FI_SUBJECT_CODE WHERE
    A.FI_CONTRACT_CODE                                                                  =CONTRACT_CODE;
  END SP_GET_INSTALMENT_CONTRACT;
  PROCEDURE SP_GET_INST_CONTRACTS_FILTERED(
      SUBJECT_CODE_IN  IN VARCHAR2,
      BRANCH_CODE_IN   IN VARCHAR2,
      CONTRACT_CODE_IN IN VARCHAR2,
      CONTRACT_PHASE_IN IN VARCHAR2,
      UBS_AC_NO_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT BRANCH_CODE,
    A.FI_SUBJECT_CODE,
    F.SUBJECT_NAME BORROWER_NAME,
    FI_CONTRACT_CODE,
    B.NAME CONTRACT_TYPE,
    C.NAME CONTRACT_PHASE,
    D.NAME CONTRACT_STATUS,
    CURRENCY_CODE,
    DEFAULTER_STATUS,
    SANCTION_LIMIT,
    TOTAL_DISBURSED_AMOUNT,
    TOTAL_OUTSTANDING_AMOUNT,
    TOTAL_NUMBER_INSTALMENTS,
    E.NAME PERIODICITY_PAYMENT,
    A.RECORD_STATUS
    FROM
        INSTALMENT_CONTRACTS A JOIN LOV_CONTRACT_TYPES B ON A.CONTRACT_TYPE = B.CODE
        JOIN LOV_CONTRACT_PHASES C ON A.CONTRACT_PHASE = C.CODE
        JOIN LOV_CONTRACT_STATUS D ON A.CONTRACT_STATUS = D.CODE
        JOIN LOV_PERIODICITY_OF_PAYMENT E ON A.PERIODICITY_PAYMENT = E.CODE
        JOIN VW_SUBJECTS F ON A.FI_SUBJECT_CODE = F.FI_SUBJECT_CODE
    WHERE
        A.RECORD_STATUS != 'D'
    AND A.FI_SUBJECT_CODE = NVL ( SUBJECT_CODE_IN, A.FI_SUBJECT_CODE )
    AND BRANCH_CODE = NVL ( BRANCH_CODE_IN, BRANCH_CODE )
    AND FI_CONTRACT_CODE = NVL ( CONTRACT_CODE_IN, FI_CONTRACT_CODE )
    AND NVL(UBS_ACCOUNT_NO, 'EMPTY') = NVL (UBS_AC_NO_IN, NVL(UBS_ACCOUNT_NO, 'EMPTY'))
    AND A.CONTRACT_PHASE = NVL(CONTRACT_PHASE_IN, CONTRACT_PHASE);
  END SP_GET_INST_CONTRACTS_FILTERED;
  PROCEDURE SP_GET_NON_INSTALMENT_CONTRACT(
      CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT A.RECORD_TYPE,
    A.FI_CODE,
    A.BRANCH_CODE,
    A.FI_SUBJECT_CODE,
    B.SUBJECT_NAME BORROWER_NAME,
    A.FI_CONTRACT_CODE,
    A.CONTRACT_TYPE,
    A.CONTRACT_PHASE,
    A.CONTRACT_STATUS,
    A.CURRENCY_CODE,
    A.STARTING_DATE,
    A.REQUEST_DATE,
    A.PLANNED_END_DATE,
    A.ACTUAL_END_DATE,
    A.DEFAULTER_STATUS,
    A.DATE_OF_LAST_PAYMENT,
    A.SUBSIDIZED_CREDIT,
    A.PRE_FINANCE_LOAN,
    A.REORGANIZED_CREDIT,
    A.THIRD_PARTY_GUARANTEE_TYPE,
    A.SECURITY_TYPE,
    A.AMOUNT_GUARANTEED_THIRD_PARTY,
    A.AMOUNT_GUARANTEED_SECURITY,
    A.QUALITATIVE_JUDGEMENT,
    A.SANCTION_LIMIT,
    A.TOTAL_OUTSTANDING_AMOUNT,
    A.NO_OF_DAYS_PAYMENT_DELAY,
    A.DUE_FOR_RECOVERY,
    A.RECOVERY_DURING_REPORTING,
    A.CUMULATIVE_RECOVERY,
    A.DATE_OF_LAW_SUIT,
    A.DATE_OF_CLASSIFICATION,
    A.NO_OF_TIMES_RESCHEDULING,
    A.DATE_LAST_RESCHEDULING,
    A.ECONOMIC_PURPOSE_CODE,
    A.SME,
    A.ENTERPRISE_TYPE,
    A.MAKE_BY,
    A.MAKE_DATE,
    A.UBS_ACCOUNT_NO,
    A.RECORD_STATUS FROM NON_INSTALMENT_CONTRACTS A JOIN VW_SUBJECTS B ON A.FI_SUBJECT_CODE = B.FI_SUBJECT_CODE WHERE
    A.FI_CONTRACT_CODE                                                                      =CONTRACT_CODE ;
  END SP_GET_NON_INSTALMENT_CONTRACT;
  PROCEDURE SP_GET_NON_INST_CONTRACTS_FLTR(
      SUBJECT_CODE_IN  IN VARCHAR2,
      BRANCH_CODE_IN   IN VARCHAR2,
      CONTRACT_CODE_IN IN VARCHAR2,
      CONTRACT_PHASE_IN IN VARCHAR2,
      UBS_AC_NO_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT BRANCH_CODE,
    A.FI_SUBJECT_CODE,
    F.SUBJECT_NAME BORROWER_NAME,
    FI_CONTRACT_CODE,
    B.NAME CONTRACT_TYPE,
    C.NAME CONTRACT_PHASE,
    D.NAME CONTRACT_STATUS,
    CURRENCY_CODE,
    DEFAULTER_STATUS,
    SANCTION_LIMIT,
    TOTAL_OUTSTANDING_AMOUNT,
    A.RECORD_STATUS
    FROM
        NON_INSTALMENT_CONTRACTS A
        JOIN LOV_CONTRACT_TYPES B ON A.CONTRACT_TYPE = B.CODE
        JOIN LOV_CONTRACT_PHASES C ON A.CONTRACT_PHASE = C.CODE
        JOIN LOV_CONTRACT_STATUS D ON A.CONTRACT_STATUS = D.CODE
        JOIN VW_SUBJECTS F ON A.FI_SUBJECT_CODE = F.FI_SUBJECT_CODE
    WHERE
        A.RECORD_STATUS != 'D'
    AND A.FI_SUBJECT_CODE = NVL ( SUBJECT_CODE_IN, A.FI_SUBJECT_CODE )
    AND BRANCH_CODE = NVL ( BRANCH_CODE_IN, BRANCH_CODE )
    AND FI_CONTRACT_CODE = NVL ( CONTRACT_CODE_IN, FI_CONTRACT_CODE )
    AND NVL(UBS_ACCOUNT_NO, 'EMPTY') = NVL (UBS_AC_NO_IN, NVL(UBS_ACCOUNT_NO, 'EMPTY'))
    AND A.CONTRACT_PHASE = NVL(CONTRACT_PHASE_IN, A.CONTRACT_PHASE);
  END SP_GET_NON_INST_CONTRACTS_FLTR;
  PROCEDURE SP_GET_CARD_CONTRACT(
      CONTRACT_CODE IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT A.RECORD_TYPE,
    A.FI_CODE,
    A.BRANCH_CODE,
    A.FI_SUBJECT_CODE,
    B.SUBJECT_NAME BORROWER_NAME,
    A.FI_CONTRACT_CODE,
    A.CONTRACT_TYPE,
    A.CONTRACT_PHASE,
    A.CONTRACT_STATUS,
    A.CURRENCY_CODE,
    A.STARTING_DATE,
    A.REQUEST_DATE,
    A.PLANNED_END_DATE,
    A.ACTUAL_END_DATE,
    A.DEFAULTER_STATUS,
    A.DATE_LAST_PAYMENT,
    A.SUBSIDIZED_CREDIT,
    A.PRE_FINANCE_OF_LOAN,
    A.REORGANIZED_CREDIT,
    A.THIRD_PARTY_GUARANTEE_TYPE,
    A.SECURITY_TYPE,
    A.AMOUNT_GUARANTEED_THIRD_PARTY,
    A.AMOUNT_GUARANTEED_SECURITY,
    A.QUALITATIVE_JUDGEMENT,
    A.PERIODICITY_PAYMENT,
    A.METHOD_OF_PAYMENT,
    A.INSTALMENT_AMOUNT,
    A.CREDIT_LIMIT,
    A.TOTAL_OUTSTANDING_AMOUNT,
    A.EXPIRATION_DATE_NEXT_INST,
    A.REMAINING_AMOUNT,
    A.NUMBER_OF_OVERDUE,
    A.OVERDUE_AMOUNT,
    A.DATE_OF_LAST_CHARGE,
    A.TYPE_OF_INSTALMENT,
    A.NO_OF_DAYS_PAYMENT_DELAY,
    A.DUE_FOR_RECOVERY,
    A.RECOVERY_DURING_REPORTING,
    A.CUMULATIVE_RECOVERY,
    A.DATE_OF_LAW_SUIT,
    A.ECONOMIC_PURPOSE_CODE,
    A.MAKE_BY,
    A.MAKE_DATE,
    A.RECORD_STATUS,
    A.DATE_OF_CLASSIFICATION FROM CARD_CONTRACTS A JOIN VW_SUBJECTS B ON A.FI_SUBJECT_CODE = B.FI_SUBJECT_CODE WHERE
    A.FI_CONTRACT_CODE                                                            = CONTRACT_CODE ;
  END SP_GET_CARD_CONTRACT;
  PROCEDURE SP_GET_CONTRACT_LINKS_FILTERED(
      BRANCH_CODE_IN    IN VARCHAR2,
      PRIMARY_CODE_IN   IN VARCHAR2,
      PRIMARY_NAME_IN   IN VARCHAR2,
      SECONDARY_CODE_IN IN VARCHAR2,
      SECONDARY_NAME_IN IN VARCHAR2,
      CONTRACT_CODE_IN  IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT A.BRANCH_CODE,
    D.NAME TYPE_OF_LINK,
    A.FI_PRIMARY_CODE,
    B.SUBJECT_NAME PRIMARY_NAME,
    A.FI_SECONDARY_CODE,
    C.SUBJECT_NAME SECONDARY_NAME,
    A.FI_CONTRACT_CODE,
    E.CONTRACT_CATEGORY,
    A.RECORD_STATUS FROM CONTRACT_LINKS A JOIN VW_SUBJECTS B ON A.FI_PRIMARY_CODE = B.FI_SUBJECT_CODE JOIN VW_SUBJECTS C
    ON A.FI_SECONDARY_CODE                                                      = C.FI_SUBJECT_CODE JOIN LOV_LINK_TYPES
    D ON A.TYPE_OF_LINK                                                         = D.CODE JOIN VW_CONTRACTS E ON
    A.FI_CONTRACT_CODE                                                          = E.FI_CONTRACT_CODE
    WHERE
    A.RECORD_STATUS != 'D'
    AND A.BRANCH_CODE = NVL(BRANCH_CODE_IN, A.BRANCH_CODE)
    AND FI_PRIMARY_CODE = NVL(PRIMARY_CODE_IN, FI_PRIMARY_CODE )
    AND FI_SECONDARY_CODE = NVL(SECONDARY_CODE_IN, FI_SECONDARY_CODE)
    AND A.FI_CONTRACT_CODE = NVL(CONTRACT_CODE_IN, A.FI_CONTRACT_CODE)
    AND LOWER(B.SUBJECT_NAME) LIKE NVL('%' ||PRIMARY_NAME_IN ||'%','%') AND LOWER(C.SUBJECT_NAME) LIKE NVL('%' || SECONDARY_NAME_IN ||'%','%') ;
  END SP_GET_CONTRACT_LINKS_FILTERED;
  PROCEDURE SP_GET_CARD_CONTRACTS_FILTERED(
      SUBJECT_CODE_IN  IN VARCHAR2,
      BRANCH_CODE_IN   IN VARCHAR2,
      CONTRACT_CODE_IN IN VARCHAR2,
      CONTRACT_PHASE_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT BRANCH_CODE,
    A.FI_SUBJECT_CODE,
    F.SUBJECT_NAME BORROWER_NAME,
    FI_CONTRACT_CODE,
    B.NAME CONTRACT_TYPE,
    C.NAME CONTRACT_PHASE,
    E.NAME CONTRACT_STATUS,
    CURRENCY_CODE,
    DEFAULTER_STATUS,
    CREDIT_LIMIT,
    TOTAL_OUTSTANDING_AMOUNT,
    TYPE_OF_INSTALMENT,
    A.RECORD_STATUS
    FROM
        CARD_CONTRACTS A
        JOIN LOV_CONTRACT_TYPES B ON A.CONTRACT_TYPE = B.CODE
        JOIN LOV_CONTRACT_PHASES C ON A.CONTRACT_PHASE = C.CODE
        JOIN LOV_CONTRACT_STATUS D ON A.CONTRACT_STATUS = D.CODE
        JOIN LOV_INSTALMENT_TYPES E ON A.TYPE_OF_INSTALMENT = E.CODE
        JOIN VW_SUBJECTS F ON A.FI_SUBJECT_CODE = F.FI_SUBJECT_CODE
    WHERE
        A.RECORD_STATUS != 'D'
    AND A.FI_SUBJECT_CODE = NVL (SUBJECT_CODE_IN, A.FI_SUBJECT_CODE)
    AND BRANCH_CODE = NVL ( BRANCH_CODE_IN,BRANCH_CODE)
    AND FI_CONTRACT_CODE = NVL ( CONTRACT_CODE_IN,FI_CONTRACT_CODE )
    AND A.CONTRACT_PHASE = NVL(CONTRACT_PHASE_IN, A.CONTRACT_PHASE);
  END SP_GET_CARD_CONTRACTS_FILTERED;
  PROCEDURE SP_CARD_CONTRACT_FLAG_DELETE(
      FI_CONTRACT_CODE_IN VARCHAR2,
      MAKE_BY_IN   IN VARCHAR2,
      MAKE_DATE_IN IN DATE)
  AS
  BEGIN
    SP_CARD_CONTRACT_HIST_INSERT(FI_CONTRACT_CODE_IN);
    UPDATE
      CARD_CONTRACTS
    SET
      RECORD_STATUS ='D',
      MAKE_BY       =MAKE_BY_IN,
      MAKE_DATE     =SYSDATE
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
  END SP_CARD_CONTRACT_FLAG_DELETE;
  PROCEDURE SP_INST_CONTRACT_FLAG_DELETE(
      FI_CONTRACT_CODE_IN VARCHAR2,
      MAKE_BY_IN   IN VARCHAR2,
      MAKE_DATE_IN IN DATE)
  AS
  BEGIN
    SP_INST_CONTRACT_HIST_INSERT(FI_CONTRACT_CODE_IN);
    UPDATE
      INSTALMENT_CONTRACTS
    SET
      RECORD_STATUS ='D',
      MAKE_BY       =MAKE_BY_IN,
      MAKE_DATE     =SYSDATE
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
  END SP_INST_CONTRACT_FLAG_DELETE;
  PROCEDURE SP_N_INST_CONTRACT_FLAG_DELETE(
      FI_CONTRACT_CODE_IN VARCHAR2,
      MAKE_BY_IN   IN VARCHAR2,
      MAKE_DATE_IN IN DATE)
  AS
  BEGIN
    SP_NON_INST_CONTRACT_HIST_INS(FI_CONTRACT_CODE_IN);
    UPDATE
      NON_INSTALMENT_CONTRACTS
    SET
      RECORD_STATUS ='D',
      MAKE_BY       =MAKE_BY_IN,
      MAKE_DATE     =SYSDATE
    WHERE
      FI_CONTRACT_CODE = FI_CONTRACT_CODE_IN;
  END SP_N_INST_CONTRACT_FLAG_DELETE;
  PROCEDURE SP_CONTRACT_LINK_FLAG_DELETE(
      FI_CONTRACT_CODE_IN  IN VARCHAR2,
      FI_SECONDARY_CODE_IN IN VARCHAR2,
      MAKE_BY_IN   VARCHAR2,
      MAKE_DATE_IN DATE)
  AS
  BEGIN
    SP_CONTRACT_LINK_HIST_INSERT(FI_CONTRACT_CODE_IN,FI_SECONDARY_CODE_IN);
    UPDATE
      CONTRACT_LINKS
    SET
      RECORD_STATUS = 'D',
      MAKE_BY       = MAKE_BY_IN,
      MAKE_DATE     = SYSDATE
    WHERE
      FI_CONTRACT_CODE    = FI_CONTRACT_CODE_IN
    AND FI_SECONDARY_CODE = FI_SECONDARY_CODE_IN;
  END SP_CONTRACT_LINK_FLAG_DELETE;

  PROCEDURE SP_GET_INSTALMENT_CONTRACT_REPORT(
      CONTRACT_CODE IN VARCHAR2,
      REPORT_PERIOD IN DATE,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
     OPEN REF_CURSOR FOR SELECT A.REPORTING_PERIOD,A.FI_CONTRACT_CODE FROM INSTALMENT_CONTRACT_REPORT A 
    WHERE A.FI_CONTRACT_CODE= CONTRACT_CODE and TO_DATE(A.REPORTING_PERIOD,'DD/MM/YYYY')=TO_DATE(REPORT_PERIOD,'DD/MM/YYYY');
  END SP_GET_INSTALMENT_CONTRACT_REPORT;
  
  PROCEDURE SP_GET_NONINSTALMENT_CONTRACT_REPORT(
      CONTRACT_CODE IN VARCHAR2,
       REPORT_PERIOD IN DATE,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
     OPEN REF_CURSOR FOR SELECT A.REPORTING_PERIOD,A.FI_CONTRACT_CODE FROM NON_INSTALMENT_CONTRACT_REPORT A 
    WHERE A.FI_CONTRACT_CODE= CONTRACT_CODE and TO_DATE(A.REPORTING_PERIOD,'DD/MM/YYYY')=TO_DATE(REPORT_PERIOD,'DD/MM/YYYY'); 
  END SP_GET_NONINSTALMENT_CONTRACT_REPORT;
  
  PROCEDURE SP_GET_PERSONAL_DATA_REPORT(
      SUBJECT_CODE IN VARCHAR2,
       REPORT_PERIOD IN DATE,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
     OPEN REF_CURSOR FOR SELECT A.REPORTING_PERIOD,A.FI_SUBJECT_CODE FROM PERSONAL_DATA_REPORT A 
    WHERE A.FI_SUBJECT_CODE= SUBJECT_CODE AND TO_DATE(A.REPORTING_PERIOD,'DD/MM/YYYY')=TO_DATE(REPORT_PERIOD,'DD/MM/YYYY'); 
  END SP_GET_PERSONAL_DATA_REPORT;
  
  PROCEDURE SP_GET_INSTITUTION_REPORT(
      SUBJECT_CODE IN VARCHAR2,
       REPORT_PERIOD IN DATE,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
     OPEN REF_CURSOR FOR SELECT A.REPORTING_PERIOD,A.FI_SUBJECT_CODE FROM INSTITUTION_REPORT A 
    WHERE A.FI_SUBJECT_CODE= SUBJECT_CODE AND TO_DATE(A.REPORTING_PERIOD,'DD/MM/YYYY')=TO_DATE(REPORT_PERIOD,'DD/MM/YYYY'); 
  END SP_GET_INSTITUTION_REPORT;
  
END PKG_CONTRACT;
