CREATE OR REPLACE PACKAGE PKG_REPORT AS

  PROCEDURE SP_ACCS_READY_TO_REPORT(
    IN_CIB_BRANCH_CODE IN VARCHAR2,
    IN_CONTRACT_PHASE IN VARCHAR2,
    IN_CONTRACT_STATUS in VARCHAR2,
    REF_CURSOR OUT SYS_REFCURSOR);

  PROCEDURE SP_NEED_TOBE_REPORTED(
    IN_CIB_BRANCH_CODE IN VARCHAR2,
    REF_CURSOR OUT SYS_REFCURSOR);

END PKG_REPORT;

