CREATE OR REPLACE PACKAGE PKG_LOV AS 

  PROCEDURE SP_3RD_PARTY_GUARANTEE_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_CONTRACT_PHASES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_CONTRACT_STATUS(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_CONTRACT_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_CONTRACT_TYPES_INST(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_CONTRACT_TYPES_CARD(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_CONTRACT_TYPES_NONINST(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_COUNTRIES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_CURRENCIES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_ECONOMIC_PURPOSE_CODES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_ENTERPRISE_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GENDER(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_ID_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_INSTALMENT_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_INSTITUTION_LEGAL_FORMS(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_LEASED_GOOD_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_LINK_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_NO_OF_DAYS(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_OWNER_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_PAYMENT_METHODS(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_PERIODICITY_OF_PAYMENT(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_PRE_FINANCE_OF_LOAN(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_REORGANIZED_CREDIT(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_SECTOR_CODES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_SECTOR_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_SECURITY_TYPES(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_SUBSIDIZED_CREDIT(REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_DISTRICTS(COUNTRY_CODE_IN IN VARCHAR, REF_CURSOR OUT SYS_REFCURSOR); 
  PROCEDURE SP_SUB_REGISTRY_OFFICES(IN_DISTRICT IN VARCHAR, REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_THANAS(IN_DISTRICT IN VARCHAR, REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_MOUZAS(IN_DISTRICT IN VARCHAR, REF_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_DEED_TYPES(REF_CURSOR OUT SYS_REFCURSOR);

END PKG_LOV;

 
