CREATE OR REPLACE PACKAGE BODY PKG_SUBJECT 
AS
  PROCEDURE SP_PERSON_INSERT(
      IN_RECORD_TYPE                   IN VARCHAR2 ,
      IN_FI_CODE                       IN VARCHAR2 ,
      IN_BRANCH_CODE                   IN VARCHAR2 ,
      IN_FI_SUBJECT_CODE               IN VARCHAR2 ,
      IN_TITLE                         IN VARCHAR2 ,
      IN_NAME                          IN VARCHAR2 ,
      IN_FATHERS_TITLE                 IN VARCHAR2 ,
      IN_FATHERS_NAME                  IN VARCHAR2 ,
      IN_MOTHERS_TITLE                 IN VARCHAR2 ,
      IN_MOTHERS_NAME                  IN VARCHAR2 ,
      IN_SPOUSES_TITLE                 IN VARCHAR2 ,
      IN_SPOUSES_NAME                  IN VARCHAR2 ,
      IN_SECTOR_TYPE                   IN NUMBER ,
      IN_SECTOR_CODE                   IN NUMBER ,
      IN_GENDER                        IN VARCHAR2 ,
      IN_DATE_OF_BIRTH                 IN DATE ,
      IN_PLACE_OF_BIRTH                IN VARCHAR2 ,
      IN_COUNTRY_OF_BIRTH              IN VARCHAR2 ,
      IN_NATIONAL_ID_NUMBER            IN VARCHAR2 ,
      IN_NATIONAL_ID_AVAILABLE         IN NUMBER ,
      IN_TIN                           IN VARCHAR2 ,
      IN_PERMANENT_ADDRESS_STREET      IN VARCHAR2 ,
      IN_PERMANENT_ADDRESS_POSTAL_CD IN NUMBER ,
      IN_PERMANENT_ADDRESS_DISTRICT    IN VARCHAR2 ,
      IN_PERMANENT_ADDRESS_COUNTRY     IN VARCHAR2 ,
      IN_PRESENT_ADDRESS_STREET        IN VARCHAR2 ,
      IN_PRESENT_ADDRESS_POSTAL_CODE   IN NUMBER ,
      IN_PRESENT_ADDRESS_DISTRICT      IN VARCHAR2 ,
      IN_PRESENT_ADDRESS_COUNTRY       IN VARCHAR2 ,
      IN_BUSINESS_ADDRESS_STREET       IN VARCHAR2 ,
      IN_BUSINESS_ADDRESS_POSTAL_CD  IN NUMBER ,
      IN_BUSINESS_ADDRESS_DISTRICT     IN VARCHAR2 ,
      IN_BUSINESS_ADDRESS_COUNTRY      IN VARCHAR2 ,
      IN_ID_TYPE                       IN VARCHAR2 ,
      IN_ID_NUMBER                     IN VARCHAR2 ,
      IN_ID_ISSUE_DATE                 IN DATE ,
      IN_ID_ISSUE_COUNTRY              IN VARCHAR2 ,
      IN_PHONE_NUMBER                  IN VARCHAR2 ,
      IN_MAKE_BY                       IN VARCHAR2,
      IN_MAKE_DATE                     IN DATE,
      IN_RECORD_STATUS                 IN VARCHAR2,
      IN_CIF_NO                        IN VARCHAR2,
      IN_SMART_ID_NUMBER               IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
    TMP_FI_SUBJECT_CODE VARCHAR2(16);
  BEGIN
    IF IN_FI_SUBJECT_CODE IS NULL THEN
      SELECT
        IN_RECORD_TYPE
        ||IN_FI_CODE
        ||IN_BRANCH_CODE
        ||LPAD(TO_CHAR(SEQ_PERSON.NEXTVAL),8,'0')
      INTO
        TMP_FI_SUBJECT_CODE
      FROM
        DUAL;
      INSERT
      INTO
        PERSONAL_DATA
        (
          RECORD_TYPE,
          FI_CODE,
          BRANCH_CODE,
          FI_SUBJECT_CODE,
          TITLE,
          NAME,
          FATHERS_TITLE,
          FATHERS_NAME,
          MOTHERS_TITLE,
          MOTHERS_NAME,
          SPOUSES_TITLE,
          SPOUSES_NAME,
          SECTOR_TYPE,
          SECTOR_CODE,
          GENDER,
          DATE_OF_BIRTH,
          PLACE_OF_BIRTH,
          COUNTRY_OF_BIRTH,
          NATIONAL_ID_NUMBER,
          NATIONAL_ID_AVAILABLE,
          TIN,
          PERMANENT_ADDRESS_STREET,
          PERMANENT_ADDRESS_POSTAL_CODE,
          PERMANENT_ADDRESS_DISTRICT,
          PERMANENT_ADDRESS_COUNTRY,
          PRESENT_ADDRESS_STREET,
          PRESENT_ADDRESS_POSTAL_CODE,
          PRESENT_ADDRESS_DISTRICT,
          PRESENT_ADDRESS_COUNTRY,
          BUSINESS_ADDRESS_STREET,
          BUSINESS_ADDRESS_POSTAL_CODE,
          BUSINESS_ADDRESS_DISTRICT,
          BUSINESS_ADDRESS_COUNTRY,
          ID_TYPE,
          ID_NUMBER,
          ID_ISSUE_DATE,
          ID_ISSUE_COUNTRY,
          PHONE_NUMBER,
          MAKE_BY,
          MAKE_DATE,
          RECORD_STATUS,
          CIF_NO,
          SMART_ID_NUMBER
        )
        VALUES
        (
          IN_RECORD_TYPE,
          IN_FI_CODE,
          IN_BRANCH_CODE,
          TMP_FI_SUBJECT_CODE,
          IN_TITLE,
          IN_NAME,
          IN_FATHERS_TITLE,
          IN_FATHERS_NAME,
          IN_MOTHERS_TITLE,
          IN_MOTHERS_NAME,
          IN_SPOUSES_TITLE,
          IN_SPOUSES_NAME,
          IN_SECTOR_TYPE,
          IN_SECTOR_CODE,
          IN_GENDER,
          IN_DATE_OF_BIRTH,
          IN_PLACE_OF_BIRTH,
          IN_COUNTRY_OF_BIRTH,
          IN_NATIONAL_ID_NUMBER,
          IN_NATIONAL_ID_AVAILABLE,
          IN_TIN,
          IN_PERMANENT_ADDRESS_STREET,
          IN_PERMANENT_ADDRESS_POSTAL_CD,
          IN_PERMANENT_ADDRESS_DISTRICT,
          IN_PERMANENT_ADDRESS_COUNTRY,
          IN_PRESENT_ADDRESS_STREET,
          IN_PRESENT_ADDRESS_POSTAL_CODE,
          IN_PRESENT_ADDRESS_DISTRICT,
          IN_PRESENT_ADDRESS_COUNTRY,
          IN_BUSINESS_ADDRESS_STREET,
          IN_BUSINESS_ADDRESS_POSTAL_CD,
          IN_BUSINESS_ADDRESS_DISTRICT,
          IN_BUSINESS_ADDRESS_COUNTRY,
          IN_ID_TYPE,
          IN_ID_NUMBER,
          IN_ID_ISSUE_DATE,
          IN_ID_ISSUE_COUNTRY,
          IN_PHONE_NUMBER,
          IN_MAKE_BY,
          sysdate,
          IN_RECORD_STATUS,
          IN_CIF_NO,
          IN_SMART_ID_NUMBER
        ) ;
    ELSE
      SP_PERSON_UPDATE( IN_RECORD_TYPE,
          IN_FI_CODE,
          IN_BRANCH_CODE,
          IN_FI_SUBJECT_CODE,
          IN_TITLE,
          IN_NAME,
          IN_FATHERS_TITLE,
          IN_FATHERS_NAME,
          IN_MOTHERS_TITLE,
          IN_MOTHERS_NAME,
          IN_SPOUSES_TITLE,
          IN_SPOUSES_NAME,
          IN_SECTOR_TYPE,
          IN_SECTOR_CODE,
          IN_GENDER,
          IN_DATE_OF_BIRTH,
          IN_PLACE_OF_BIRTH,
          IN_COUNTRY_OF_BIRTH,
          IN_NATIONAL_ID_NUMBER,
          IN_NATIONAL_ID_AVAILABLE,
          IN_TIN,
          IN_PERMANENT_ADDRESS_STREET,
          IN_PERMANENT_ADDRESS_POSTAL_CD,
          IN_PERMANENT_ADDRESS_DISTRICT,
          IN_PERMANENT_ADDRESS_COUNTRY,
          IN_PRESENT_ADDRESS_STREET,
          IN_PRESENT_ADDRESS_POSTAL_CODE,
          IN_PRESENT_ADDRESS_DISTRICT,
          IN_PRESENT_ADDRESS_COUNTRY,
          IN_BUSINESS_ADDRESS_STREET,
          IN_BUSINESS_ADDRESS_POSTAL_CD,
          IN_BUSINESS_ADDRESS_DISTRICT,
          IN_BUSINESS_ADDRESS_COUNTRY,
          IN_ID_TYPE,
          IN_ID_NUMBER,
          IN_ID_ISSUE_DATE,
          IN_ID_ISSUE_COUNTRY,
          IN_PHONE_NUMBER,
          IN_MAKE_BY,          
          IN_MAKE_DATE, 'U', IN_CIF_NO, IN_SMART_ID_NUMBER );
    END IF;
    OPEN REF_CURSOR FOR SELECT NVL
    (
      TMP_FI_SUBJECT_CODE,IN_FI_SUBJECT_CODE
    )
    FROM DUAL;
  END SP_PERSON_INSERT;
  PROCEDURE SP_PERSON_HIST_INSERT
    (
      FI_SUBJECT_CODE_IN IN VARCHAR2
    )
  AS
    L_VERSION_NO NUMBER
    (
      10
    )
    ;
  BEGIN
    SELECT
      MAX(VERSION_NO)+1
    INTO
      L_VERSION_NO
    FROM
      PERSONAL_DATA_HIST
    WHERE
      FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
    IF L_VERSION_NO  IS NULL THEN
      L_VERSION_NO   := 1;
    END IF;
    INSERT
    INTO
      PERSONAL_DATA_HIST
    SELECT
      L_VERSION_NO,
      SYSDATE,
      A.*
    FROM
      PERSONAL_DATA A
    WHERE
      FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
  END SP_PERSON_HIST_INSERT;
  PROCEDURE SP_PERSON_UPDATE(
      RECORD_TYPE_IN                 IN VARCHAR2 ,
      FI_CODE_IN                     IN VARCHAR2 ,
      BRANCH_CODE_IN                 IN VARCHAR2 ,
      FI_SUBJECT_CODE_IN             IN VARCHAR2 ,
      TITLE_IN                       IN VARCHAR2 ,
      NAME_IN                        IN VARCHAR2 ,
      FATHERS_TITLE_IN               IN VARCHAR2 ,
      FATHERS_NAME_IN                IN VARCHAR2 ,
      MOTHERS_TITLE_IN               IN VARCHAR2 ,
      MOTHERS_NAME_IN                IN VARCHAR2 ,
      SPOUSES_TITLE_IN               IN VARCHAR2 ,
      SPOUSES_NAME_IN                IN VARCHAR2 ,
      SECTOR_TYPE_IN                 IN NUMBER ,
      SECTOR_CODE_IN                 IN NUMBER ,
      GENDER_IN                      IN VARCHAR2 ,
      DATE_OF_BIRTH_IN               IN DATE ,
      PLACE_OF_BIRTH_IN              IN VARCHAR2 ,
      COUNTRY_OF_BIRTH_IN            IN VARCHAR2 ,
      NATIONAL_ID_NUMBER_IN          IN VARCHAR2 ,
      NATIONAL_ID_AVAILABLE_IN       IN NUMBER ,
      TIN_IN                         IN VARCHAR2 ,
      PERMANENT_ADDRESS_STREET_IN    IN VARCHAR2 ,
      PERMANENT_ADDRESS_POSTAL_CD_IN IN NUMBER ,
      PERMANENT_ADDRESS_DISTRICT_IN  IN VARCHAR2 ,
      PERMANENT_ADDRESS_COUNTRY_IN   IN VARCHAR2 ,
      PRESENT_ADDRESS_STREET_IN      IN VARCHAR2 ,
      PRESENT_ADDRESS_POSTAL_CODE_IN IN NUMBER ,
      PRESENT_ADDRESS_DISTRICT_IN    IN VARCHAR2 ,
      PRESENT_ADDRESS_COUNTRY_IN     IN VARCHAR2 ,
      BUSINESS_ADDRESS_STREET_IN     IN VARCHAR2 ,
      BUSINESS_ADDRESS_POSTAL_CD_IN  IN NUMBER ,
      BUSINESS_ADDRESS_DISTRICT_IN   IN VARCHAR2 ,
      BUSINESS_ADDRESS_COUNTRY_IN    IN VARCHAR2 ,
      ID_TYPE_IN                     IN VARCHAR2 ,
      ID_NUMBER_IN                   IN VARCHAR2 ,
      ID_ISSUE_DATE_IN               IN DATE ,
      ID_ISSUE_COUNTRY_IN            IN VARCHAR2 ,
      PHONE_NUMBER_IN                IN VARCHAR2 ,
      MAKE_BY_IN                     IN VARCHAR2,
      MAKE_DATE_IN                   IN DATE,
      RECORD_STATUS_IN               IN VARCHAR2,
      IN_CIF_NO                      IN VARCHAR2,
      IN_SMART_ID_NUMBER             IN VARCHAR2)
  AS
    L_RECORD_STATUS VARCHAR2(1);
    L_CIF_NO VARCHAR2(9);
  BEGIN
    SELECT RECORD_STATUS, CIF_NO INTO L_RECORD_STATUS, L_CIF_NO FROM PERSONAL_DATA WHERE FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
    IF L_RECORD_STATUS != 'R' AND L_RECORD_STATUS != 'L' THEN    
      SP_PERSON_HIST_INSERT(FI_SUBJECT_CODE_IN);
      UPDATE
        PERSONAL_DATA
      SET
        RECORD_TYPE = RECORD_TYPE_IN ,
        FI_CODE     = FI_CODE_IN ,
        BRANCH_CODE =
        CASE
          WHEN BRANCH_CODE_IN = '0000'
          THEN BRANCH_CODE
          ELSE BRANCH_CODE_IN
        END ,
        TITLE                         = TITLE_IN ,
        NAME                          = NAME_IN ,
        FATHERS_TITLE                 = FATHERS_TITLE_IN ,
        FATHERS_NAME                  = FATHERS_NAME_IN ,
        MOTHERS_TITLE                 = MOTHERS_TITLE_IN ,
        MOTHERS_NAME                  = MOTHERS_NAME_IN ,
        SPOUSES_TITLE                 = SPOUSES_TITLE_IN ,
        SPOUSES_NAME                  = SPOUSES_NAME_IN ,
        SECTOR_TYPE                   = SECTOR_TYPE_IN ,
        SECTOR_CODE                   = SECTOR_CODE_IN ,
        GENDER                        = GENDER_IN ,
        DATE_OF_BIRTH                 = DATE_OF_BIRTH_IN ,
        PLACE_OF_BIRTH                = PLACE_OF_BIRTH_IN ,
        COUNTRY_OF_BIRTH              = COUNTRY_OF_BIRTH_IN ,
        NATIONAL_ID_NUMBER            = NATIONAL_ID_NUMBER_IN ,
        NATIONAL_ID_AVAILABLE         = NATIONAL_ID_AVAILABLE_IN ,
        TIN                           = TIN_IN ,
        PERMANENT_ADDRESS_STREET      = PERMANENT_ADDRESS_STREET_IN ,
        PERMANENT_ADDRESS_POSTAL_CODE = PERMANENT_ADDRESS_POSTAL_CD_IN,
        PERMANENT_ADDRESS_DISTRICT    = PERMANENT_ADDRESS_DISTRICT_IN ,
        PERMANENT_ADDRESS_COUNTRY     = PERMANENT_ADDRESS_COUNTRY_IN ,
        PRESENT_ADDRESS_STREET        = PRESENT_ADDRESS_STREET_IN ,
        PRESENT_ADDRESS_POSTAL_CODE   = PRESENT_ADDRESS_POSTAL_CODE_IN ,
        PRESENT_ADDRESS_DISTRICT      = PRESENT_ADDRESS_DISTRICT_IN ,
        PRESENT_ADDRESS_COUNTRY       = PRESENT_ADDRESS_COUNTRY_IN ,
        BUSINESS_ADDRESS_STREET       = BUSINESS_ADDRESS_STREET_IN ,
        BUSINESS_ADDRESS_POSTAL_CODE  = BUSINESS_ADDRESS_POSTAL_CD_IN ,
        BUSINESS_ADDRESS_DISTRICT     = BUSINESS_ADDRESS_DISTRICT_IN ,
        BUSINESS_ADDRESS_COUNTRY      = BUSINESS_ADDRESS_COUNTRY_IN ,
        ID_TYPE                       = ID_TYPE_IN ,
        ID_NUMBER                     = ID_NUMBER_IN ,
        ID_ISSUE_DATE                 = ID_ISSUE_DATE_IN ,
        ID_ISSUE_COUNTRY              = ID_ISSUE_COUNTRY_IN ,
        PHONE_NUMBER                  = PHONE_NUMBER_IN ,
        MAKE_BY                       = MAKE_BY_IN ,
        MAKE_DATE                     = sysdate ,
        RECORD_STATUS                 = RECORD_STATUS_IN,
        CIF_NO                        = IN_CIF_NO,
        SMART_ID_NUMBER               = IN_SMART_ID_NUMBER
      WHERE
        FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
    ELSIF L_CIF_NO IS NULL THEN
      SP_PERSON_HIST_INSERT(FI_SUBJECT_CODE_IN);
      UPDATE
        PERSONAL_DATA
      SET
        CIF_NO = IN_CIF_NO
      WHERE
        FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;  
    END IF;
  END SP_PERSON_UPDATE;
  PROCEDURE SP_GET_PERSON_BY_SMART_ID(
      SMART_ID_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT 
    RECORD_TYPE "RecordType",
    FI_CODE "FICode",
    BRANCH_CODE "BranchCode",
    FI_SUBJECT_CODE "FISubjectCode",
    TITLE "Title",
    NAME "Name",
    FATHERS_TITLE "FathersTitle",
    FATHERS_NAME "FathersName",
    MOTHERS_TITLE "MothersTitle",
    MOTHERS_NAME "MothersName",
    SPOUSES_TITLE "SpousesTitle",
    SPOUSES_NAME "SpousesName",
    SECTOR_TYPE "SectorType",
    SECTOR_CODE "SectorCode",
    GENDER "Gender",
    DATE_OF_BIRTH "DateOfBirth",
    PLACE_OF_BIRTH "PlaceOfBirth",
    COUNTRY_OF_BIRTH "CountryOfBirth",
    NATIONAL_ID_NUMBER "NationalIDNumber",
    NATIONAL_ID_AVAILABLE "NationalIDAvailable",
    TIN "Tin",
    ID_TYPE "IDType",
    ID_NUMBER "IDNumber",
    ID_ISSUE_DATE "IDIssueDate",
    ID_ISSUE_COUNTRY "IDIssueCountryCode",
    PHONE_NUMBER "PhoneNumber",
    MAKE_BY "MakeBy",
    MAKE_DATE "MakeDate",
    RECORD_STATUS "RecordStatus",
    CIF_NO "CifNo",
    SMART_ID_NUMBER "SmartIDNumber",
    PERMANENT_ADDRESS_STREET "Street",
    PERMANENT_ADDRESS_POSTAL_CODE "PostalCode",
    PERMANENT_ADDRESS_DISTRICT "District",
    PERMANENT_ADDRESS_COUNTRY "CountryCode",
    PRESENT_ADDRESS_STREET "Street",
    PRESENT_ADDRESS_POSTAL_CODE "PostalCode",
    PRESENT_ADDRESS_DISTRICT "District",
    PRESENT_ADDRESS_COUNTRY "CountryCode",
    BUSINESS_ADDRESS_STREET "Street",
    BUSINESS_ADDRESS_POSTAL_CODE "PostalCode",
    BUSINESS_ADDRESS_DISTRICT "District",
    BUSINESS_ADDRESS_COUNTRY "CountryCode"
    FROM PERSONAL_DATA WHERE SMART_ID_NUMBER = SMART_ID_IN;
  END SP_GET_PERSON_BY_SMART_ID;
  PROCEDURE SP_INSTITUTION_INSERT(
      RECORD_TYPE_IN                 IN VARCHAR2,
      FI_CODE_IN                     IN VARCHAR2,
      BRANCH_CODE_IN                 IN VARCHAR2,
      FI_SUBJECT_CODE_IN             IN VARCHAR2,
      TITLE_IN                       IN VARCHAR2,
      TRADE_NAME_IN                  IN VARCHAR2,
      SECTOR_TYPE_IN                 IN NUMBER,
      SECTOR_CODE_IN                 IN NUMBER,
      LEGAL_FORM_IN                  IN NUMBER,
      REGISTRATION_NUMBER_RJSC_IN    IN VARCHAR2,
      REGISTRATION_DATE_RJSC_IN      IN DATE,
      TIN_IN                         IN VARCHAR2,
      BUSINESS_ADDRESS_STREET_IN     IN VARCHAR2,
      BUSINESS_ADDRESS_POSTAL_CD_IN  IN NUMBER,
      BUSINESS_ADDRESS_DISTRICT_IN   IN VARCHAR2,
      BUSINESS_ADDRESS_COUNTRY_IN    IN VARCHAR2,
      FACTORY_ADDRESS_STREET_IN      IN VARCHAR2,
      FACTORY_ADDRESS_POSTAL_CODE_IN IN NUMBER,
      FACTORY_ADDRESS_DISTRICT_IN    IN VARCHAR2,
      FACTORY_ADDRESS_COUNTRY_IN     IN VARCHAR2,
      CRG_SCORING_IN                 IN NUMBER,
      CREDIT_RATING_IN               IN NUMBER,
      PHONE_NUMBER_IN                IN VARCHAR2,
      MAKE_BY_IN                     IN VARCHAR2,
      MAKE_DATE_IN                   IN DATE,
      RECORD_STATUS_IN               IN VARCHAR2,
      IN_CIF_NO                      IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
    TMP_FI_SUBJECT_CODE VARCHAR2 ( 16 ) ;
  BEGIN
    IF FI_SUBJECT_CODE_IN IS NULL THEN
      SELECT
        RECORD_TYPE_IN
        ||FI_CODE_IN
        ||BRANCH_CODE_IN
        ||LPAD(TO_CHAR(SEQ_INSTITUTION.NEXTVAL),8,'0')
      INTO
        TMP_FI_SUBJECT_CODE
      FROM
        DUAL;
      INSERT
      INTO
        INSTITUTIONS
        (
          RECORD_TYPE,
          FI_CODE,
          BRANCH_CODE,
          FI_SUBJECT_CODE,
          TITLE,
          TRADE_NAME,
          SECTOR_TYPE,
          SECTOR_CODE,
          LEGAL_FORM,
          REGISTRATION_NUMBER_RJSC,
          REGISTRATION_DATE_RJSC,
          TIN,
          BUSINESS_ADDRESS_STREET,
          BUSINESS_ADDRESS_POSTAL_CODE,
          BUSINESS_ADDRESS_DISTRICT,
          BUSINESS_ADDRESS_COUNTRY,
          FACTORY_ADDRESS_STREET,
          FACTORY_ADDRESS_POSTAL_CODE,
          FACTORY_ADDRESS_DISTRICT,
          FACTORY_ADDRESS_COUNTRY,
          CRG_SCORING,
          CREDIT_RATING,
          PHONE_NUMBER,
          MAKE_BY,
          MAKE_DATE,
          RECORD_STATUS,
          CIF_NO
        )
        VALUES
        (
          RECORD_TYPE_IN,
          FI_CODE_IN,
          BRANCH_CODE_IN,
          TMP_FI_SUBJECT_CODE,
          TITLE_IN,
          TRADE_NAME_IN,
          SECTOR_TYPE_IN,
          SECTOR_CODE_IN,
          LEGAL_FORM_IN,
          REGISTRATION_NUMBER_RJSC_IN,
          REGISTRATION_DATE_RJSC_IN,
          TIN_IN,
          BUSINESS_ADDRESS_STREET_IN,
          BUSINESS_ADDRESS_POSTAL_CD_IN,
          BUSINESS_ADDRESS_DISTRICT_IN,
          BUSINESS_ADDRESS_COUNTRY_IN,
          FACTORY_ADDRESS_STREET_IN,
          FACTORY_ADDRESS_POSTAL_CODE_IN,
          FACTORY_ADDRESS_DISTRICT_IN,
          FACTORY_ADDRESS_COUNTRY_IN,
          CRG_SCORING_IN,
          CREDIT_RATING_IN,
          PHONE_NUMBER_IN,
          MAKE_BY_IN,
          sysdate,
          RECORD_STATUS_IN,
          IN_CIF_NO
        );
    ELSE
      SP_INSTITUTION_UPDATE( RECORD_TYPE_IN, FI_CODE_IN, BRANCH_CODE_IN, FI_SUBJECT_CODE_IN, TITLE_IN, TRADE_NAME_IN,
      SECTOR_TYPE_IN, SECTOR_CODE_IN, LEGAL_FORM_IN, REGISTRATION_NUMBER_RJSC_IN, REGISTRATION_DATE_RJSC_IN, TIN_IN,
      BUSINESS_ADDRESS_STREET_IN, BUSINESS_ADDRESS_POSTAL_CD_IN, BUSINESS_ADDRESS_DISTRICT_IN,
      BUSINESS_ADDRESS_COUNTRY_IN, FACTORY_ADDRESS_STREET_IN, FACTORY_ADDRESS_POSTAL_CODE_IN,
      FACTORY_ADDRESS_DISTRICT_IN, FACTORY_ADDRESS_COUNTRY_IN, CRG_SCORING_IN, CREDIT_RATING_IN, PHONE_NUMBER_IN,
      MAKE_BY_IN, MAKE_DATE_IN, 'U', IN_CIF_NO );
    END IF;
    OPEN REF_CURSOR FOR SELECT NVL
    (
      TMP_FI_SUBJECT_CODE,FI_SUBJECT_CODE_IN
    )
    FROM DUAL;
  END SP_INSTITUTION_INSERT;
  PROCEDURE SP_INSTITUTION_HIST_INSERT
    (
      FI_SUBJECT_CODE_IN IN VARCHAR2
    )
  AS
    L_VERSION_NO NUMBER
    (
      10
    )
    ;
  BEGIN
    SELECT
      MAX(VERSION_NO)+1
    INTO
      L_VERSION_NO
    FROM
      INSTITUTIONS_HIST
    WHERE
      FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
    IF L_VERSION_NO  IS NULL THEN
      L_VERSION_NO   := 1;
    END IF;
    INSERT
    INTO
      INSTITUTIONS_HIST
    SELECT
      L_VERSION_NO,
      SYSDATE,
      A.*
    FROM
      INSTITUTIONS A
    WHERE
      FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
  END SP_INSTITUTION_HIST_INSERT;
  PROCEDURE SP_INSTITUTION_UPDATE(
      RECORD_TYPE_IN                IN VARCHAR2,
      FI_CODE_IN                    IN VARCHAR2,
      BRANCH_CODE_IN                IN VARCHAR2,
      FI_SUBJECT_CODE_IN            IN VARCHAR2,
      TITLE_IN                      IN VARCHAR2,
      TRADE_NAME_IN                 IN VARCHAR2,
      SECTOR_TYPE_IN                IN NUMBER,
      SECTOR_CODE_IN                IN NUMBER,
      LEGAL_FORM_IN                 IN NUMBER,
      REGISTRATION_NUMBER_RJSC_IN   IN VARCHAR2,
      REGISTRATION_DATE_RJSC_IN     IN DATE,
      TIN_IN                        IN VARCHAR2,
      BUSINESS_ADDRESS_STREET_IN    IN VARCHAR2,
      BUSINESS_ADDRESS_POSTAL_CD_IN IN NUMBER,
      BUSINESS_ADDRESS_DISTRICT_IN  IN VARCHAR2,
      BUSINESS_ADDRESS_COUNTRY_IN   IN VARCHAR2,
      FACTORY_ADDRESS_STREET_IN     IN VARCHAR2,
      FACTORY_ADDRESS_POSTAL_CD_IN  IN NUMBER,
      FACTORY_ADDRESS_DISTRICT_IN   IN VARCHAR2,
      FACTORY_ADDRESS_COUNTRY_IN    IN VARCHAR2,
      CRG_SCORING_IN                IN NUMBER,
      CREDIT_RATING_IN              IN NUMBER,
      PHONE_NUMBER_IN               IN VARCHAR2,
      MAKE_BY_IN                    IN VARCHAR2,
      MAKE_DATE_IN                  IN DATE,
      RECORD_STATUS_IN              IN VARCHAR2,
      IN_CIF_NO                     IN VARCHAR2)
  AS
    P_RECORD_STATUS VARCHAR2(1);
    P_CIF_NO VARCHAR2(9);
  BEGIN
    SELECT RECORD_STATUS, CIF_NO INTO P_RECORD_STATUS, P_CIF_NO FROM INSTITUTIONS WHERE FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
    IF P_RECORD_STATUS != 'R' AND P_RECORD_STATUS != 'L' THEN    
      SP_INSTITUTION_HIST_INSERT(FI_SUBJECT_CODE_IN);
      UPDATE
        INSTITUTIONS
      SET
        RECORD_TYPE = RECORD_TYPE_IN ,
        FI_CODE     = FI_CODE_IN ,
        BRANCH_CODE =
        CASE
          WHEN BRANCH_CODE_IN = '0000'
          THEN BRANCH_CODE
          ELSE BRANCH_CODE_IN
        END,
        TITLE                        = TITLE_IN ,
        TRADE_NAME                   = TRADE_NAME_IN ,
        SECTOR_TYPE                  = SECTOR_TYPE_IN ,
        SECTOR_CODE                  = SECTOR_CODE_IN ,
        LEGAL_FORM                   = LEGAL_FORM_IN ,
        REGISTRATION_NUMBER_RJSC     = REGISTRATION_NUMBER_RJSC_IN ,
        REGISTRATION_DATE_RJSC       = REGISTRATION_DATE_RJSC_IN ,
        TIN                          = TIN_IN ,
        BUSINESS_ADDRESS_STREET      = BUSINESS_ADDRESS_STREET_IN ,
        BUSINESS_ADDRESS_POSTAL_CODE = BUSINESS_ADDRESS_POSTAL_CD_IN,
        BUSINESS_ADDRESS_DISTRICT    = BUSINESS_ADDRESS_DISTRICT_IN ,
        BUSINESS_ADDRESS_COUNTRY     = BUSINESS_ADDRESS_COUNTRY_IN ,
        FACTORY_ADDRESS_STREET       = FACTORY_ADDRESS_STREET_IN ,
        FACTORY_ADDRESS_POSTAL_CODE  = FACTORY_ADDRESS_POSTAL_CD_IN ,
        FACTORY_ADDRESS_DISTRICT     = FACTORY_ADDRESS_DISTRICT_IN ,
        FACTORY_ADDRESS_COUNTRY      = FACTORY_ADDRESS_COUNTRY_IN ,
        CRG_SCORING                  = CRG_SCORING_IN ,
        CREDIT_RATING                = CREDIT_RATING_IN ,
        PHONE_NUMBER                 = PHONE_NUMBER_IN ,
        MAKE_BY                      = MAKE_BY_IN ,
        MAKE_DATE                    = sysdate,
        RECORD_STATUS                = RECORD_STATUS_IN,
        CIF_NO                       = IN_CIF_NO
      WHERE
        FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
    ELSIF P_CIF_NO IS NULL THEN
      SP_INSTITUTION_HIST_INSERT(FI_SUBJECT_CODE_IN);
      UPDATE
        INSTITUTIONS
      SET
        CIF_NO = IN_CIF_NO
      WHERE
        FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
    END IF;
  END SP_INSTITUTION_UPDATE;
  PROCEDURE SP_GET_INSTITUTION(
      FI_SUBJECT_CODE_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT RECORD_TYPE,
    FI_CODE,
    BRANCH_CODE,
    FI_SUBJECT_CODE,
    TITLE,
    TRADE_NAME,
    SECTOR_TYPE,
    SECTOR_CODE,
    LEGAL_FORM,
    REGISTRATION_NUMBER_RJSC,
    REGISTRATION_DATE_RJSC,
    TIN,
    BUSINESS_ADDRESS_STREET,
    BUSINESS_ADDRESS_POSTAL_CODE,
    BUSINESS_ADDRESS_DISTRICT,
    BUSINESS_ADDRESS_COUNTRY,
    FACTORY_ADDRESS_STREET,
    FACTORY_ADDRESS_POSTAL_CODE,
    FACTORY_ADDRESS_DISTRICT,
    FACTORY_ADDRESS_COUNTRY,
    CRG_SCORING,
    CREDIT_RATING,
    PHONE_NUMBER,
    MAKE_BY,
    MAKE_DATE,
    RECORD_STATUS,
    CIF_NO FROM INSTITUTIONS WHERE FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN ;
  END SP_GET_INSTITUTION;
  PROCEDURE SP_GET_INSTITUTION_BY_CIF_NO(
      CIF_NO_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT 
    RECORD_TYPE "RecordType",
    FI_CODE "FICode",
    BRANCH_CODE "BranchCode",
    FI_SUBJECT_CODE "FISubjectCode",
    TITLE "Title",
    TRADE_NAME "TradeName",
    SECTOR_TYPE "SectorType",
    SECTOR_CODE "SectorCode",
    LEGAL_FORM "LegalForm",
    REGISTRATION_NUMBER_RJSC "RegistrationNumberRJSC",
    REGISTRATION_DATE_RJSC "RegistrationDateRJSC",
    TIN "Tin",
    CRG_SCORING "CRGScoring",
    CREDIT_RATING "CreditRating",
    PHONE_NUMBER "PhoneNumber",
    MAKE_BY "MakeBy",
    MAKE_DATE "MakeDate",
    RECORD_STATUS "RecordStatus",
    CIF_NO "CifNo",
    BUSINESS_ADDRESS_STREET "Street",
    BUSINESS_ADDRESS_POSTAL_CODE "PostalCode",
    BUSINESS_ADDRESS_DISTRICT "District",
    BUSINESS_ADDRESS_COUNTRY "CountryCode",
    FACTORY_ADDRESS_STREET "Street",
    FACTORY_ADDRESS_POSTAL_CODE "PostalCode",    
    FACTORY_ADDRESS_DISTRICT "District",
    FACTORY_ADDRESS_COUNTRY "CountryCode"    
    FROM INSTITUTIONS WHERE CIF_NO = CIF_NO_IN ;
  END SP_GET_INSTITUTION_BY_CIF_NO;
  PROCEDURE SP_GET_PERSON(
      FI_SUBJECT_CODE_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT RECORD_TYPE,
    FI_CODE,
    BRANCH_CODE,
    FI_SUBJECT_CODE,
    TITLE,
    NAME,
    FATHERS_TITLE,
    FATHERS_NAME,
    MOTHERS_TITLE,
    MOTHERS_NAME,
    SPOUSES_TITLE,
    SPOUSES_NAME,
    SECTOR_TYPE,
    SECTOR_CODE,
    GENDER,
    DATE_OF_BIRTH,
    PLACE_OF_BIRTH,
    COUNTRY_OF_BIRTH,
    NATIONAL_ID_NUMBER,
    NATIONAL_ID_AVAILABLE,
    TIN,
    PERMANENT_ADDRESS_STREET,
    PERMANENT_ADDRESS_POSTAL_CODE,
    PERMANENT_ADDRESS_DISTRICT,
    PERMANENT_ADDRESS_COUNTRY,
    PRESENT_ADDRESS_STREET,
    PRESENT_ADDRESS_POSTAL_CODE,
    PRESENT_ADDRESS_DISTRICT,
    PRESENT_ADDRESS_COUNTRY,
    BUSINESS_ADDRESS_STREET,
    BUSINESS_ADDRESS_POSTAL_CODE,
    BUSINESS_ADDRESS_DISTRICT,
    BUSINESS_ADDRESS_COUNTRY,
    ID_TYPE,
    ID_NUMBER,
    ID_ISSUE_DATE,
    ID_ISSUE_COUNTRY,
    PHONE_NUMBER,
    MAKE_BY,
    MAKE_DATE,
    RECORD_STATUS,
    CIF_NO,
    SMART_ID_NUMBER
    FROM PERSONAL_DATA WHERE FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
  END SP_GET_PERSON;
  PROCEDURE SP_GET_PERSON_BY_CIF_NO(
      CIF_NO_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT 
    RECORD_TYPE "RecordType",
    FI_CODE "FICode",
    BRANCH_CODE "BranchCode",
    FI_SUBJECT_CODE "FISubjectCode",
    TITLE "Title",
    NAME "Name",
    FATHERS_TITLE "FathersTitle",
    FATHERS_NAME "FathersName",
    MOTHERS_TITLE "MothersTitle",
    MOTHERS_NAME "MothersName",
    SPOUSES_TITLE "SpousesTitle",
    SPOUSES_NAME "SpousesName",
    SECTOR_TYPE "SectorType",
    SECTOR_CODE "SectorCode",
    GENDER "Gender",
    DATE_OF_BIRTH "DateOfBirth",
    PLACE_OF_BIRTH "PlaceOfBirth",
    COUNTRY_OF_BIRTH "CountryOfBirth",
    NATIONAL_ID_NUMBER "NationalIDNumber",
    NATIONAL_ID_AVAILABLE "NationalIDAvailable",
    TIN "Tin",
    ID_TYPE "IDType",
    ID_NUMBER "IDNumber",
    ID_ISSUE_DATE "IDIssueDate",
    ID_ISSUE_COUNTRY "IDIssueCountryCode",
    PHONE_NUMBER "PhoneNumber",
    MAKE_BY "MakeBy",
    MAKE_DATE "MakeDate",
    RECORD_STATUS "RecordStatus",
    CIF_NO "CifNo",
    SMART_ID_NUMBER "SmartIDNumber",
    PERMANENT_ADDRESS_STREET "Street",
    PERMANENT_ADDRESS_POSTAL_CODE "PostalCode",
    PERMANENT_ADDRESS_DISTRICT "District",
    PERMANENT_ADDRESS_COUNTRY "CountryCode",
    PRESENT_ADDRESS_STREET "Street",
    PRESENT_ADDRESS_POSTAL_CODE "PostalCode",
    PRESENT_ADDRESS_DISTRICT "District",
    PRESENT_ADDRESS_COUNTRY "CountryCode",
    BUSINESS_ADDRESS_STREET "Street",
    BUSINESS_ADDRESS_POSTAL_CODE "PostalCode",
    BUSINESS_ADDRESS_DISTRICT "District",
    BUSINESS_ADDRESS_COUNTRY "CountryCode"    
    FROM PERSONAL_DATA WHERE CIF_NO = CIF_NO_IN;
  END SP_GET_PERSON_BY_CIF_NO;
  PROCEDURE SP_OWNER_LINK_INSERT(
      RECORD_TYPE_IN                 VARCHAR2,
      FI_CODE_IN                     VARCHAR2,
      BRANCH_CODE_IN                 VARCHAR2,
      INSTITUTION_FI_SUBJECT_CODE_IN VARCHAR2,
      ROLE_IN                        VARCHAR2,
      OWNER_FI_SUBJECT_CODE_IN       VARCHAR2,
      MAKE_BY_IN                     VARCHAR2,
      MAKE_DATE_IN                   DATE,
      RECORD_STATUS_IN               VARCHAR2 )
  AS
    L_EXISTS INT;
  BEGIN
    SELECT
      COUNT(1)
    INTO
      L_EXISTS
    FROM
      INSTITUTION_OWNER_LINKS A
    WHERE
      A.INSTITUTION_FI_SUBJECT_CODE = INSTITUTION_FI_SUBJECT_CODE_IN
    AND A.OWNER_FI_SUBJECT_CODE     = OWNER_FI_SUBJECT_CODE_IN;
    IF L_EXISTS                    IS NULL THEN
      L_EXISTS                     := 0;
    END IF;
    IF L_EXISTS = 0 THEN
      INSERT
      INTO
        INSTITUTION_OWNER_LINKS
        (
          RECORD_TYPE,
          FI_CODE,
          BRANCH_CODE,
          INSTITUTION_FI_SUBJECT_CODE,
          ROLE,
          OWNER_FI_SUBJECT_CODE,
          MAKE_BY,
          MAKE_DATE,
          RECORD_STATUS
        )
        VALUES
        (
          RECORD_TYPE_IN,
          FI_CODE_IN,
          BRANCH_CODE_IN,
          INSTITUTION_FI_SUBJECT_CODE_IN,
          ROLE_IN,
          OWNER_FI_SUBJECT_CODE_IN,
          MAKE_BY_IN,
          sysdate,
          RECORD_STATUS_IN
        );

      UPDATE
        INSTITUTIONS
      SET
        RECORD_STATUS = 'L'
      WHERE
              FI_SUBJECT_CODE = INSTITUTION_FI_SUBJECT_CODE_IN
          AND RECORD_STATUS = 'R'
          AND FI_SUBJECT_CODE LIKE 'I%';

    ELSE
      SP_OWNER_LINK_UPDATE( RECORD_TYPE_IN, FI_CODE_IN, BRANCH_CODE_IN, INSTITUTION_FI_SUBJECT_CODE_IN, ROLE_IN,
      OWNER_FI_SUBJECT_CODE_IN, MAKE_BY_IN, MAKE_DATE_IN, 'U' );
    END IF;
  END SP_OWNER_LINK_INSERT;
  PROCEDURE SP_OWNER_LINK_HIST_INSERT
    (
      INSTITUTION_FI_SUBJECT_CODE_IN IN VARCHAR2,
      OWNER_FI_SUBJECT_CODE_IN       IN VARCHAR2
    )
  AS
    L_VERSION_NO NUMBER
    (
      10
    )
    ;
  BEGIN
    SELECT
      MAX(VERSION_NO)+1
    INTO
      L_VERSION_NO
    FROM
      INSTITUTION_OWNER_LINKS_HIST A
    WHERE
      A.INSTITUTION_FI_SUBJECT_CODE = INSTITUTION_FI_SUBJECT_CODE_IN
    AND A.OWNER_FI_SUBJECT_CODE     = OWNER_FI_SUBJECT_CODE_IN;
    IF L_VERSION_NO                IS NULL THEN
      L_VERSION_NO                 :=1;
    END IF;
    INSERT
    INTO
      INSTITUTION_OWNER_LINKS_HIST
    SELECT
      L_VERSION_NO,
      SYSDATE,
      A.*
    FROM
      INSTITUTION_OWNER_LINKS A
    WHERE
      A.INSTITUTION_FI_SUBJECT_CODE = INSTITUTION_FI_SUBJECT_CODE_IN
    AND A.OWNER_FI_SUBJECT_CODE     = OWNER_FI_SUBJECT_CODE_IN;
  END SP_OWNER_LINK_HIST_INSERT;
  PROCEDURE SP_OWNER_LINK_UPDATE(
      RECORD_TYPE_IN                 VARCHAR2,
      FI_CODE_IN                     VARCHAR2,
      BRANCH_CODE_IN                 VARCHAR2,
      INSTITUTION_FI_SUBJECT_CODE_IN VARCHAR2,
      ROLE_IN                        VARCHAR2,
      OWNER_FI_SUBJECT_CODE_IN       VARCHAR2,
      MAKE_BY_IN                     VARCHAR2,
      MAKE_DATE_IN                   DATE,
      RECORD_STATUS_IN               VARCHAR2 )
  AS
    P_RECORD_STATUS VARCHAR2(1);
  BEGIN
    SELECT RECORD_STATUS INTO P_RECORD_STATUS FROM INSTITUTION_OWNER_LINKS WHERE INSTITUTION_FI_SUBJECT_CODE = INSTITUTION_FI_SUBJECT_CODE_IN AND OWNER_FI_SUBJECT_CODE = OWNER_FI_SUBJECT_CODE_IN;
    IF P_RECORD_STATUS != 'R' THEN
      SP_OWNER_LINK_HIST_INSERT(INSTITUTION_FI_SUBJECT_CODE_IN, OWNER_FI_SUBJECT_CODE_IN);
      UPDATE
        INSTITUTION_OWNER_LINKS
      SET
        RECORD_TYPE   = RECORD_TYPE_IN,
        FI_CODE       = FI_CODE_IN,
        BRANCH_CODE   = DECODE(BRANCH_CODE_IN,'0000',BRANCH_CODE,BRANCH_CODE_IN),
        ROLE          =ROLE_IN,
        MAKE_BY       = MAKE_BY_IN,
        MAKE_DATE     = sysdate,
        RECORD_STATUS = RECORD_STATUS_IN
      WHERE
        INSTITUTION_FI_SUBJECT_CODE = INSTITUTION_FI_SUBJECT_CODE_IN
      AND OWNER_FI_SUBJECT_CODE     = OWNER_FI_SUBJECT_CODE_IN ;
    END IF;
  END SP_OWNER_LINK_UPDATE;
  PROCEDURE SP_GET_SUBJECT_BY_CONTRACT(
      FI_CONTRACT_CODE IN VARCHAR,
      REF_CURSOR OUT SYS_REFCURSOR )
  AS
    L_SUBJECT_CODE VARCHAR ( 16 ) ;
  BEGIN
    SELECT
      A.SUBJECT_CODE
    INTO
      L_SUBJECT_CODE
    FROM
      (
        SELECT
          FI_SUBJECT_CODE SUBJECT_CODE,
          FI_CONTRACT_CODE CONTRACT_CODE
        FROM
          INSTALMENT_CONTRACTS
        UNION
        SELECT
          FI_SUBJECT_CODE,
          FI_CONTRACT_CODE
        FROM
          NON_INSTALMENT_CONTRACTS
        UNION
        SELECT
          FI_SUBJECT_CODE,
          FI_CONTRACT_CODE
        FROM
          CARD_CONTRACTS
      )
      A
    WHERE
      A.CONTRACT_CODE            = FI_CONTRACT_CODE;
    IF SUBSTR(L_SUBJECT_CODE,1,1)='P' THEN
      SP_GET_PERSON ( L_SUBJECT_CODE,REF_CURSOR) ;
    ELSE
      SP_GET_INSTITUTION(L_SUBJECT_CODE, REF_CURSOR);
    END IF;
  END SP_GET_SUBJECT_BY_CONTRACT;
  PROCEDURE SP_GET_SUBJECTS_BY_FILTERS(
      BRANCH_CODE_IN     IN VARCHAR2,
      FI_SUBJECT_CODE_IN IN VARCHAR2,
      FI_SUBJECT_NAME_IN IN VARCHAR2,
      FATHERS_NAME_IN IN VARCHAR2,
      DATE_OF_BIRTH_IN IN DATE,
      CIF_NO_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR 
    SELECT 
        BRANCH_CODE,
        FI_SUBJECT_CODE,
        TITLE,
        NAME,
        FATHERS_TITLE,
        FATHERS_NAME,
        MOTHERS_TITLE,
        MOTHERS_NAME,
        SPOUSES_TITLE,
        DATE_OF_BIRTH,
        CIF_NO,
        RECORD_STATUS 
    FROM 
        PERSONAL_DATA 
    WHERE 
        RECORD_STATUS != 'D' 
    AND BRANCH_CODE = NVL(BRANCH_CODE_IN,BRANCH_CODE)
    AND FI_SUBJECT_CODE = NVL( FI_SUBJECT_CODE_IN,FI_SUBJECT_CODE)
    AND LOWER(NAME) LIKE LOWER(NVL('%'||FI_SUBJECT_NAME_IN||'%','%'))
    AND LOWER(NVL(FATHERS_NAME,'xxx')) LIKE LOWER(NVL('%'||FATHERS_NAME_IN||'%','%'))
    AND DATE_OF_BIRTH = NVL(DATE_OF_BIRTH_IN, DATE_OF_BIRTH)
    AND ((CIF_NO IS NOT NULL AND CIF_NO_IN IS NOT NULL AND CIF_NO = NVL(CIF_NO_IN, CIF_NO))
        OR (CIF_NO_IN IS NULL));
  END SP_GET_SUBJECTS_BY_FILTERS;
  PROCEDURE SP_GET_INSTITUTIONS_BY_FILTERS(
      BRANCH_CODE_IN     IN VARCHAR2,
      FI_SUBJECT_CODE_IN IN VARCHAR2,
      FI_SUBJECT_NAME_IN IN VARCHAR2,
      BUSINESS_ADDRESS_IN IN VARCHAR2,
      CIF_NO_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
      OPEN REF_CURSOR 
       FOR 
    SELECT BRANCH_CODE,
           FI_SUBJECT_CODE,
           TITLE,
           TRADE_NAME,
           B.NAME LEGAL_FORM,
           BUSINESS_ADDRESS_STREET,
           CIF_NO,
           RECORD_STATUS 
      FROM INSTITUTIONS A 
      JOIN LOV_INSTITUTION_LEGAL_FORMS B 
        ON A.LEGAL_FORM = B.CODE 
     WHERE A.RECORD_STATUS != 'D' 
       AND BRANCH_CODE = NVL(BRANCH_CODE_IN,BRANCH_CODE) 
       AND FI_SUBJECT_CODE = NVL( FI_SUBJECT_CODE_IN, FI_SUBJECT_CODE) 
       AND LOWER(TRADE_NAME) LIKE LOWER(NVL('%'||FI_SUBJECT_NAME_IN||'%','%'))
       AND LOWER(NVL(BUSINESS_ADDRESS_STREET, 'xxx')) LIKE LOWER(NVL('%'||BUSINESS_ADDRESS_IN||'%','%'))
       AND ((CIF_NO IS NOT NULL AND CIF_NO_IN IS NOT NULL AND CIF_NO = NVL(CIF_NO_IN, CIF_NO))
            OR (CIF_NO_IN IS NULL));
  END SP_GET_INSTITUTIONS_BY_FILTERS;
  PROCEDURE SP_GET_OWNER_LINKS_BY_FILTERS(
      BRANCH_CODE_IN         IN VARCHAR2,
      FI_OWNER_CODE_IN       IN VARCHAR2,
      FI_OWNER_NAME_IN       IN VARCHAR2,
      FI_INSTITUTION_CODE_IN IN VARCHAR2,
      FI_INSTITUTION_NAME_IN IN VARCHAR2,
      REF_CURSOR OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN REF_CURSOR FOR SELECT A.RECORD_TYPE,
    A.FI_CODE,
    A.BRANCH_CODE,
    A.INSTITUTION_FI_SUBJECT_CODE,
    B.TRADE_NAME,
    D.NAME ROLE,
    A.OWNER_FI_SUBJECT_CODE,
    C.SUBJECT_NAME NAME,
    A.MAKE_BY,
    A.MAKE_DATE,
    A.RECORD_STATUS FROM INSTITUTION_OWNER_LINKS A JOIN INSTITUTIONS B ON A.INSTITUTION_FI_SUBJECT_CODE =
    B.FI_SUBJECT_CODE JOIN VW_SUBJECTS C ON A.OWNER_FI_SUBJECT_CODE                                 =
    C.FI_SUBJECT_CODE JOIN LOV_OWNER_TYPES D ON A.ROLE                                                = D.CODE WHERE
    A.RECORD_STATUS                                                                                  != 'D' AND
    A.BRANCH_CODE                                                                                       = NVL(
    BRANCH_CODE_IN,A.BRANCH_CODE) AND OWNER_FI_SUBJECT_CODE                                             = NVL(
    FI_OWNER_CODE_IN, OWNER_FI_SUBJECT_CODE) AND INSTITUTION_FI_SUBJECT_CODE                          = NVL(
    FI_INSTITUTION_CODE_IN, INSTITUTION_FI_SUBJECT_CODE) AND LOWER(B.TRADE_NAME) LIKE LOWER(NVL('%' ||
    FI_INSTITUTION_NAME_IN ||'%','%')) AND LOWER(C.SUBJECT_NAME) LIKE LOWER(NVL('%' ||FI_OWNER_NAME_IN ||'%','%'));
  END SP_GET_OWNER_LINKS_BY_FILTERS;
  PROCEDURE SP_PERSON_FLAG_DELETE(
      FI_SUBJECT_CODE_IN IN VARCHAR2,
      MAKE_BY_IN         IN VARCHAR2,
      MAKE_DATE_IN       IN DATE)
  AS
  BEGIN
    SP_PERSON_HIST_INSERT(FI_SUBJECT_CODE_IN);
    UPDATE
      PERSONAL_DATA
    SET
      RECORD_STATUS='D',
      MAKE_BY      = MAKE_BY_IN,
      MAKE_DATE    = sysdate
    WHERE
      FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
  END SP_PERSON_FLAG_DELETE;
  PROCEDURE SP_INSTITUTION_FLAG_DELETE(
      FI_SUBJECT_CODE_IN IN VARCHAR2,
      MAKE_BY_IN         IN VARCHAR2,
      MAKE_DATE_IN       IN DATE)
  AS
  BEGIN
    SP_INSTITUTION_HIST_INSERT(FI_SUBJECT_CODE_IN);
    UPDATE
      INSTITUTIONS
    SET
      RECORD_STATUS='D',
      MAKE_BY      = MAKE_BY_IN,
      MAKE_DATE    = sysdate
    WHERE
      FI_SUBJECT_CODE = FI_SUBJECT_CODE_IN;
  END SP_INSTITUTION_FLAG_DELETE;
  PROCEDURE SP_OWNER_LINK_FLAG_DELETE(
      FI_INSTITUTION_CODE_IN IN VARCHAR2,
      FI_PERSON_CODE_IN      IN VARCHAR2,
      MAKE_BY_IN             IN VARCHAR2,
      MAKE_DATE_IN           IN DATE)
  AS
  BEGIN
    SP_OWNER_LINK_HIST_INSERT(FI_INSTITUTION_CODE_IN,FI_PERSON_CODE_IN);
    UPDATE
      INSTITUTION_OWNER_LINKS
    SET
      RECORD_STATUS = 'D',
      MAKE_BY       = MAKE_BY_IN,
      MAKE_DATE     = sysdate
    WHERE
      INSTITUTION_FI_SUBJECT_CODE = FI_INSTITUTION_CODE_IN
    AND OWNER_FI_SUBJECT_CODE     = FI_PERSON_CODE_IN ;
  END SP_OWNER_LINK_FLAG_DELETE;
END PKG_SUBJECT;
