CREATE OR REPLACE PACKAGE PKG_VALIDATOR AS 

  PROCEDURE SP_VALIDATE_PERSON(P_MAKE_BY IN VARCHAR2);
  PROCEDURE SP_VALIDATE_INSTITUTION(P_MAKE_BY IN VARCHAR2);
  PROCEDURE SP_VALIDATE_OWNER_LINK(P_MAKE_BY IN VARCHAR2);
  
  PROCEDURE SP_VALIDATE_INST_CONTRACT(P_MAKE_BY IN VARCHAR2);
  PROCEDURE SP_VALIDATE_NON_INST_CONTRACT(P_MAKE_BY IN VARCHAR2);
  PROCEDURE SP_VALIDATE_CARD_CONTRACT(P_MAKE_BY IN VARCHAR2);
  PROCEDURE SP_VALIDATE_CONTRACT_LINK(P_MAKE_BY IN VARCHAR2);
  
  PROCEDURE SP_VALIDATE_ALL(P_MAKE_BY IN VARCHAR2);
END PKG_VALIDATOR;
