CREATE OR REPLACE PACKAGE PKG_MISC AS 

  PROCEDURE SP_GET_PARAMETERS(REF_CURSOR OUT SYS_REFCURSOR);

  PROCEDURE SP_GET_BRANCHES(REF_CURSOR OUT SYS_REFCURSOR);

  PROCEDURE SP_CLR_ERR_AND_RPT_OF_CURR_MTH;

END PKG_MISC;

 
